INSERT IGNORE INTO us_role_business_function SELECT null, 'ROLE_INTERNAL_USER', r1.BUSINESS_FUNCTION_ID, 1, now(), 1, now() FROM us_role_business_function r1 where r1.ROLE_ID='ROLE_REALM_ADMIN' and r1.BUSINESS_FUNCTION_ID!='ROLE_BF_NOTIFICATION_CC_APPROVE';
ALTER TABLE `fasp`.`rm_forecast_tree_node_data_mom` CHANGE COLUMN `CALCULATED_MMD_VALUE` `CALCULATED_MMD_VALUE` DECIMAL(18,4) UNSIGNED NULL ;
ALTER TABLE `fasp`.`rm_forecast_tree_node_data_mom` CHANGE COLUMN `DIFFERENCE` `DIFFERENCE` DECIMAL(18,4) NULL ,CHANGE COLUMN `SEASONALITY_PERC` `SEASONALITY_PERC` DECIMAL(6,2) NULL ,CHANGE COLUMN `MANUAL_CHANGE` `MANUAL_CHANGE` DECIMAL(18,4) NULL ;


/*[4:02:36 PM][ 3 ms]*/ INSERT INTO `fasp`.`ap_label`(`LABEL_ID`,`LABEL_EN`,`LABEL_FR`,`LABEL_SP`,`LABEL_PR`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`,`SOURCE_ID`) VALUES ( NULL,'Services',NULL,NULL,NULL,'1',NOW(),'1',NOW(),'43');
SELECT MAX(l.LABEL_ID) INTO @MAX FROM ap_label l ;
INSERT INTO `fasp`.`rm_forecast_method`(`FORECAST_METHOD_ID`,`REALM_ID`,`FORECAST_METHOD_TYPE_ID`,`LABEL_ID`,`ACTIVE`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`) VALUES ( NULL,'1','1',@MAX,'1','1',NOW(),'1',NOW());  