CREATE DEFINER=`faspUser`@`%` PROCEDURE `getManualJsonPushReport`(VAR_START_DATE DATETIME, VAR_STOP_DATE DATETIME, VAR_REALM_COUNTRY_IDS TEXT, VAR_PROGRAM_IDS TEXT)
BEGIN
	SET @startDate = VAR_START_DATE;
    SET @stopDate = VAR_STOP_DATE;
    SET @realmCountryIds = VAR_REALM_COUNTRY_IDS;
    SET @programIds = VAR_PROGRAM_IDS;
          
    SELECT 	
		im.MANUAL_INTEGRATION_ID,     
		p.PROGRAM_ID, p.PROGRAM_CODE, p.LABEL_ID `PROGRAM_LABEL_ID`, p.LABEL_EN `PROGRAM_LABEL_EN`, p.LABEL_FR `PROGRAM_LABEL_FR`, p.LABEL_SP `PROGRAM_LABEL_SP`, p.LABEL_PR `PROGRAM_LABEL_PR`,     
		im.VERSION_ID, i.INTEGRATION_ID, i.INTEGRATION_NAME, iv.INTEGRATION_VIEW_ID, iv.INTEGRATION_VIEW_DESC, iv.INTEGRATION_VIEW_NAME, i.FOLDER_LOCATION, i.FILE_NAME,     
		cb.USER_ID `CB_USER_ID`, cb.USERNAME `CB_USERNAME`, im.CREATED_DATE, im.COMPLETED_DATE 
	FROM rm_integration_manual im 
	LEFT JOIN vw_program p ON im.PROGRAM_ID=p.PROGRAM_ID 
	LEFT JOIN ap_integration i ON im.INTEGRATION_ID=i.INTEGRATION_ID 
	LEFT JOIN us_user cb ON im.CREATED_BY=cb.USER_ID 
	LEFT JOIN ap_integration_view iv ON i.INTEGRATION_VIEW_ID=iv.INTEGRATION_VIEW_ID  
	WHERE 
		im.CREATED_DATE BETWEEN @startDate AND @stopDate 
		AND (LENGTH(@realmCountryIds)=0 OR FIND_IN_SET(p.REALM_COUNTRY_ID, @realmCountryIds)) 
		AND (LENGTH(@programIds)=0 OR FIND_IN_SET(p.PROGRAM_ID, @programIds));
END