CREATE DEFINER=`faspUser`@`localhost` PROCEDURE `getUserListWithAccessToProgramId`(VAR_PROGRAM_ID INT)
BEGIN
    SET @varProgramId = VAR_PROGRAM_ID;
    SELECT rc.REALM_ID, p.REALM_COUNTRY_ID, p.HEALTH_AREA_ID, p.ORGANISATION_ID, p.FUNDING_SOURCE_ID, p.PROCUREMENT_AGENT_ID, p.PROGRAM_TYPE_ID into @varRealmId, @varRealmCountryId, @varHealthAreaId, @varOrganisationId, @varFundingSourceId, @varProcurementAgentId, @varProgramTypeId FROM vw_all_program p LEFT JOIN rm_realm_country rc ON p.REALM_COUNTRY_ID=rc.REALM_COUNTRY_ID where p.PROGRAM_ID=@varProgramId;
    SET @skipRoleList = "ROLE_APPLICATION_ADMIN,ROLE_REALM_ADMIN,ROLE_INTERNAL_USER";
    SET @spAccessBfList = "ROLE_BF_EDIT_PROGRAM,ROLE_BF_UPDATE_PROGRAM,ROLE_BF_LIST_PROGRAM,ROLE_BF_SET_UP_PROGRAM,ROLE_BF_CREATE_A_PROGRAM,ROLE_BF_SUPPLY_PLANNING_MODULE";
    SET @fcAccessBfList = "ROLE_BF_ADD_DATASET,ROLE_BF_EDIT_DATASET,ROLE_BF_LIST_DATASET,ROLE_BF_COMMIT_DATASET,ROLE_BF_IMPORT_DATASET,ROLE_BF_EXPORT_DATASET,ROLE_BF_LOAD_DELETE_DATASET,ROLE_BF_FORECASTING_MODULE";
    IF @varProgramTypeId = 1 THEN
		SET @accessBfList = @spAccessBfList;
    ELSEIF @varProgramTypeId = 2 THEN
		SET @accessBfList = @fcAccessBfList;
    END IF;
	
    SELECT group_concat(DISTINCT rbf.ROLE_ID) INTO @varRoleIdList FROM us_role_business_function rbf WHERE FIND_IN_SET(rbf.BUSINESS_FUNCTION_ID,@accessBfList) AND NOT FIND_IN_SET(rbf.ROLE_ID, @skipRoleList);
    
    SELECT 
        u.USER_ID, u.USERNAME, u.ORG_AND_COUNTRY, acl.ROLE_ID, l.LABEL_ID, l.LABEL_EN, l.LABEL_FR, l.LABEL_SP, l.LABEL_PR, 
        acl.REALM_COUNTRY_ID, c.LABEL_ID C_LABEL_ID, c.LABEL_EN C_LABEL_EN, c.LABEL_FR C_LABEL_FR, c.LABEL_SP C_LABEL_SP, c.LABEL_PR C_LABEL_PR,
        acl.HEALTH_AREA_ID, ha.LABEL_ID HA_LABEL_ID, ha.LABEL_EN HA_LABEL_EN, ha.LABEL_FR HA_LABEL_FR, ha.LABEL_SP HA_LABEL_SP, ha.LABEL_PR HA_LABEL_PR,
        acl.ORGANISATION_ID, o.LABEL_ID O_LABEL_ID, o.LABEL_EN O_LABEL_EN, o.LABEL_FR O_LABEL_FR, o.LABEL_SP O_LABEL_SP, o.LABEL_PR O_LABEL_PR,
        acl.FUNDING_SOURCE_ID, fs.LABEL_ID FS_LABEL_ID, fs.LABEL_EN FS_LABEL_EN, fs.LABEL_FR FS_LABEL_FR, fs.LABEL_SP FS_LABEL_SP, fs.LABEL_PR fs_LABEL_PR,
        acl.PROCUREMENT_AGENT_ID, pa.LABEL_ID PA_LABEL_ID, pa.LABEL_EN PA_LABEL_EN, pa.LABEL_FR PA_LABEL_FR, pa.LABEL_SP PA_LABEL_SP, pa.LABEL_PR PA_LABEL_PR,
        acl.PROGRAM_ID, p.LABEL_ID P_LABEL_ID, p.LABEL_EN P_LABEL_EN, p.LABEL_FR P_LABEL_FR, p.LABEL_SP P_LABEL_SP, p.LABEL_PR P_LABEL_PR
    FROM us_user_acl acl
    LEFT JOIN us_user u ON acl.USER_ID=u.USER_ID
    LEFT JOIN us_role r ON acl.ROLE_ID=r.ROLE_ID 
    LEFT JOIN ap_label l ON r.LABEL_ID=l.LABEL_ID
    LEFT JOIN rm_realm_country rc ON acl.REALM_COUNTRY_ID=rc.REALM_COUNTRY_ID
    LEFT JOIN vw_country c ON rc.COUNTRY_ID=c.COUNTRY_ID
    LEFT JOIN vw_health_area ha ON acl.HEALTH_AREA_ID=ha.HEALTH_AREA_ID
    LEFT JOIN vw_organisation o ON acl.ORGANISATION_ID=o.ORGANISATION_ID
    LEFT JOIN vw_funding_source fs ON acl.FUNDING_SOURCE_ID=fs.FUNDING_SOURCE_ID
    LEFT JOIN vw_procurement_agent pa ON acl.PROCUREMENT_AGENT_ID=pa.PROCUREMENT_AGENT_ID
    LEFT JOIN vw_all_program p ON acl.PROGRAM_ID=p.PROGRAM_ID
    WHERE 
        FIND_IN_SET (acl.ROLE_ID, @varRoleIdList)
        AND u.REALM_ID=@varRealmId 
        AND FIND_IN_SET(acl.ROLE_ID, @varRoleIdList)
        AND (acl.REALM_COUNTRY_ID is null OR acl.REALM_COUNTRY_ID=@varRealmCountryId)
        AND (acl.HEALTH_AREA_ID IS NULL OR FIND_IN_SET(acl.HEALTH_AREA_ID, @varHealthAreaId))
        AND (acl.ORGANISATION_ID is null OR acl.ORGANISATION_ID=@varOrganisationId)
        AND (acl.PROGRAM_ID is null OR acl.PROGRAM_ID=@varProgramId)
        AND (acl.FUNDING_SOURCE_ID IS NULL OR FIND_IN_SET(acl.FUNDING_SOURCE_ID, @varFundingSourceId))
        AND (acl.PROCUREMENT_AGENT_ID IS NULL OR FIND_IN_SET(acl.PROCUREMENT_AGENT_ID, @varProcurementAgentId));
END
