CREATE DEFINER=`faspUser`@`localhost` PROCEDURE `getVersionId`(PROGRAM_ID INT(10), VERSION_TYPE_ID INT(10), VERSION_STATUS_ID INT(10), NOTES TEXT, CREATED_BY INT(10), CREATED_DATE DATETIME)
BEGIN
	SET @programId = PROGRAM_ID;
	SET @cbUserId = CREATED_BY;
	SET @createdDate = CREATED_DATE;
	SET @versionTypeId = VERSION_TYPE_ID;
	SET @versionStatusId = VERSION_STATUS_ID;
	SET @notes = NOTES;
	INSERT INTO rm_program_version SELECT NULL, @programId, IFNULL(MAX(pv.VERSION_ID)+1,1), @versionTypeId, @versionStatusId, @notes, @cbUserId, @createdDate, @cbUserId, @createdDate, 0 FROM rm_program_version pv WHERE pv.`PROGRAM_ID`=@programId;
	SELECT pv.VERSION_ID INTO @versionId FROM rm_program_version pv WHERE pv.`PROGRAM_VERSION_ID`= LAST_INSERT_ID();
	UPDATE rm_program p SET p.CURRENT_VERSION_ID=@versionId WHERE p.PROGRAM_ID=@programId;
	SELECT pv.VERSION_ID, pv.NOTES, 
		pv.LAST_MODIFIED_DATE, lmb.USER_ID `LMB_USER_ID`, lmb.USERNAME `LMB_USERNAME`,
		pv.CREATED_DATE, cb.USER_ID `CB_USER_ID`, cb.USERNAME `CB_USERNAME`,
		vt.VERSION_TYPE_ID, vtl.LABEL_ID `VERSION_TYPE_LABEL_ID`, vtl.LABEL_EN `VERSION_TYPE_LABEL_EN`, vtl.LABEL_FR `VERSION_TYPE_LABEL_FR`, vtl.LABEL_SP `VERSION_TYPE_LABEL_SP`, vtl.LABEL_PR `VERSION_TYPE_LABEL_PR`, 
		vs.VERSION_STATUS_ID, vsl.LABEL_ID `VERSION_STATUS_LABEL_ID`, vsl.LABEL_EN `VERSION_STATUS_LABEL_EN`, vsl.LABEL_FR `VERSION_STATUS_LABEL_FR`, vsl.LABEL_SP `VERSION_STATUS_LABEL_SP`, vsl.LABEL_PR `VERSION_STATUS_LABEL_PR` 
	FROM rm_program_version pv 
	LEFT JOIN ap_version_type vt ON pv.VERSION_TYPE_ID=vt.VERSION_TYPE_ID
	LEFT JOIN ap_label vtl ON vt.LABEL_ID=vtl.LABEL_ID 
	LEFT JOIN ap_version_status vs ON pv.VERSION_STATUS_ID=vs.VERSION_STATUS_ID
	LEFT JOIN ap_label vsl ON vs.LABEL_ID=vsl.LABEL_ID
	LEFT JOIN us_user cb ON pv.CREATED_BY=cb.USER_ID
	LEFT JOIN us_user lmb ON pv.LAST_MODIFIED_BY=lmb.USER_ID
	WHERE pv.VERSION_ID=@versionId AND pv.PROGRAM_ID=@programId;
END
