/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cc.altius.FASP.dao.impl;

import cc.altius.FASP.dao.ProgramDataDao;
import cc.altius.FASP.model.DTO.PrgBudgetDTO;
import cc.altius.FASP.model.DTO.PrgConsumptionDTO;
import cc.altius.FASP.model.DTO.PrgInventoryDTO;
import cc.altius.FASP.model.DTO.PrgProgramDataDTO;
import cc.altius.FASP.model.DTO.PrgProgramProductDTO;
import cc.altius.FASP.model.DTO.PrgRegionDTO;
import cc.altius.FASP.model.DTO.PrgShipmentDTO;
import cc.altius.FASP.model.DTO.rowMapper.PrgBudgetDTORowMapper;
import cc.altius.FASP.model.DTO.rowMapper.PrgConsumptionDTORowMapper;
import cc.altius.FASP.model.DTO.rowMapper.PrgInventoryDTORowMapper;
import cc.altius.FASP.model.DTO.rowMapper.PrgProgramDataDTORowMapper;
import cc.altius.FASP.model.DTO.rowMapper.PrgProgramProductDTORowMapper;
import cc.altius.FASP.model.DTO.rowMapper.PrgRegionDTORowMapper;
import cc.altius.FASP.model.DTO.rowMapper.PrgShipmentDTORowMapper;
import java.util.List;
import javax.sql.DataSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

/**
 *
 * @author altius
 */
@Repository
public class ProgramDataDaoImpl implements ProgramDataDao {

    private JdbcTemplate jdbcTemplate;
    private DataSource dataSource;

    @Autowired
    public void setDataSource(DataSource dataSource) {
        this.dataSource = dataSource;
        this.jdbcTemplate = new JdbcTemplate(dataSource);
    }

    @Override
    public PrgProgramDataDTO getProgramData(String programId) {
        String sql = "SELECT \n"
                + "p.`PROGRAM_ID`,1 AS `PROGRAM_VERSION`,p.`AIR_FREIGHT_PERC`,p.`APPROVED_TO_SHIPPED_LEAD_TIME`,p.`DELIVERED_TO_RECEIVED_LEAD_TIME`,\n"
                + "p.`DRAFT_TO_SUBMITTED_LEAD_TIME`,p.`HEALTH_AREA_ID`,ha_label.`LABEL_EN` AS HEALTH_AREA_NAME_EN,\n"
                + "ha_label.`LABEL_FR` AS HEALTH_AREA_NAME_FR,ha_label.`LABEL_PR` AS HEALTH_AREA_NAME_PR,\n"
                + "ha_label.`LABEL_SP` AS HEALTH_AREA_NAME_SP,p_label.`LABEL_EN` AS PROGRAM_NAME_EN,\n"
                + "p_label.`LABEL_PR` AS PROGRAM_NAME_PR,p_label.`LABEL_FR` AS PROGRAM_NAME_FR\n"
                + ",p_label.`LABEL_SP` AS PROGRAM_NAME_SP,p.`LAST_MODIFIED_BY`,lmb_user.`USERNAME` AS LAST_MODIFIED_BY_USERNAME,\n"
                + "p.`LAST_MODIFIED_DATE`,p.`MONTHS_IN_FUTURE_FOR_AMC`,p.`MONTHS_IN_PAST_FOR_AMC`,\n"
                + "p.`ORGANISATION_ID`,ro_label.`LABEL_EN` AS ORGANISATION_NAME_EN,ro_label.`LABEL_PR` AS ORGANISATION_NAME_PR,\n"
                + "ro_label.`LABEL_FR` AS ORGANISATION_NAME_FR,ro_label.`LABEL_SP` AS ORGANISATION_NAME_SP,\n"
                + "p.`PLAN_DRAFT_LEAD_TIME` AS `PLAN_TO_DRAFT_LEAD_TIME`,p.`PROGRAM_MANAGER_USER_ID`\n"
                + ",prg_manager.`USERNAME` AS `PROGRAM_MANAGER_USERNAME`,p.`PROGRAM_NOTES`,p.`REALM_COUNTRY_ID`,\n"
                + "rrc.`AIR_FREIGHT_PERC` AS REALM_COUNTRY_AIR_FREIGHT_PERC,rrc.`ARRIVED_TO_DELIVERED_LEAD_TIME`,rrc.`COUNTRY_ID`,\n"
                + "a_currency.`CONVERSION_RATE_TO_USD`,a_currency.`CURRENCY_CODE`,ac.`CURRENCY_ID`,a_currency.`CURRENCY_SYMBOL`\n"
                + ",a_currency_label.`LABEL_EN` CURRENCY_NAME_EN,a_currency_label.`LABEL_FR` CURRENCY_NAME_FR,\n"
                + "a_currency_label.`LABEL_PR` CURRENCY_NAME_PR,a_currency_label.`LABEL_SP` CURRENCY_NAME_SP,\n"
                + "ac_label.`LABEL_EN` AS COUNTRY_NAME_EN,ac_label.`LABEL_PR` AS COUNTRY_NAME_PR\n"
                + ",ac_label.`LABEL_FR` AS COUNTRY_NAME_FR,ac_label.`LABEL_SP` AS COUNTRY_NAME_SP,\n"
                + "ac.`LANGUAGE_ID`,al.`LANGUAGE_NAME`,rrc.`DEFAULT_CURRENCY_ID`,\n"
                + "default_curreny.`CONVERSION_RATE_TO_USD` AS `DEFAULT_CONVERSION_RATE_TO_USD`,\n"
                + "default_curreny.`CURRENCY_CODE` AS DEFAULT_CURRENCY_CODE,\n"
                + "default_curreny.`CURRENCY_SYMBOL` AS DEFAULT_CURRENCY_SYMBOL\n"
                + ",dc_label.`LABEL_EN` AS DEFAULT_CURRENCY_NAME_EN,dc_label.`LABEL_FR` AS DEFAULT_CURRENCY_NAME_FR\n"
                + ",dc_label.`LABEL_PR` AS DEFAULT_CURRENCY_NAME_PR,dc_label.`LABEL_SP` AS DEFAULT_CURRENCY_NAME_SP,\n"
                + "rrc.`PALLET_UNIT_ID`,pu_label.`LABEL_EN` AS PALLET_UNIT_EN,pu_label.`LABEL_FR` AS PALLET_UNIT_FR,\n"
                + "pu_label.`LABEL_PR` AS PALLET_UNIT_PR,pu_label.`LABEL_SP` AS PALLET_UNIT_SP,\n"
                + "pallet_unit.`UNIT_CODE` AS PALLET_UNIT_CODE,pallet_unit.`UNIT_TYPE_ID` AS PALLET_UNIT_TYPE_ID,\n"
                + "put_label.`LABEL_EN` AS PALLET_UNIT_TYPE_NAME_EN,put_label.`LABEL_FR` AS PALLET_UNIT_TYPE_NAME_FR,\n"
                + "put_label.`LABEL_PR` AS PALLET_UNIT_TYPE_NAME_PR,put_label.`LABEL_SP` AS PALLET_UNIT_TYPE_NAME_SP,\n"
                + "rrc.`REALM_ID`,rr.`DEFAULT` AS DEFAULT_REALM,rr_label.`LABEL_EN` AS REALM_NAME_EN\n"
                + ",rr_label.`LABEL_FR` AS REALM_NAME_FR,rr_label.`LABEL_PR` AS REALM_NAME_PR\n"
                + ",rr_label.`LABEL_SP` AS REALM_NAME_SP,rr.`MONTHS_IN_FUTURE_FOR_AMC` AS MONTHS_IN_FUTURE_FOR_AMC_REALM\n"
                + ",rr.`MONTHS_IN_PAST_FOR_AMC` AS MONTHS_IN_PAST_FOR_AMC_REALM,rr.`ORDER_FREQUENCY`,rr.`REALM_CODE`,\n"
                + "rrc.`SEA_FREIGHT_PERC` AS REALM_COUNTRY_SEA_FREIGHT_PREC,rrc.`SHIPPED_TO_ARRIVED_AIR_LEAD_TIME`,\n"
                + "rrc.`SHIPPED_TO_ARRIVED_SEA_LEAD_TIME`,p.`SEA_FREIGHT_PERC`,p.`SUBMITTED_TO_APPROVED_LEAD_TIME`\n"
                + "FROM rm_program p\n"
                + "LEFT JOIN rm_health_area ha ON ha.`HEALTH_AREA_ID`=p.`HEALTH_AREA_ID`\n"
                + "LEFT JOIN rm_label ha_label ON ha_label.`LABEL_ID`=ha.`LABEL_ID`\n"
                + "LEFT JOIN rm_label p_label ON p_label.`LABEL_ID`=p.`LABEL_ID`\n"
                + "LEFT JOIN us_user lmb_user ON lmb_user.`USER_ID`=p.`LAST_MODIFIED_BY`\n"
                + "LEFT JOIN rm_organisation ro ON ro.`ORGANISATION_ID`=p.`ORGANISATION_ID`\n"
                + "LEFT JOIN rm_label ro_label ON ro_label.`LABEL_ID`=ro.`LABEL_ID`\n"
                + "LEFT JOIN us_user prg_manager ON prg_manager.`USER_ID`=p.`PROGRAM_MANAGER_USER_ID`\n"
                + "LEFT JOIN rm_realm_country rrc ON rrc.`REALM_COUNTRY_ID`=p.`REALM_COUNTRY_ID`\n"
                + "LEFT JOIN ap_country ac ON ac.`COUNTRY_ID`=rrc.`COUNTRY_ID`\n"
                + "LEFT JOIN ap_currency a_currency ON a_currency.`CURRENCY_ID`=ac.`CURRENCY_ID`\n"
                + "LEFT JOIN ap_label a_currency_label ON a_currency_label.`LABEL_ID`=a_currency.`LABEL_ID`\n"
                + "LEFT JOIN ap_label ac_label ON ac_label.`LABEL_ID`=ac.`LABEL_ID`\n"
                + "LEFT JOIN ap_language al ON al.`LANGUAGE_ID`=ac.`LANGUAGE_ID`\n"
                + "LEFT JOIN ap_currency default_curreny ON default_curreny.`CURRENCY_ID`=rrc.`DEFAULT_CURRENCY_ID`\n"
                + "LEFT JOIN ap_label dc_label ON dc_label.`LABEL_ID`=default_curreny.`LABEL_ID`\n"
                + "LEFT JOIN ap_unit pallet_unit ON pallet_unit.`UNIT_ID`=rrc.`PALLET_UNIT_ID`\n"
                + "LEFT JOIN ap_label pu_label ON pu_label.`LABEL_ID`=pallet_unit.`LABEL_ID`\n"
                + "LEFT JOIN ap_unit_type pu_type ON pu_type.`UNIT_TYPE_ID`=pallet_unit.`UNIT_TYPE_ID`\n"
                + "LEFT JOIN ap_label put_label ON put_label.`LABEL_ID`=pu_type.`LABEL_ID`\n"
                + "LEFT JOIN rm_realm rr ON rr.`REALM_ID`=rrc.`REALM_ID`\n"
                + "LEFT JOIN rm_label rr_label ON rr_label.`LABEL_ID`=rr.`LABEL_ID` WHERE p.PROGRAM_ID=?;";
        return this.jdbcTemplate.queryForObject(sql, new PrgProgramDataDTORowMapper(),programId);
    }

    @Override
    public List<PrgProgramProductDTO> getProgramProductListByProgramId(int programId) {
        String sql = "SELECT rpp.`MAX_MONTHS`,rpp.`MIN_MONTHS`,rpp.`PROGRAM_PRODUCT_ID`,rpp.`PRODUCT_ID`,au_label.`LABEL_EN` AS FORECAST_UNIT_NAME_EN\n"
                + ",au_label.`LABEL_FR` AS FORECAST_UNIT_NAME_FR,au_label.`LABEL_PR` AS FORECAST_UNIT_NAME_PR,au_label.`LABEL_SP` AS FORECAST_UNIT_NAME_SP,\n"
                + "au.`UNIT_CODE` AS FORECAST_UNIT_CODE,rp.`FORECASTING_UNIT_ID` AS `FORECAST_UNIT_ID`,aut_label.`LABEL_EN` AS FORECAST_UNIT_TYPE_NAME_EN\n"
                + ",aut_label.`LABEL_FR` AS FORECAST_UNIT_TYPE_NAME_FR,aut_label.`LABEL_PR` AS FORECAST_UNIT_TYPE_NAME_PR\n"
                + ",aut_label.`LABEL_SP` AS FORECAST_UNIT_TYPE_NAME_SP,au.`UNIT_TYPE_ID` AS FORECAST_UNIT_TYPE_ID\n"
                + ",gl.`LABEL_EN` AS GENERIC_LABEL_EN,gl.`LABEL_FR` AS GENERIC_LABEL_FR,gl.`LABEL_PR` AS GENERIC_LABEL_PR,gl.`LABEL_SP` AS GENERIC_LABEL_SP\n"
                + ",rp_label.`LABEL_EN` AS PRODUCT_NAME_EN,rp_label.`LABEL_FR` AS PRODUCT_NAME_FR,rp_label.`LABEL_PR` AS PRODUCT_NAME_PR\n"
                + ",rp_label.`LABEL_SP` AS PRODUCT_NAME_SP,rpp.`PRODUCT_ID`,rp.`PRODUCT_CATEGORY_ID`\n"
                + ",rpc_label.`LABEL_EN` AS `PRODUCT_CATEGORY_NAME_EN`,rpc_label.`LABEL_FR` AS `PRODUCT_CATEGORY_NAME_FR`\n"
                + ",rpc_label.`LABEL_PR` AS `PRODUCT_CATEGORY_NAME_PR`,rpc_label.`LABEL_SP` AS `PRODUCT_CATEGORY_NAME_SP`\n"
                + "FROM rm_program_product rpp\n"
                + "LEFT JOIN rm_product rp ON rp.`PRODUCT_ID`=rpp.`PRODUCT_ID`\n"
                + "LEFT JOIN ap_unit au ON au.`UNIT_ID`=rp.`FORECASTING_UNIT_ID`\n"
                + "LEFT JOIN ap_label au_label ON au_label.`LABEL_ID`=au.`LABEL_ID`\n"
                + "LEFT JOIN ap_unit_type aut ON aut.`UNIT_TYPE_ID`=au.`UNIT_TYPE_ID`\n"
                + "LEFT JOIN ap_label aut_label ON aut_label.`LABEL_ID`=aut.`LABEL_ID`\n"
                + "LEFT JOIN rm_label gl ON gl.`LABEL_ID`=rp.`GENERIC_LABEL_ID`\n"
                + "LEFT JOIN rm_label rp_label ON rp_label.`LABEL_ID`=rp.`LABEL_ID`\n"
                + "LEFT JOIN rm_product_category rpc ON rpc.`PRODUCT_CATEGORY_ID`=rp.`PRODUCT_CATEGORY_ID`\n"
                + "LEFT JOIN rm_label rpc_label ON rpc_label.`LABEL_ID`=rpc.`LABEL_ID`\n"
                + "WHERE rpp.`PROGRAM_ID`=?;";
        return this.jdbcTemplate.query(sql, new PrgProgramProductDTORowMapper(), programId);
    }

    @Override
    public List<PrgInventoryDTO> getInventoryListByProductId(int productId) {
        String sql = "SELECT \n"
                + "i.`INVENTORY_ID`,i.`ACTUAL_QTY`\n"
                + ",i.`ADJUSTMENT_QTY`,i.`BATCH_NO`,i.`DATA_SOURCE_ID`,\n"
                + "adst_label.`LABEL_EN` AS DATA_SOURCE_TYPE_NAME_EN\n"
                + ",adst_label.`LABEL_FR` AS DATA_SOURCE_TYPE_NAME_FR,adst_label.`LABEL_PR` AS DATA_SOURCE_TYPE_NAME_PR\n"
                + ",adst_label.`LABEL_SP` AS DATA_SOURCE_TYPE_NAME_SP,adst.`DATA_SOURCE_TYPE_ID`,ads_label.`LABEL_EN` AS DATA_SOURCE_NAME_EN,\n"
                + "ads_label.`LABEL_FR` AS DATA_SOURCE_NAME_FR,ads_label.`LABEL_PR` AS DATA_SOURCE_NAME_PR\n"
                + ",ads_label.`LABEL_SP` AS DATA_SOURCE_NAME_SP,i.`EXPIRY_DATE`,ilu.`HEIGHT_QTY` AS HEIGHT_QTY,\n"
                + "ilu.`HEIGHT_UNIT_ID`,ihu.`UNIT_ID` AS HEIGHT_UNIT_ID,ihu_label.`LABEL_EN` AS HEIGHT_UNIT_NAME_EN\n"
                + ",ihu_label.`LABEL_FR` AS HEIGHT_UNIT_NAME_FR,ihu_label.`LABEL_PR` AS HEIGHT_UNIT_NAME_PR\n"
                + ",ihu_label.`LABEL_SP` AS HEIGHT_UNIT_NAME_SP,ihu.`UNIT_CODE` AS HEIGHT_UNIT_CODE\n"
                + ",iaut_label.`LABEL_EN` AS HEIGHT_UNIT_TYPE_NAME_EN,iaut_label.`LABEL_FR` AS HEIGHT_UNIT_TYPE_NAME_FR\n"
                + ",iaut_label.`LABEL_PR` AS HEIGHT_UNIT_TYPE_NAME_PR,iaut_label.`LABEL_SP` AS HEIGHT_UNIT_TYPE_NAME_SP,\n"
                + "iaut.`UNIT_TYPE_ID` AS HEIGHT_UNIT_TYPE_ID,ilul.`LABEL_EN` AS LOGISTICS_UNIT_NAME_EN\n"
                + ",ilul.`LABEL_FR` AS LOGISTICS_UNIT_NAME_FR,ilul.`LABEL_PR` AS LOGISTICS_UNIT_NAME_PR\n"
                + ",ilul.`LABEL_SP` AS LOGISTICS_UNIT_NAME_SP,\n"
                + "ilu.`LENGTH_QTY` AS LENGTH_QTY\n"
                + ",i_length_unit_label.`LABEL_EN` AS LENGTH_UNIT_NAME_EN,i_length_unit_label.`LABEL_FR` AS LENGTH_UNIT_NAME_FR\n"
                + ",i_length_unit_label.`LABEL_PR` AS LENGTH_UNIT_NAME_PR,i_length_unit_label.`LABEL_SP` AS LENGTH_UNIT_NAME_SP,\n"
                + "i_length_unit.`UNIT_CODE` AS LENGTH_UNIT_CODE,i_length_unit.`UNIT_ID` AS LENGTH_UNIT_ID\n"
                + ",ilaut_label.`LABEL_EN` AS LENGTH_UNIT_TYPE_NAME_EN,ilaut_label.`LABEL_FR` AS LENGTH_UNIT_TYPE_NAME_FR\n"
                + ",ilaut_label.`LABEL_PR` AS LENGTH_UNIT_TYPE_NAME_PR,ilaut_label.`LABEL_SP` AS LENGTH_UNIT_TYPE_NAME_SP\n"
                + ",ilaut.`UNIT_TYPE_ID` AS LENGTH_UNIT_TYPE_ID,ilu.`LOGISTICS_UNIT_ID` AS LOGISTICS_UNIT_ID\n"
                + ",rmm.`LABEL_EN` AS MANUFACTURER_NAME_EN,rmm.`LABEL_FR` AS MANUFACTURER_NAME_FR\n"
                + ",rmm.`LABEL_PR` AS MANUFACTURER_NAME_PR,rmm.`LABEL_SP` AS MANUFACTURER_NAME_SP,\n"
                + "ilu.`MANUFACTURER_ID` AS `MANUFACTURER_ID`,irpu_label.`LABEL_EN` AS PLANNING_UNIT_NAME_EN\n"
                + ",irpu_label.`LABEL_FR` AS PLANNING_UNIT_NAME_FR,irpu_label.`LABEL_PR` AS PLANNING_UNIT_NAME_PR\n"
                + ",irpu_label.`LABEL_SP` AS PLANNING_UNIT_NAME_SP,irpu.`PLANNING_UNIT_ID` AS `PLANNING_UNIT_ID`,\n"
                + "irpu.`PRICE` AS PRICE,irpu.`QTY_OF_FORECASTING_UNITS` AS `QTY_OF_FORECASTING_UNITS`,\n"
                + "au_pu_label.`LABEL_EN` AS PLANNING_UNIT_UNIT_NAME_EN,au_pu_label.`LABEL_FR` AS PLANNING_UNIT_UNIT_NAME_FR,\n"
                + "au_pu_label.`LABEL_PR` AS PLANNING_UNIT_UNIT_NAME_PR,au_pu_label.`LABEL_SP` AS PLANNING_UNIT_UNIT_NAME_SP,\n"
                + "au_pu.`UNIT_CODE` AS `PLANNING_UNIT_UNIT_CODE`,au_pu.`UNIT_ID` AS `PLANNING_UNIT_UNIT_ID`,\n"
                + "pu_ut_label.`LABEL_EN` AS PLANNING_UNIT_UNIT_TYPE_NAME_EN,pu_ut_label.`LABEL_FR` AS PLANNING_UNIT_UNIT_TYPE_NAME_FR, \n"
                + "pu_ut_label.`LABEL_PR` AS PLANNING_UNIT_UNIT_TYPE_NAME_PR,pu_ut_label.`LABEL_SP` AS PLANNING_UNIT_UNIT_TYPE_NAME_SP,\n"
                + "pu_ut.`UNIT_TYPE_ID` AS PLANNING_UNIT_UNIT_TYPE_ID,ilu.`QTY_IN_EURO1`,ilu.`QTY_IN_EURO2`,ilu.`QTY_OF_PLANNING_UNITS`\n"
                + ",lu_unit_label.`LABEL_EN` AS LOGISTICS_UNIT_UNIT_NAME_EN,lu_unit_label.`LABEL_FR` AS LOGISTICS_UNIT_UNIT_NAME_FR\n"
                + ",lu_unit_label.`LABEL_PR` AS LOGISTICS_UNIT_UNIT_NAME_PR,lu_unit_label.`LABEL_SP` AS LOGISTICS_UNIT_UNIT_NAME_SP,\n"
                + "lu_unit.`UNIT_CODE` AS LOGISTICS_UNIT_UNIT_CODE,lu_unit.`UNIT_ID` AS LOGISTICS_UNIT_UNIT_ID,\n"
                + "lu_ut_label.`LABEL_EN` AS LOGISTICS_UNIT_UNIT_TYPE_NAME_EN,lu_ut_label.`LABEL_FR` AS LOGISTICS_UNIT_UNIT_TYPE_NAME_FR,\n"
                + "lu_ut_label.`LABEL_PR` AS LOGISTICS_UNIT_UNIT_TYPE_NAME_PR,lu_ut_label.`LABEL_SP` AS LOGISTICS_UNIT_UNIT_TYPE_NAME_SP,\n"
                + "lu_ut.`UNIT_TYPE_ID` AS LOGISTICS_UNIT_UNIT_TYPE_ID,ilu.`VARIANT`,ilu.`WEIGHT_QTY`,\n"
                + "\n"
                + "weight_unit_label.`LABEL_EN` AS WEIGHT_UNIT_NAME_EN,weight_unit_label.`LABEL_FR` AS WEIGHT_UNIT_NAME_FR,weight_unit_label.`LABEL_PR` AS WEIGHT_UNIT_NAME_PR,\n"
                + "weight_unit_label.`LABEL_SP` AS WEIGHT_UNIT_NAME_SP,\n"
                + "weight_unit.`UNIT_CODE` AS WEIGHT_UNIT_CODE,weight_unit.`UNIT_ID` AS WEIGHT_UNIT_ID,\n"
                + "weight_unit_type_label.`LABEL_EN` AS WEIGHT_UNIT_TYPE_NAME_EN,weight_unit_type_label.`LABEL_PR` AS WEIGHT_UNIT_TYPE_NAME_PR,\n"
                + "weight_unit_type_label.`LABEL_FR` AS WEIGHT_UNIT_TYPE_NAME_FR,weight_unit_type_label.`LABEL_SP` AS WEIGHT_UNIT_TYPE_NAME_SP,\n"
                + "weight_unit.`UNIT_TYPE_ID` AS WEIGHT_UNIT_TYPE_ID,\n"
                + "\n"
                + "ilu.`WIDTH_QTY`,\n"
                + "\n"
                + "width_unit_label.`LABEL_EN` AS WIDTH_UNIT_NAME_EN,width_unit_label.`LABEL_FR` AS WIDTH_UNIT_NAME_FR,width_unit_label.`LABEL_PR` AS WIDTH_UNIT_NAME_PR,\n"
                + "width_unit_label.`LABEL_SP` AS WIDTH_UNIT_NAME_SP,\n"
                + "width_unit.`UNIT_CODE` AS WIDTH_UNIT_CODE,width_unit.`UNIT_ID` AS WIDTH_UNIT_ID,\n"
                + "width_unit_type_label.`LABEL_EN` AS WIDTH_UNIT_TYPE_NAME_EN,width_unit_type_label.`LABEL_PR` AS WIDTH_UNIT_TYPE_NAME_PR,\n"
                + "width_unit_type_label.`LABEL_FR` AS WIDTH_UNIT_TYPE_NAME_FR,width_unit_type_label.`LABEL_SP` AS WIDTH_UNIT_TYPE_NAME_SP,\n"
                + "width_unit.`UNIT_TYPE_ID` AS WIDTH_UNIT_TYPE_ID,i.`PACK_SIZE`,\n"
                + "\n"
                + "region.`CAPACITY_CBM` AS REGION_CAPACITY_CBM,i.`REGION_ID`,region_label.`LABEL_EN` AS REGION_NAME_EN\n"
                + ",region_label.`LABEL_FR` AS REGION_NAME_FR,region_label.`LABEL_PR` AS REGION_NAME_PR,region_label.`LABEL_SP` AS REGION_NAME_SP,\n"
                + "\n"
                + "inventory_unit_label.`LABEL_EN` AS UNIT_NAME_EN,inventory_unit_label.`LABEL_FR` AS UNIT_NAME_FR,inventory_unit_label.`LABEL_PR` AS UNIT_NAME_PR,\n"
                + "inventory_unit_label.`LABEL_SP` AS UNIT_NAME_SP,\n"
                + "inventory_unit.`UNIT_CODE` AS UNIT_CODE,inventory_unit.`UNIT_ID` AS UNIT_ID,\n"
                + "inventory_unit_type_label.`LABEL_EN` AS UNIT_TYPE_NAME_EN,inventory_unit_type_label.`LABEL_PR` AS UNIT_TYPE_NAME_PR,\n"
                + "inventory_unit_type_label.`LABEL_FR` AS UNIT_TYPE_NAME_FR,inventory_unit_type_label.`LABEL_SP` AS UNIT_TYPE_NAME_SP,\n"
                + "inventory_unit.`UNIT_TYPE_ID` AS UNIT_TYPE_ID\n"
                + "\n"
                + "FROM rm_inventory i\n"
                + "LEFT JOIN ap_data_source ads ON ads.`DATA_SOURCE_ID`=i.`DATA_SOURCE_ID`\n"
                + "LEFT JOIN ap_data_source_type adst ON adst.`DATA_SOURCE_TYPE_ID`=ads.`DATA_SOURCE_TYPE_ID`\n"
                + "LEFT JOIN ap_label adst_label ON adst_label.`LABEL_ID`=adst.`LABEL_ID`\n"
                + "LEFT JOIN ap_label ads_label ON ads_label.`LABEL_ID`=ads.`LABEL_ID`\n"
                + "LEFT JOIN rm_logistics_unit ilu ON ilu.`LOGISTICS_UNIT_ID`=i.`LOGISTICS_UNIT_ID`\n"
                + "LEFT JOIN ap_unit ihu ON ihu.`UNIT_ID`=ilu.`UNIT_ID`\n"
                + "LEFT JOIN ap_label ihu_label ON ihu_label.`LABEL_ID`=ihu.`LABEL_ID`\n"
                + "LEFT JOIN ap_unit_type iaut ON iaut.`UNIT_TYPE_ID`=ihu.`UNIT_TYPE_ID`\n"
                + "LEFT JOIN ap_label iaut_label ON iaut_label.`LABEL_ID`=iaut.`LABEL_ID`\n"
                + "LEFT JOIN rm_label ilul ON ilul.`LABEL_ID`=ilu.`LABEL_ID`\n"
                + "LEFT JOIN ap_unit i_length_unit ON i_length_unit.`UNIT_ID`=ilu.`LENGTH_UNIT_ID`\n"
                + "LEFT JOIN ap_label i_length_unit_label ON i_length_unit_label.`LABEL_ID`=i_length_unit.`LABEL_ID`\n"
                + "LEFT JOIN ap_unit_type ilaut ON ilaut.`UNIT_TYPE_ID`=i_length_unit.`UNIT_TYPE_ID`\n"
                + "LEFT JOIN ap_label ilaut_label ON ilaut_label.`LABEL_ID`=ilaut.`LABEL_ID`\n"
                + "LEFT JOIN rm_manufacturer rm ON rm.`MANUFACTURER_ID`=ilu.`MANUFACTURER_ID`\n"
                + "LEFT JOIN rm_label rmm ON rmm.`LABEL_ID`=rm.`LABEL_ID`\n"
                + "LEFT JOIN rm_planning_unit irpu ON irpu.`PLANNING_UNIT_ID`=ilu.`PLANNING_UNIT_ID`\n"
                + "LEFT JOIN rm_label irpu_label ON irpu_label.`LABEL_ID`=irpu.`LABEL_ID`\n"
                + "LEFT JOIN ap_unit au_pu ON au_pu.`UNIT_ID`=irpu.`UNIT_ID`\n"
                + "LEFT JOIN ap_label au_pu_label ON au_pu_label.`LABEL_ID`=au_pu.`LABEL_ID`\n"
                + "LEFT JOIN ap_unit_type pu_ut ON pu_ut.`UNIT_TYPE_ID`=au_pu.`UNIT_TYPE_ID`\n"
                + "LEFT JOIN ap_label pu_ut_label ON pu_ut_label.`LABEL_ID`=pu_ut.`LABEL_ID`\n"
                + "LEFT JOIN ap_unit lu_unit ON lu_unit.`UNIT_ID`=ilu.`UNIT_ID`\n"
                + "LEFT JOIN ap_label lu_unit_label ON lu_unit_label.`LABEL_ID`=lu_unit.`LABEL_ID`\n"
                + "LEFT JOIN ap_unit_type lu_ut ON lu_ut.`UNIT_TYPE_ID`=lu_unit.`UNIT_TYPE_ID`\n"
                + "LEFT JOIN ap_label lu_ut_label ON lu_ut_label.`LABEL_ID`=lu_ut.`LABEL_ID`\n"
                + "\n"
                + "LEFT JOIN ap_unit weight_unit ON weight_unit.`UNIT_ID`=ilu.`WEIGHT_UNIT_ID`\n"
                + "LEFT JOIN ap_label weight_unit_label ON weight_unit_label.`LABEL_ID`=weight_unit.`LABEL_ID`\n"
                + "LEFT JOIN ap_unit_type weight_unit_type ON weight_unit_type.`UNIT_TYPE_ID`=weight_unit.`UNIT_TYPE_ID`\n"
                + "LEFT JOIN ap_label weight_unit_type_label ON weight_unit_type_label.`LABEL_ID`=weight_unit_type.`LABEL_ID`\n"
                + "\n"
                + "LEFT JOIN ap_unit width_unit ON width_unit.`UNIT_ID`=ilu.`WIDTH_UNIT_ID`\n"
                + "LEFT JOIN ap_label width_unit_label ON width_unit_label.`LABEL_ID`=width_unit.`LABEL_ID`\n"
                + "LEFT JOIN ap_unit_type width_unit_type ON width_unit_type.`UNIT_TYPE_ID`=width_unit.`UNIT_TYPE_ID`\n"
                + "LEFT JOIN ap_label width_unit_type_label ON width_unit_type_label.`LABEL_ID`=width_unit_type.`LABEL_ID`\n"
                + "\n"
                + "LEFT JOIN rm_region region ON region.`REGION_ID`=i.`REGION_ID`\n"
                + "LEFT JOIN rm_label region_label ON region_label.`LABEL_ID`=region.`LABEL_ID`\n"
                + "\n"
                + "LEFT JOIN ap_unit inventory_unit ON inventory_unit.`UNIT_ID`=ilu.`UNIT_ID`\n"
                + "LEFT JOIN ap_label inventory_unit_label ON inventory_unit_label.`LABEL_ID`=inventory_unit.`LABEL_ID`\n"
                + "LEFT JOIN ap_unit_type inventory_unit_type ON inventory_unit_type.`UNIT_TYPE_ID`=inventory_unit.`UNIT_TYPE_ID`\n"
                + "LEFT JOIN ap_label inventory_unit_type_label ON inventory_unit_type_label.`LABEL_ID`=inventory_unit_type.`LABEL_ID`\n"
                + "WHERE irpu.`PRODUCT_ID`=?";
        return this.jdbcTemplate.query(sql, new PrgInventoryDTORowMapper(), productId);
    }

    @Override
    public List<PrgConsumptionDTO> getConsumptionListByProductId(int productId) {
        String sql = "SELECT i.`CONSUMPTION_ID`,i.`CONSUMPTION_QTY`,i.`DATA_SOURCE_ID`,adst.`DATA_SOURCE_TYPE_ID`,\n"
                + "                adst_label.`LABEL_EN` AS DATA_SOURCE_TYPE_NAME_EN\n"
                + "                ,adst_label.`LABEL_FR` AS DATA_SOURCE_TYPE_NAME_FR,adst_label.`LABEL_PR` AS DATA_SOURCE_TYPE_NAME_PR\n"
                + "                ,adst_label.`LABEL_SP` AS DATA_SOURCE_TYPE_NAME_SP,ads_label.`LABEL_EN` AS DATA_SOURCE_NAME_EN,\n"
                + "                ads_label.`LABEL_FR` AS DATA_SOURCE_NAME_FR,ads_label.`LABEL_PR` AS DATA_SOURCE_NAME_PR\n"
                + "                ,ads_label.`LABEL_SP` AS DATA_SOURCE_NAME_SP,i.`DAYS_OF_STOCK_OUT`,ilu.`HEIGHT_QTY` AS HEIGHT_QTY,\n"
                + "                ilu.`HEIGHT_UNIT_ID`,ihu.`UNIT_ID` AS HEIGHT_UNIT_ID,ihu_label.`LABEL_EN` AS HEIGHT_UNIT_NAME_EN\n"
                + "                ,ihu_label.`LABEL_FR` AS HEIGHT_UNIT_NAME_FR,ihu_label.`LABEL_PR` AS HEIGHT_UNIT_NAME_PR\n"
                + "                ,ihu_label.`LABEL_SP` AS HEIGHT_UNIT_NAME_SP,ihu.`UNIT_CODE` AS HEIGHT_UNIT_CODE\n"
                + "                ,iaut_label.`LABEL_EN` AS HEIGHT_UNIT_TYPE_NAME_EN,iaut_label.`LABEL_FR` AS HEIGHT_UNIT_TYPE_NAME_FR\n"
                + "                ,iaut_label.`LABEL_PR` AS HEIGHT_UNIT_TYPE_NAME_PR,iaut_label.`LABEL_SP` AS HEIGHT_UNIT_TYPE_NAME_SP,\n"
                + "                iaut.`UNIT_TYPE_ID` AS HEIGHT_UNIT_TYPE_ID,ilul.`LABEL_EN` AS LOGISTICS_UNIT_NAME_EN\n"
                + "                ,ilul.`LABEL_FR` AS LOGISTICS_UNIT_NAME_FR,ilul.`LABEL_PR` AS LOGISTICS_UNIT_NAME_PR\n"
                + "                ,ilul.`LABEL_SP` AS LOGISTICS_UNIT_NAME_SP,\n"
                + "                ilu.`LENGTH_QTY` AS LENGTH_QTY\n"
                + "                ,i_length_unit_label.`LABEL_EN` AS LENGTH_UNIT_NAME_EN,i_length_unit_label.`LABEL_FR` AS LENGTH_UNIT_NAME_FR\n"
                + "                ,i_length_unit_label.`LABEL_PR` AS LENGTH_UNIT_NAME_PR,i_length_unit_label.`LABEL_SP` AS LENGTH_UNIT_NAME_SP,\n"
                + "                i_length_unit.`UNIT_CODE` AS LENGTH_UNIT_CODE,i_length_unit.`UNIT_ID` AS LENGTH_UNIT_ID\n"
                + "                ,ilaut_label.`LABEL_EN` AS LENGTH_UNIT_TYPE_NAME_EN,ilaut_label.`LABEL_FR` AS LENGTH_UNIT_TYPE_NAME_FR\n"
                + "                ,ilaut_label.`LABEL_PR` AS LENGTH_UNIT_TYPE_NAME_PR,ilaut_label.`LABEL_SP` AS LENGTH_UNIT_TYPE_NAME_SP\n"
                + "                ,ilaut.`UNIT_TYPE_ID` AS LENGTH_UNIT_TYPE_ID,ilu.`LOGISTICS_UNIT_ID` AS LOGISTICS_UNIT_ID\n"
                + "                ,rmm.`LABEL_EN` AS MANUFACTURER_NAME_EN,rmm.`LABEL_FR` AS MANUFACTURER_NAME_FR\n"
                + "                ,rmm.`LABEL_PR` AS MANUFACTURER_NAME_PR,rmm.`LABEL_SP` AS MANUFACTURER_NAME_SP,\n"
                + "                ilu.`MANUFACTURER_ID` AS `MANUFACTURER_ID`,irpu_label.`LABEL_EN` AS PLANNING_UNIT_NAME_EN\n"
                + "                ,irpu_label.`LABEL_FR` AS PLANNING_UNIT_NAME_FR,irpu_label.`LABEL_PR` AS PLANNING_UNIT_NAME_PR\n"
                + "                ,irpu_label.`LABEL_SP` AS PLANNING_UNIT_NAME_SP,irpu.`PLANNING_UNIT_ID` AS `PLANNING_UNIT_ID`,\n"
                + "                irpu.`PRICE` AS PRICE,irpu.`QTY_OF_FORECASTING_UNITS` AS `QTY_OF_FORECASTING_UNITS`,\n"
                + "                au_pu_label.`LABEL_EN` AS PLANNING_UNIT_UNIT_NAME_EN,au_pu_label.`LABEL_FR` AS PLANNING_UNIT_UNIT_NAME_FR,\n"
                + "                au_pu_label.`LABEL_PR` AS PLANNING_UNIT_UNIT_NAME_PR,au_pu_label.`LABEL_SP` AS PLANNING_UNIT_UNIT_NAME_SP,\n"
                + "                au_pu.`UNIT_CODE` AS `PLANNING_UNIT_UNIT_CODE`,au_pu.`UNIT_ID` AS `PLANNING_UNIT_UNIT_ID`,\n"
                + "                pu_ut_label.`LABEL_EN` AS PLANNING_UNIT_UNIT_TYPE_NAME_EN,pu_ut_label.`LABEL_FR` AS PLANNING_UNIT_UNIT_TYPE_NAME_FR, \n"
                + "                pu_ut_label.`LABEL_PR` AS PLANNING_UNIT_UNIT_TYPE_NAME_PR,pu_ut_label.`LABEL_SP` AS PLANNING_UNIT_UNIT_TYPE_NAME_SP,\n"
                + "                pu_ut.`UNIT_TYPE_ID` AS PLANNING_UNIT_UNIT_TYPE_ID,ilu.`QTY_IN_EURO1`,ilu.`QTY_IN_EURO2`,ilu.`QTY_OF_PLANNING_UNITS`\n"
                + "                ,lu_unit_label.`LABEL_EN` AS LOGISTICS_UNIT_UNIT_NAME_EN,lu_unit_label.`LABEL_FR` AS LOGISTICS_UNIT_UNIT_NAME_FR\n"
                + "                ,lu_unit_label.`LABEL_PR` AS LOGISTICS_UNIT_UNIT_NAME_PR,lu_unit_label.`LABEL_SP` AS LOGISTICS_UNIT_UNIT_NAME_SP,\n"
                + "                lu_unit.`UNIT_CODE` AS LOGISTICS_UNIT_UNIT_CODE,lu_unit.`UNIT_ID` AS LOGISTICS_UNIT_UNIT_ID,\n"
                + "                lu_ut_label.`LABEL_EN` AS LOGISTICS_UNIT_UNIT_TYPE_NAME_EN,lu_ut_label.`LABEL_FR` AS LOGISTICS_UNIT_UNIT_TYPE_NAME_FR,\n"
                + "                lu_ut_label.`LABEL_PR` AS LOGISTICS_UNIT_UNIT_TYPE_NAME_PR,lu_ut_label.`LABEL_SP` AS LOGISTICS_UNIT_UNIT_TYPE_NAME_SP,\n"
                + "                lu_ut.`UNIT_TYPE_ID` AS LOGISTICS_UNIT_UNIT_TYPE_ID,ilu.`VARIANT`,ilu.`WEIGHT_QTY`,\n"
                + "                \n"
                + "                weight_unit_label.`LABEL_EN` AS WEIGHT_UNIT_NAME_EN,weight_unit_label.`LABEL_FR` AS WEIGHT_UNIT_NAME_FR,weight_unit_label.`LABEL_PR` AS WEIGHT_UNIT_NAME_PR,\n"
                + "                weight_unit_label.`LABEL_SP` AS WEIGHT_UNIT_NAME_SP,\n"
                + "                weight_unit.`UNIT_CODE` AS WEIGHT_UNIT_CODE,weight_unit.`UNIT_ID` AS WEIGHT_UNIT_ID,\n"
                + "                weight_unit_type_label.`LABEL_EN` AS WEIGHT_UNIT_TYPE_NAME_EN,weight_unit_type_label.`LABEL_PR` AS WEIGHT_UNIT_TYPE_NAME_PR,\n"
                + "                weight_unit_type_label.`LABEL_FR` AS WEIGHT_UNIT_TYPE_NAME_FR,weight_unit_type_label.`LABEL_SP` AS WEIGHT_UNIT_TYPE_NAME_SP,\n"
                + "                weight_unit.`UNIT_TYPE_ID` AS WEIGHT_UNIT_TYPE_ID,\n"
                + "                \n"
                + "                ilu.`WIDTH_QTY`,\n"
                + "                \n"
                + "                width_unit_label.`LABEL_EN` AS WIDTH_UNIT_NAME_EN,width_unit_label.`LABEL_FR` AS WIDTH_UNIT_NAME_FR,width_unit_label.`LABEL_PR` AS WIDTH_UNIT_NAME_PR,\n"
                + "                width_unit_label.`LABEL_SP` AS WIDTH_UNIT_NAME_SP,\n"
                + "                width_unit.`UNIT_CODE` AS WIDTH_UNIT_CODE,width_unit.`UNIT_ID` AS WIDTH_UNIT_ID,\n"
                + "                width_unit_type_label.`LABEL_EN` AS WIDTH_UNIT_TYPE_NAME_EN,width_unit_type_label.`LABEL_PR` AS WIDTH_UNIT_TYPE_NAME_PR,\n"
                + "                width_unit_type_label.`LABEL_FR` AS WIDTH_UNIT_TYPE_NAME_FR,width_unit_type_label.`LABEL_SP` AS WIDTH_UNIT_TYPE_NAME_SP,\n"
                + "                width_unit.`UNIT_TYPE_ID` AS WIDTH_UNIT_TYPE_ID,i.`PACK_SIZE`,i.`START_DATE`,i.`STOP_DATE`,\n"
                + "               region.`CAPACITY_CBM` AS REGION_CAPACITY_CBM,i.`REGION_ID`,region_label.`LABEL_EN` AS REGION_NAME_EN\n"
                + "                ,region_label.`LABEL_FR` AS REGION_NAME_FR,region_label.`LABEL_PR` AS REGION_NAME_PR,region_label.`LABEL_SP` AS REGION_NAME_SP,\n"
                + "                \n"
                + "                consumption_unit_label.`LABEL_EN` AS UNIT_NAME_EN,consumption_unit_label.`LABEL_FR` AS UNIT_NAME_FR,consumption_unit_label.`LABEL_PR` AS UNIT_NAME_PR,\n"
                + "                consumption_unit_label.`LABEL_SP` AS UNIT_NAME_SP,\n"
                + "                consumption_unit.`UNIT_CODE` AS UNIT_CODE,consumption_unit.`UNIT_ID` AS UNIT_ID,\n"
                + "                consumption_unit_type_label.`LABEL_EN` AS UNIT_TYPE_NAME_EN,consumption_unit_type_label.`LABEL_PR` AS UNIT_TYPE_NAME_PR,\n"
                + "                consumption_unit_type_label.`LABEL_FR` AS UNIT_TYPE_NAME_FR,consumption_unit_type_label.`LABEL_SP` AS UNIT_TYPE_NAME_SP,\n"
                + "                consumption_unit.`UNIT_TYPE_ID` AS UNIT_TYPE_ID\n"
                + "FROM rm_consumption i                \n"
                + "LEFT JOIN ap_data_source ads ON ads.`DATA_SOURCE_ID`=i.`DATA_SOURCE_ID`\n"
                + "                LEFT JOIN ap_data_source_type adst ON adst.`DATA_SOURCE_TYPE_ID`=ads.`DATA_SOURCE_TYPE_ID`\n"
                + "                LEFT JOIN ap_label adst_label ON adst_label.`LABEL_ID`=adst.`LABEL_ID`\n"
                + "                LEFT JOIN ap_label ads_label ON ads_label.`LABEL_ID`=ads.`LABEL_ID`\n"
                + "LEFT JOIN rm_logistics_unit ilu ON ilu.`LOGISTICS_UNIT_ID`=i.`LOGISTICS_UNIT_ID`\n"
                + "                LEFT JOIN ap_unit ihu ON ihu.`UNIT_ID`=ilu.`UNIT_ID`\n"
                + "                LEFT JOIN ap_label ihu_label ON ihu_label.`LABEL_ID`=ihu.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit_type iaut ON iaut.`UNIT_TYPE_ID`=ihu.`UNIT_TYPE_ID`\n"
                + "                LEFT JOIN ap_label iaut_label ON iaut_label.`LABEL_ID`=iaut.`LABEL_ID`\n"
                + "                LEFT JOIN rm_label ilul ON ilul.`LABEL_ID`=ilu.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit i_length_unit ON i_length_unit.`UNIT_ID`=ilu.`LENGTH_UNIT_ID`\n"
                + "                LEFT JOIN ap_label i_length_unit_label ON i_length_unit_label.`LABEL_ID`=i_length_unit.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit_type ilaut ON ilaut.`UNIT_TYPE_ID`=i_length_unit.`UNIT_TYPE_ID`\n"
                + "                LEFT JOIN ap_label ilaut_label ON ilaut_label.`LABEL_ID`=ilaut.`LABEL_ID`\n"
                + "                LEFT JOIN rm_manufacturer rm ON rm.`MANUFACTURER_ID`=ilu.`MANUFACTURER_ID`\n"
                + "                LEFT JOIN rm_label rmm ON rmm.`LABEL_ID`=rm.`LABEL_ID`\n"
                + "                LEFT JOIN rm_planning_unit irpu ON irpu.`PLANNING_UNIT_ID`=ilu.`PLANNING_UNIT_ID`\n"
                + "                LEFT JOIN rm_label irpu_label ON irpu_label.`LABEL_ID`=irpu.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit au_pu ON au_pu.`UNIT_ID`=irpu.`UNIT_ID`\n"
                + "                LEFT JOIN ap_label au_pu_label ON au_pu_label.`LABEL_ID`=au_pu.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit_type pu_ut ON pu_ut.`UNIT_TYPE_ID`=au_pu.`UNIT_TYPE_ID`\n"
                + "                LEFT JOIN ap_label pu_ut_label ON pu_ut_label.`LABEL_ID`=pu_ut.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit lu_unit ON lu_unit.`UNIT_ID`=ilu.`UNIT_ID`\n"
                + "                LEFT JOIN ap_label lu_unit_label ON lu_unit_label.`LABEL_ID`=lu_unit.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit_type lu_ut ON lu_ut.`UNIT_TYPE_ID`=lu_unit.`UNIT_TYPE_ID`\n"
                + "                LEFT JOIN ap_label lu_ut_label ON lu_ut_label.`LABEL_ID`=lu_ut.`LABEL_ID`\n"
                + "                \n"
                + "                LEFT JOIN ap_unit weight_unit ON weight_unit.`UNIT_ID`=ilu.`WEIGHT_UNIT_ID`\n"
                + "                LEFT JOIN ap_label weight_unit_label ON weight_unit_label.`LABEL_ID`=weight_unit.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit_type weight_unit_type ON weight_unit_type.`UNIT_TYPE_ID`=weight_unit.`UNIT_TYPE_ID`\n"
                + "                LEFT JOIN ap_label weight_unit_type_label ON weight_unit_type_label.`LABEL_ID`=weight_unit_type.`LABEL_ID`\n"
                + "                \n"
                + "                LEFT JOIN ap_unit width_unit ON width_unit.`UNIT_ID`=ilu.`WIDTH_UNIT_ID`\n"
                + "                LEFT JOIN ap_label width_unit_label ON width_unit_label.`LABEL_ID`=width_unit.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit_type width_unit_type ON width_unit_type.`UNIT_TYPE_ID`=width_unit.`UNIT_TYPE_ID`\n"
                + "                LEFT JOIN ap_label width_unit_type_label ON width_unit_type_label.`LABEL_ID`=width_unit_type.`LABEL_ID`\n"
                + "                \n"
                + "                LEFT JOIN rm_region region ON region.`REGION_ID`=i.`REGION_ID`\n"
                + "                LEFT JOIN rm_label region_label ON region_label.`LABEL_ID`=region.`LABEL_ID`\n"
                + "                \n"
                + "                LEFT JOIN ap_unit consumption_unit ON consumption_unit.`UNIT_ID`=ilu.`UNIT_ID`\n"
                + "                LEFT JOIN ap_label consumption_unit_label ON consumption_unit_label.`LABEL_ID`=consumption_unit.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit_type consumption_unit_type ON consumption_unit_type.`UNIT_TYPE_ID`=consumption_unit.`UNIT_TYPE_ID`\n"
                + "                LEFT JOIN ap_label consumption_unit_type_label ON consumption_unit_type_label.`LABEL_ID`=consumption_unit_type.`LABEL_ID`\n"
                + "WHERE irpu.`PRODUCT_ID`=?";
        return this.jdbcTemplate.query(sql, new PrgConsumptionDTORowMapper(), productId);
    }

    @Override
    public List<PrgShipmentDTO> getShipmentListByProductId(int productId) {
        String sql = "SELECT i.`FREIGHT_PRICE`,i.`SHIPMENT_ID`,i.`ARRIVE_DATE`,i.`DATA_SOURCE_ID`,adst.`DATA_SOURCE_TYPE_ID`,\n"
                + "                adst_label.`LABEL_EN` AS DATA_SOURCE_TYPE_NAME_EN\n"
                + "                ,adst_label.`LABEL_FR` AS DATA_SOURCE_TYPE_NAME_FR,adst_label.`LABEL_PR` AS DATA_SOURCE_TYPE_NAME_PR\n"
                + "                ,adst_label.`LABEL_SP` AS DATA_SOURCE_TYPE_NAME_SP,ads_label.`LABEL_EN` AS DATA_SOURCE_NAME_EN,\n"
                + "                ads_label.`LABEL_FR` AS DATA_SOURCE_NAME_FR,ads_label.`LABEL_PR` AS DATA_SOURCE_NAME_PR\n"
                + "                ,ads_label.`LABEL_SP` AS DATA_SOURCE_NAME_SP,i.`FREIGHT_PRICE`,ilu.`HEIGHT_QTY` AS HEIGHT_QTY,\n"
                + "                ilu.`HEIGHT_UNIT_ID`,ihu.`UNIT_ID` AS HEIGHT_UNIT_ID,ihu_label.`LABEL_EN` AS HEIGHT_UNIT_NAME_EN\n"
                + "                ,ihu_label.`LABEL_FR` AS HEIGHT_UNIT_NAME_FR,ihu_label.`LABEL_PR` AS HEIGHT_UNIT_NAME_PR\n"
                + "                ,ihu_label.`LABEL_SP` AS HEIGHT_UNIT_NAME_SP,ihu.`UNIT_CODE` AS HEIGHT_UNIT_CODE\n"
                + "                ,iaut_label.`LABEL_EN` AS HEIGHT_UNIT_TYPE_NAME_EN,iaut_label.`LABEL_FR` AS HEIGHT_UNIT_TYPE_NAME_FR\n"
                + "                ,iaut_label.`LABEL_PR` AS HEIGHT_UNIT_TYPE_NAME_PR,iaut_label.`LABEL_SP` AS HEIGHT_UNIT_TYPE_NAME_SP,\n"
                + "                iaut.`UNIT_TYPE_ID` AS HEIGHT_UNIT_TYPE_ID,ilul.`LABEL_EN` AS LOGISTICS_UNIT_NAME_EN\n"
                + "                ,ilul.`LABEL_FR` AS LOGISTICS_UNIT_NAME_FR,ilul.`LABEL_PR` AS LOGISTICS_UNIT_NAME_PR\n"
                + "                ,ilul.`LABEL_SP` AS LOGISTICS_UNIT_NAME_SP,\n"
                + "                ilu.`LENGTH_QTY` AS LENGTH_QTY\n"
                + "                ,i_length_unit_label.`LABEL_EN` AS LENGTH_UNIT_NAME_EN,i_length_unit_label.`LABEL_FR` AS LENGTH_UNIT_NAME_FR\n"
                + "                ,i_length_unit_label.`LABEL_PR` AS LENGTH_UNIT_NAME_PR,i_length_unit_label.`LABEL_SP` AS LENGTH_UNIT_NAME_SP,\n"
                + "                i_length_unit.`UNIT_CODE` AS LENGTH_UNIT_CODE,i_length_unit.`UNIT_ID` AS LENGTH_UNIT_ID\n"
                + "                ,ilaut_label.`LABEL_EN` AS LENGTH_UNIT_TYPE_NAME_EN,ilaut_label.`LABEL_FR` AS LENGTH_UNIT_TYPE_NAME_FR\n"
                + "                ,ilaut_label.`LABEL_PR` AS LENGTH_UNIT_TYPE_NAME_PR,ilaut_label.`LABEL_SP` AS LENGTH_UNIT_TYPE_NAME_SP\n"
                + "                ,ilaut.`UNIT_TYPE_ID` AS LENGTH_UNIT_TYPE_ID,ilu.`LOGISTICS_UNIT_ID` AS LOGISTICS_UNIT_ID\n"
                + "                ,rmm.`LABEL_EN` AS MANUFACTURER_NAME_EN,rmm.`LABEL_FR` AS MANUFACTURER_NAME_FR\n"
                + "                ,rmm.`LABEL_PR` AS MANUFACTURER_NAME_PR,rmm.`LABEL_SP` AS MANUFACTURER_NAME_SP,\n"
                + "                ilu.`MANUFACTURER_ID` AS `MANUFACTURER_ID`,irpu_label.`LABEL_EN` AS PLANNING_UNIT_NAME_EN\n"
                + "                ,irpu_label.`LABEL_FR` AS PLANNING_UNIT_NAME_FR,irpu_label.`LABEL_PR` AS PLANNING_UNIT_NAME_PR\n"
                + "                ,irpu_label.`LABEL_SP` AS PLANNING_UNIT_NAME_SP,irpu.`PLANNING_UNIT_ID` AS `PLANNING_UNIT_ID`,\n"
                + "                irpu.`PRICE` AS PRICE,irpu.`QTY_OF_FORECASTING_UNITS` AS `QTY_OF_FORECASTING_UNITS`,\n"
                + "                au_pu_label.`LABEL_EN` AS PLANNING_UNIT_UNIT_NAME_EN,au_pu_label.`LABEL_FR` AS PLANNING_UNIT_UNIT_NAME_FR,\n"
                + "                au_pu_label.`LABEL_PR` AS PLANNING_UNIT_UNIT_NAME_PR,au_pu_label.`LABEL_SP` AS PLANNING_UNIT_UNIT_NAME_SP,\n"
                + "                au_pu.`UNIT_CODE` AS `PLANNING_UNIT_UNIT_CODE`,au_pu.`UNIT_ID` AS `PLANNING_UNIT_UNIT_ID`,\n"
                + "                pu_ut_label.`LABEL_EN` AS PLANNING_UNIT_UNIT_TYPE_NAME_EN,pu_ut_label.`LABEL_FR` AS PLANNING_UNIT_UNIT_TYPE_NAME_FR, \n"
                + "                pu_ut_label.`LABEL_PR` AS PLANNING_UNIT_UNIT_TYPE_NAME_PR,pu_ut_label.`LABEL_SP` AS PLANNING_UNIT_UNIT_TYPE_NAME_SP,\n"
                + "                pu_ut.`UNIT_TYPE_ID` AS PLANNING_UNIT_UNIT_TYPE_ID,ilu.`QTY_IN_EURO1`,ilu.`QTY_IN_EURO2`,ilu.`QTY_OF_PLANNING_UNITS`\n"
                + "                ,lu_unit_label.`LABEL_EN` AS LOGISTICS_UNIT_UNIT_NAME_EN,lu_unit_label.`LABEL_FR` AS LOGISTICS_UNIT_UNIT_NAME_FR\n"
                + "                ,lu_unit_label.`LABEL_PR` AS LOGISTICS_UNIT_UNIT_NAME_PR,lu_unit_label.`LABEL_SP` AS LOGISTICS_UNIT_UNIT_NAME_SP,\n"
                + "                lu_unit.`UNIT_CODE` AS LOGISTICS_UNIT_UNIT_CODE,lu_unit.`UNIT_ID` AS LOGISTICS_UNIT_UNIT_ID,\n"
                + "                lu_ut_label.`LABEL_EN` AS LOGISTICS_UNIT_UNIT_TYPE_NAME_EN,lu_ut_label.`LABEL_FR` AS LOGISTICS_UNIT_UNIT_TYPE_NAME_FR,\n"
                + "                lu_ut_label.`LABEL_PR` AS LOGISTICS_UNIT_UNIT_TYPE_NAME_PR,lu_ut_label.`LABEL_SP` AS LOGISTICS_UNIT_UNIT_TYPE_NAME_SP,\n"
                + "                lu_ut.`UNIT_TYPE_ID` AS LOGISTICS_UNIT_UNIT_TYPE_ID,ilu.`VARIANT`,ilu.`WEIGHT_QTY`,\n"
                + "                \n"
                + "                weight_unit_label.`LABEL_EN` AS WEIGHT_UNIT_NAME_EN,weight_unit_label.`LABEL_FR` AS WEIGHT_UNIT_NAME_FR,weight_unit_label.`LABEL_PR` AS WEIGHT_UNIT_NAME_PR,\n"
                + "                weight_unit_label.`LABEL_SP` AS WEIGHT_UNIT_NAME_SP,\n"
                + "                weight_unit.`UNIT_CODE` AS WEIGHT_UNIT_CODE,weight_unit.`UNIT_ID` AS WEIGHT_UNIT_ID,\n"
                + "                weight_unit_type_label.`LABEL_EN` AS WEIGHT_UNIT_TYPE_NAME_EN,weight_unit_type_label.`LABEL_PR` AS WEIGHT_UNIT_TYPE_NAME_PR,\n"
                + "                weight_unit_type_label.`LABEL_FR` AS WEIGHT_UNIT_TYPE_NAME_FR,weight_unit_type_label.`LABEL_SP` AS WEIGHT_UNIT_TYPE_NAME_SP,\n"
                + "                weight_unit.`UNIT_TYPE_ID` AS WEIGHT_UNIT_TYPE_ID,\n"
                + "                \n"
                + "                ilu.`WIDTH_QTY`,\n"
                + "                \n"
                + "                width_unit_label.`LABEL_EN` AS WIDTH_UNIT_NAME_EN,width_unit_label.`LABEL_FR` AS WIDTH_UNIT_NAME_FR,width_unit_label.`LABEL_PR` AS WIDTH_UNIT_NAME_PR,\n"
                + "                width_unit_label.`LABEL_SP` AS WIDTH_UNIT_NAME_SP,\n"
                + "                width_unit.`UNIT_CODE` AS WIDTH_UNIT_CODE,width_unit.`UNIT_ID` AS WIDTH_UNIT_ID,\n"
                + "                width_unit_type_label.`LABEL_EN` AS WIDTH_UNIT_TYPE_NAME_EN,width_unit_type_label.`LABEL_PR` AS WIDTH_UNIT_TYPE_NAME_PR,\n"
                + "                width_unit_type_label.`LABEL_FR` AS WIDTH_UNIT_TYPE_NAME_FR,width_unit_type_label.`LABEL_SP` AS WIDTH_UNIT_TYPE_NAME_SP,\n"
                + "                width_unit.`UNIT_TYPE_ID` AS WIDTH_UNIT_TYPE_ID,\n"
                + "                \n"
                + "                i.`NOTES`,i.`ORDER_DATE`,i.`PO_RO_NUMBER`,rpa_label.`LABEL_EN` AS PROCURMENT_AGENT_NAME_EN\n"
                + "                ,rpa_label.`LABEL_FR` AS PROCURMENT_AGENT_NAME_FR,rpa_label.`LABEL_PR` AS PROCURMENT_AGENT_NAME_PR\n"
                + "                ,rpa_label.`LABEL_SP` AS PROCURMENT_AGENT_NAME_SP,i.`PROCUREMENT_AGENT_ID`,rpa.`SUBMITTED_TO_APPROVED_LEAD_TIME`,\n"
                + "pa_lu.`APPROVED_TO_SHIPPED_LEAD_TIME` AS `APPROVED_TO_SHIP_LEAD_TIME`,pa_lu.`PRICE`,pa_lu.`PROCUREMENT_AGENT_SKU_ID`,pa_lu.`SKU_CODE`,i.`QTY`,\n"
                + "i.`RECEIVE_DATE`,\n"
                + "\n"
                + "region.`CAPACITY_CBM` AS REGION_CAPACITY_CBM,i.`REGION_ID`,region_label.`LABEL_EN` AS REGION_NAME_EN\n"
                + "                ,region_label.`LABEL_FR` AS REGION_NAME_FR,region_label.`LABEL_PR` AS REGION_NAME_PR,region_label.`LABEL_SP` AS REGION_NAME_SP,\n"
                + "                               \n"
                + "               i.`SHIP_DATE`,ship_bud.`BUDGET_AMT` AS `BUD_AMOUNT`,ship_bud.`BUDGET_ID` AS `BUD_BUDGET_ID`\n"
                + "               ,ship_bud_label.`LABEL_EN` AS BUD_NAME_EN,ship_bud_label.`LABEL_FR` AS BUD_NAME_FR\n"
                + "               ,ship_bud_label.`LABEL_PR` AS BUD_NAME_PR,ship_bud_label.`LABEL_SP` AS BUD_NAME_SP,ship_bud.`START_DATE` AS BUD_START_DATE\n"
                + "               ,ship_bud.`STOP_DATE` AS BUD_STOP_DATE,\n"
                + "               rsb.`BUDGET_AMT` AS BUDGET_AMOUNT,rsb.`BUDGET_ID`,rsb.`SUB_FUNDING_SOURCE_ID`,\n"
                + "budget_rsfs.`FUNDING_SOURCE_ID` AS BUDGET_FUNDING_SOURCE_ID,budget_fs_label.`LABEL_EN` AS BUDGET_FUNDING_SOURCE_NAME_EN               \n"
                + "               ,budget_fs_label.`LABEL_FR` AS BUDGET_FUNDING_SOURCE_NAME_FR,budget_fs_label.`LABEL_PR` AS BUDGET_FUNDING_SOURCE_NAME_PR\n"
                + "               ,budget_fs_label.`LABEL_SP` AS BUDGET_FUNDING_SOURCE_NAME_SP,budget_rsfs_label.`LABEL_EN` AS BUDGET_SUB_FUNDING_SOURCE_NAME_EN\n"
                + "               ,budget_rsfs_label.`LABEL_PR` AS BUDGET_SUB_FUNDING_SOURCE_NAME_PR,budget_rsfs_label.`LABEL_FR` AS BUDGET_SUB_FUNDING_SOURCE_NAME_FR\n"
                + "               ,budget_rsfs_label.`LABEL_SP` AS BUDGET_SUB_FUNDING_SOURCE_NAME_SP,budget_rsfs.`SUB_FUNDING_SOURCE_ID` AS `BUDGET_SUB_FUNDING_SOURCE_ID`,\n"
                + "               i.`SHIPMENT_PRICE`,i.`SUGGESTED_QTY`,i.`SHIPMENT_STATUS_ID` ,ass_label.`LABEL_EN` AS SHIPMENT_STATUS_NAME_EN\n"
                + "              ,ass_label.`LABEL_FR` AS SHIPMENT_STATUS_NAME_FR,ass_label.`LABEL_PR` AS SHIPMENT_STATUS_NAME_PR\n"
                + "              ,ass_label.`LABEL_SP` AS SHIPMENT_STATUS_NAME_SP\n"
                + "               \n"
                + "FROM rm_shipment i                \n"
                + "LEFT JOIN ap_data_source ads ON ads.`DATA_SOURCE_ID`=i.`DATA_SOURCE_ID`\n"
                + "                LEFT JOIN ap_data_source_type adst ON adst.`DATA_SOURCE_TYPE_ID`=ads.`DATA_SOURCE_TYPE_ID`\n"
                + "                LEFT JOIN ap_label adst_label ON adst_label.`LABEL_ID`=adst.`LABEL_ID`\n"
                + "                LEFT JOIN ap_label ads_label ON ads_label.`LABEL_ID`=ads.`LABEL_ID`\n"
                + "                LEFT JOIN rm_logistics_unit ilu ON ilu.`LOGISTICS_UNIT_ID`=i.`LOGISTICS_UNIT_ID`\n"
                + "                LEFT JOIN ap_unit ihu ON ihu.`UNIT_ID`=ilu.`UNIT_ID`\n"
                + "                LEFT JOIN ap_label ihu_label ON ihu_label.`LABEL_ID`=ihu.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit_type iaut ON iaut.`UNIT_TYPE_ID`=ihu.`UNIT_TYPE_ID`\n"
                + "                LEFT JOIN ap_label iaut_label ON iaut_label.`LABEL_ID`=iaut.`LABEL_ID`\n"
                + "                LEFT JOIN rm_label ilul ON ilul.`LABEL_ID`=ilu.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit i_length_unit ON i_length_unit.`UNIT_ID`=ilu.`LENGTH_UNIT_ID`\n"
                + "                LEFT JOIN ap_label i_length_unit_label ON i_length_unit_label.`LABEL_ID`=i_length_unit.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit_type ilaut ON ilaut.`UNIT_TYPE_ID`=i_length_unit.`UNIT_TYPE_ID`\n"
                + "                LEFT JOIN ap_label ilaut_label ON ilaut_label.`LABEL_ID`=ilaut.`LABEL_ID`\n"
                + "                LEFT JOIN rm_manufacturer rm ON rm.`MANUFACTURER_ID`=ilu.`MANUFACTURER_ID`\n"
                + "                LEFT JOIN rm_label rmm ON rmm.`LABEL_ID`=rm.`LABEL_ID`\n"
                + "                LEFT JOIN rm_planning_unit irpu ON irpu.`PLANNING_UNIT_ID`=ilu.`PLANNING_UNIT_ID`\n"
                + "                LEFT JOIN rm_label irpu_label ON irpu_label.`LABEL_ID`=irpu.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit au_pu ON au_pu.`UNIT_ID`=irpu.`UNIT_ID`\n"
                + "                LEFT JOIN ap_label au_pu_label ON au_pu_label.`LABEL_ID`=au_pu.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit_type pu_ut ON pu_ut.`UNIT_TYPE_ID`=au_pu.`UNIT_TYPE_ID`\n"
                + "                LEFT JOIN ap_label pu_ut_label ON pu_ut_label.`LABEL_ID`=pu_ut.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit lu_unit ON lu_unit.`UNIT_ID`=ilu.`UNIT_ID`\n"
                + "                LEFT JOIN ap_label lu_unit_label ON lu_unit_label.`LABEL_ID`=lu_unit.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit_type lu_ut ON lu_ut.`UNIT_TYPE_ID`=lu_unit.`UNIT_TYPE_ID`\n"
                + "                LEFT JOIN ap_label lu_ut_label ON lu_ut_label.`LABEL_ID`=lu_ut.`LABEL_ID`\n"
                + "                \n"
                + "                LEFT JOIN ap_unit weight_unit ON weight_unit.`UNIT_ID`=ilu.`WEIGHT_UNIT_ID`\n"
                + "                LEFT JOIN ap_label weight_unit_label ON weight_unit_label.`LABEL_ID`=weight_unit.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit_type weight_unit_type ON weight_unit_type.`UNIT_TYPE_ID`=weight_unit.`UNIT_TYPE_ID`\n"
                + "                LEFT JOIN ap_label weight_unit_type_label ON weight_unit_type_label.`LABEL_ID`=weight_unit_type.`LABEL_ID`\n"
                + "                \n"
                + "                LEFT JOIN ap_unit width_unit ON width_unit.`UNIT_ID`=ilu.`WIDTH_UNIT_ID`\n"
                + "                LEFT JOIN ap_label width_unit_label ON width_unit_label.`LABEL_ID`=width_unit.`LABEL_ID`\n"
                + "                LEFT JOIN ap_unit_type width_unit_type ON width_unit_type.`UNIT_TYPE_ID`=width_unit.`UNIT_TYPE_ID`\n"
                + "                LEFT JOIN ap_label width_unit_type_label ON width_unit_type_label.`LABEL_ID`=width_unit_type.`LABEL_ID`\n"
                + "                LEFT JOIN rm_procurement_agent rpa ON rpa.`PROCUREMENT_AGENT_ID`=i.`PROCUREMENT_AGENT_ID`\n"
                + "                LEFT JOIN rm_label rpa_label ON rpa_label.`LABEL_ID`=rpa.`LABEL_ID`\n"
                + "                LEFT JOIN rm_procurement_agent_logistics_unit pa_lu ON pa_lu.`PROCUREMENT_AGENT_ID`=rpa.`PROCUREMENT_AGENT_ID`\n"
                + "                \n"
                + "                LEFT JOIN rm_region region ON region.`REGION_ID`=i.`REGION_ID`\n"
                + "                LEFT JOIN rm_label region_label ON region_label.`LABEL_ID`=region.`LABEL_ID`\n"
                + "                \n"
                + "                LEFT JOIN rm_shipment_budget rsb ON rsb.`SHIPMENT_ID`=i.`SHIPMENT_ID`\n"
                + "		LEFT JOIN rm_budget ship_bud ON ship_bud.`BUDGET_ID`=rsb.`BUDGET_ID`\n"
                + "		LEFT JOIN rm_label ship_bud_label ON ship_bud_label.`LABEL_ID`=ship_bud.`LABEL_ID`\n"
                + "		\n"
                + "		LEFT JOIN rm_sub_funding_source budget_rsfs ON budget_rsfs.`SUB_FUNDING_SOURCE_ID`=rsb.`FUNDING_SOURCE_ID`\n"
                + "		LEFT JOIN rm_funding_source budget_fs ON budget_fs.`FUNDING_SOURCE_ID`=budget_rsfs.`FUNDING_SOURCE_ID`\n"
                + "		LEFT JOIN rm_label budget_fs_label ON budget_fs_label.`LABEL_ID`=budget_fs.`LABEL_ID`\n"
                + "		LEFT JOIN rm_label budget_rsfs_label ON budget_rsfs_label.`LABEL_ID`=budget_rsfs.`LABEL_ID`	\n"
                + "		LEFT JOIN ap_shipment_status ass ON ass.`SHIPMENT_STATUS_ID`=i.`SHIPMENT_STATUS_ID`\n"
                + "		LEFT JOIN ap_label ass_label ON ass_label.`LABEL_ID`=ass.`LABEL_ID`\n"
                + " WHERE irpu.`PRODUCT_ID`=?";
        return this.jdbcTemplate.query(sql, new PrgShipmentDTORowMapper(), productId);
    }

    @Override
    public List<PrgRegionDTO> getRegionListByProgramId(int programId) {
        String sql = "SELECT rpr.`REGION_ID`,r.`CAPACITY_CBM`,rm_label.`LABEL_EN` AS REGION_NAME_EN,r.`ACTIVE`\n"
                + ",rm_label.`LABEL_FR` AS REGION_NAME_FR,rm_label.`LABEL_PR` AS REGION_NAME_PR,rm_label.`LABEL_SP` AS REGION_NAME_SP\n"
                + "FROM rm_program_region rpr\n"
                + "LEFT JOIN rm_region r ON r.`REGION_ID`=rpr.`REGION_ID`\n"
                + "LEFT JOIN rm_label ON rm_label.`LABEL_ID`=r.`LABEL_ID` \n"
                + "WHERE rpr.`PROGRAM_ID`=?;";
        return this.jdbcTemplate.query(sql, new PrgRegionDTORowMapper(), programId);
    }

    @Override
    public List<PrgBudgetDTO> getBudgetListByProgramId(int programId) {
        String sql = "SELECT b.`BUDGET_AMT` AS `BUDGET_AMOUNT`,b.`BUDGET_ID`,ap_label.`LABEL_EN` AS BUDGET_NAME_EN,ap_label.`LABEL_FR` AS BUDGET_NAME_FR,\n"
                + "ap_label.`LABEL_PR` AS BUDGET_NAME_PR,ap_label.`LABEL_SP` AS BUDGET_NAME_SP,b.`START_DATE` AS BUDGET_START_DATE,\n"
                + "b.`STOP_DATE` AS  BUDGET_STOP_DATE,rsfs.`FUNDING_SOURCE_ID`,rfs_label.`LABEL_EN` AS FUNDING_SOURCE_NAME_EN\n"
                + ",rfs_label.`LABEL_FR` AS FUNDING_SOURCE_NAME_FR,rfs_label.`LABEL_PR` AS FUNDING_SOURCE_NAME_PR\n"
                + ",rfs_label.`LABEL_SP` AS FUNDING_SOURCE_NAME_SP,rsfs.`SUB_FUNDING_SOURCE_ID`,\n"
                + "rsfs_label.`LABEL_EN` AS SUB_FUNDING_SOURCE_NAME_EN\n"
                + ",rsfs_label.`LABEL_FR` AS SUB_FUNDING_SOURCE_NAME_FR,rsfs_label.`LABEL_PR` AS SUB_FUNDING_SOURCE_NAME_PR,\n"
                + "rsfs_label.`LABEL_SP` AS SUB_FUNDING_SOURCE_NAME_SP\n"
                + "FROM rm_budget b \n"
                + "LEFT JOIN ap_label ON ap_label.`LABEL_ID`=b.`LABEL_ID`\n"
                + "LEFT JOIN rm_sub_funding_source rsfs ON rsfs.`SUB_FUNDING_SOURCE_ID`=b.`SUB_FUNDING_SOURCE_ID`\n"
                + "LEFT JOIN rm_funding_source rfs ON rfs.`FUNDING_SOURCE_ID`=rsfs.`FUNDING_SOURCE_ID`\n"
                + "LEFT JOIN rm_label rfs_label ON rfs_label.`LABEL_ID`=rfs.`LABEL_ID`\n"
                + "LEFT JOIN rm_label rsfs_label ON rsfs.`LABEL_ID`=rsfs_label.`LABEL_ID`\n"
                + "WHERE b.`PROGRAM_ID`=?;";
        return this.jdbcTemplate.query(sql, new PrgBudgetDTORowMapper(), programId);
    }

}
