/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cc.altius.FASP.model;

import cc.altius.FASP.framework.JsonDateDeserializer;
import cc.altius.FASP.framework.JsonDateSerializer;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * @author akil
 */
public class SimpleBatchQuantity implements Serializable {

    @JsonView({Views.ArtmisView.class, Views.InternalView.class})
    private int batchId;
    @JsonView({Views.ArtmisView.class, Views.InternalView.class})
    private String batchNo;
    @JsonDeserialize(using = JsonDateDeserializer.class)
    @JsonSerialize(using = JsonDateSerializer.class)
    @JsonView({Views.ArtmisView.class, Views.InternalView.class})
    private Date expiryDate;
    @JsonView({Views.ArtmisView.class, Views.InternalView.class})
    private boolean autoGenerated;
    @JsonView({Views.ArtmisView.class, Views.InternalView.class})
    private long qty;
    @JsonView({Views.ArtmisView.class, Views.InternalView.class})
    private long qtyWps;
    @JsonView({Views.ArtmisView.class, Views.InternalView.class})
    private long expiredQty;
    @JsonView({Views.ArtmisView.class, Views.InternalView.class})
    private long expiredQtyWps;
    @JsonDeserialize(using = JsonDateDeserializer.class)
    @JsonSerialize(using = JsonDateSerializer.class)
    @JsonView({Views.ArtmisView.class, Views.InternalView.class})
    private Date createdDate;

    public SimpleBatchQuantity() {
    }

    public SimpleBatchQuantity(int batchId, String batchNo, Date expiryDate, boolean autoGenerated, long qty, long qtyWps, long expiredQty, long expiredQtyWps, Date createdDate) {
        this.batchId = batchId;
        this.batchNo = batchNo;
        this.expiryDate = expiryDate;
        this.autoGenerated = autoGenerated;
        this.qty = qty;
        this.qtyWps = qtyWps;
        this.expiredQty = expiredQty;
        this.expiredQtyWps = expiredQtyWps;
        this.createdDate = createdDate;
    }

    public int getBatchId() {
        return batchId;
    }

    public void setBatchId(int batchId) {
        this.batchId = batchId;
    }

    public String getBatchNo() {
        return batchNo;
    }

    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    public Date getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public long getQty() {
        return qty;
    }

    public void setQty(long qty) {
        this.qty = qty;
    }

    public long getQtyWps() {
        return qtyWps;
    }

    public void setQtyWps(long qtyWps) {
        this.qtyWps = qtyWps;
    }

    public long getExpiredQty() {
        return expiredQty;
    }

    public void setExpiredQty(long expiredQty) {
        this.expiredQty = expiredQty;
    }

    public long getExpiredQtyWps() {
        return expiredQtyWps;
    }

    public void setExpiredQtyWps(long expiredQtyWps) {
        this.expiredQtyWps = expiredQtyWps;
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

}
