/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cc.altius.FASP.model;

import cc.altius.FASP.framework.JsonDateDeserializer;
import cc.altius.FASP.framework.JsonDateSerializer;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * @author akil
 */
public class SimpleBatchQuantity implements Serializable {

    private int batchId;
    private String batchNo;
    @JsonDeserialize(using = JsonDateDeserializer.class)
    @JsonSerialize(using = JsonDateSerializer.class)
    private Date expiryDate;
    private boolean autoGenerated;
    private int qty;
    private int qtyWps;
    private int expiredQty;
    private int expiredQtyWps;
    @JsonDeserialize(using = JsonDateDeserializer.class)
    @JsonSerialize(using = JsonDateSerializer.class)
    private Date createdDate;

    public SimpleBatchQuantity() {
    }

    public SimpleBatchQuantity(int batchId, String batchNo, Date expiryDate, boolean autoGenerated, int qty, int qtyWps, int expiredQty, int expiredQtyWps, Date createdDate) {
        this.batchId = batchId;
        this.batchNo = batchNo;
        this.expiryDate = expiryDate;
        this.autoGenerated = autoGenerated;
        this.qty = qty;
        this.qtyWps = qtyWps;
        this.expiredQty = expiredQty;
        this.expiredQtyWps = expiredQtyWps;
        this.createdDate = createdDate;
    }

    public int getBatchId() {
        return batchId;
    }

    public void setBatchId(int batchId) {
        this.batchId = batchId;
    }

    public String getBatchNo() {
        return batchNo;
    }

    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    public Date getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public int getQty() {
        return qty;
    }

    public void setQty(int qty) {
        this.qty = qty;
    }

    public int getQtyWps() {
        return qtyWps;
    }

    public void setQtyWps(int qtyWps) {
        this.qtyWps = qtyWps;
    }

    public int getExpiredQty() {
        return expiredQty;
    }

    public void setExpiredQty(int expiredQty) {
        this.expiredQty = expiredQty;
    }

    public int getExpiredQtyWps() {
        return expiredQtyWps;
    }

    public void setExpiredQtyWps(int expiredQtyWps) {
        this.expiredQtyWps = expiredQtyWps;
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

}
