/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  altius
 * Created: 08-Mar-2021
 */

DROP TABLE IF EXISTS `fasp`.`tr_artmis_country`;
CREATE TABLE `fasp`.`tr_artmis_country` (
  `RECEPIENT_NAME` VARCHAR(200) NOT NULL,
  `REALM_COUNTRY_ID` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`RECEPIENT_NAME`));
INSERT INTO tr_artmis_country VALUES ('Angola', '3');
INSERT INTO tr_artmis_country VALUES ('Australia', '1');
INSERT INTO tr_artmis_country VALUES ('Bangladesh', '52');
INSERT INTO tr_artmis_country VALUES ('Barbados', '4');
INSERT INTO tr_artmis_country VALUES ('Benin', '5');
INSERT INTO tr_artmis_country VALUES ('Botswana', '6');
INSERT INTO tr_artmis_country VALUES ('Burkina Faso', '7');
INSERT INTO tr_artmis_country VALUES ('Burundi', '8');
INSERT INTO tr_artmis_country VALUES ('Cambodia', '9');
INSERT INTO tr_artmis_country VALUES ('Cameroon', '10');
INSERT INTO tr_artmis_country VALUES ('Congo DRC', '11');
INSERT INTO tr_artmis_country VALUES ('Côte dIvoire', '12');
INSERT INTO tr_artmis_country VALUES ('Dominican Republic', '13');
INSERT INTO tr_artmis_country VALUES ('El Salvador', '14');
INSERT INTO tr_artmis_country VALUES ('Eswatini', '15');
INSERT INTO tr_artmis_country VALUES ('Ethiopia', '16');
INSERT INTO tr_artmis_country VALUES ('France', '2');
INSERT INTO tr_artmis_country VALUES ('Ghana', '17');
INSERT INTO tr_artmis_country VALUES ('Guatemala', '18');
INSERT INTO tr_artmis_country VALUES ('Guinea', '19');
INSERT INTO tr_artmis_country VALUES ('Haiti', '20');
INSERT INTO tr_artmis_country VALUES ('Honduras', '21');
INSERT INTO tr_artmis_country VALUES ('Indonesia', '22');
INSERT INTO tr_artmis_country VALUES ('Kenya', '24');
INSERT INTO tr_artmis_country VALUES ('Laos', '25');
INSERT INTO tr_artmis_country VALUES ('Lesotho', '26');
INSERT INTO tr_artmis_country VALUES ('Liberia', '27');
INSERT INTO tr_artmis_country VALUES ('Madagascar', '28');
INSERT INTO tr_artmis_country VALUES ('Malawi', '29');
INSERT INTO tr_artmis_country VALUES ('Mali', '30');
INSERT INTO tr_artmis_country VALUES ('Mozambique', '31');
INSERT INTO tr_artmis_country VALUES ('Myanmar', '32');
INSERT INTO tr_artmis_country VALUES ('Namibia', '33');
INSERT INTO tr_artmis_country VALUES ('Nepal', '34');
INSERT INTO tr_artmis_country VALUES ('Niger', '35');
INSERT INTO tr_artmis_country VALUES ('Nigeria', '36');
INSERT INTO tr_artmis_country VALUES ('Pakistan', '37');
INSERT INTO tr_artmis_country VALUES ('Panama', '38');
INSERT INTO tr_artmis_country VALUES ('Rwanda', '39');
INSERT INTO tr_artmis_country VALUES ('Senegal', '40');
INSERT INTO tr_artmis_country VALUES ('Sierra Leone', '41');
INSERT INTO tr_artmis_country VALUES ('South Africa', '42');
INSERT INTO tr_artmis_country VALUES ('Tanzania', '44');
INSERT INTO tr_artmis_country VALUES ('Thailand', '45');
INSERT INTO tr_artmis_country VALUES ('Togo', '46');
INSERT INTO tr_artmis_country VALUES ('Uganda', '47');
INSERT INTO tr_artmis_country VALUES ('Ukraine', '48');
INSERT INTO tr_artmis_country VALUES ('Vietnam', '49');
INSERT INTO tr_artmis_country VALUES ('Zambia', '50');
INSERT INTO tr_artmis_country VALUES ('Zimbabwe', '51');



INSERT INTO `fasp`.`ap_export`(`EXPORT_ID`,`ERP_CODE`,`JOB_NAME`,`LAST_DATE`) VALUES ( NULL,'ARTMIS','QAT_Shipment_Linking',NOW()); 
UPDATE `fasp`.`em_email_template` SET `SUBJECT`='QAT data export error : <%ERROR_NAME%>' WHERE `EMAIL_TEMPLATE_ID`='4'; 


 

DELIMITER $$

USE `fasp`$$

DROP PROCEDURE IF EXISTS `getShipmentListForManualLinking`$$

CREATE DEFINER=`faspUser`@`%` PROCEDURE `getShipmentListForManualLinking`(PROGRAM_ID INT(10), PLANNING_UNIT_ID TEXT, VERSION_ID INT (10))
BEGIN
    SET @programId = PROGRAM_ID;
    SET @planningUnitIds = PLANNING_UNIT_ID;
    SET @procurementAgentId = 1;
    SET @versionId = VERSION_ID;
    IF @versionId = -1 THEN
        SELECT MAX(pv.VERSION_ID) INTO @versionId FROM rm_program_version pv WHERE pv.PROGRAM_ID=@programId;
    END IF;
   
SELECT
        st.SHIPMENT_ID, st.SHIPMENT_TRANS_ID, st.SHIPMENT_QTY, st.EXPECTED_DELIVERY_DATE, st.PRODUCT_COST, st.SKU_CODE,
        st.PROCUREMENT_AGENT_ID, st.PROCUREMENT_AGENT_CODE, st.`COLOR_HTML_CODE`, st.`PROCUREMENT_AGENT_LABEL_ID`, st.`PROCUREMENT_AGENT_LABEL_EN`, st.`PROCUREMENT_AGENT_LABEL_FR`, st.`PROCUREMENT_AGENT_LABEL_SP`, st.`PROCUREMENT_AGENT_LABEL_PR`,
        st.FUNDING_SOURCE_ID, st.FUNDING_SOURCE_CODE, st.`FUNDING_SOURCE_LABEL_ID`, st.`FUNDING_SOURCE_LABEL_EN`, st.`FUNDING_SOURCE_LABEL_FR`, st.`FUNDING_SOURCE_LABEL_SP`, st.`FUNDING_SOURCE_LABEL_PR`,
        st.BUDGET_ID, st.BUDGET_CODE, st.`BUDGET_LABEL_ID`, st.`BUDGET_LABEL_EN`, st.`BUDGET_LABEL_FR`, st.`BUDGET_LABEL_SP`, st.`BUDGET_LABEL_PR`,
        st.SHIPMENT_STATUS_ID, st.`SHIPMENT_STATUS_LABEL_ID`, st.`SHIPMENT_STATUS_LABEL_EN`, st.`SHIPMENT_STATUS_LABEL_FR`, st.`SHIPMENT_STATUS_LABEL_SP`, st.`SHIPMENT_STATUS_LABEL_PR`,
        st.PLANNING_UNIT_ID, st.`PLANNING_UNIT_LABEL_ID`, st.`PLANNING_UNIT_LABEL_EN`, st.`PLANNING_UNIT_LABEL_FR`, st.`PLANNING_UNIT_LABEL_SP`, st.`PLANNING_UNIT_LABEL_PR`,
        st.ORDER_NO, st.PRIME_LINE_NO,st.`NOTES`
FROM (
        SELECT
            s.SHIPMENT_ID, st.RECEIVED_DATE, st.EXPECTED_DELIVERY_DATE,st.SHIPMENT_QTY, st.RATE, st.PRODUCT_COST, st.FREIGHT_COST, st.ACCOUNT_FLAG, st.SHIPMENT_TRANS_ID, papu.SKU_CODE,
            pa.`PROCUREMENT_AGENT_ID`, pa.`PROCUREMENT_AGENT_CODE`, pa.`COLOR_HTML_CODE`, pa.`LABEL_ID` `PROCUREMENT_AGENT_LABEL_ID`, pa.`LABEL_EN` `PROCUREMENT_AGENT_LABEL_EN`, pa.LABEL_FR `PROCUREMENT_AGENT_LABEL_FR`, pa.LABEL_SP `PROCUREMENT_AGENT_LABEL_SP`, pa.LABEL_PR `PROCUREMENT_AGENT_LABEL_PR`,
            fs.`FUNDING_SOURCE_ID`, fs.`FUNDING_SOURCE_CODE`, fs.LABEL_ID `FUNDING_SOURCE_LABEL_ID`, fs.LABEL_EN `FUNDING_SOURCE_LABEL_EN`, fs.LABEL_FR `FUNDING_SOURCE_LABEL_FR`, fs.LABEL_SP `FUNDING_SOURCE_LABEL_SP`, fs.LABEL_PR `FUNDING_SOURCE_LABEL_PR`,
            shs.SHIPMENT_STATUS_ID, shs.LABEL_ID `SHIPMENT_STATUS_LABEL_ID`, shs.LABEL_EN `SHIPMENT_STATUS_LABEL_EN`, shs.LABEL_FR `SHIPMENT_STATUS_LABEL_FR`, shs.LABEL_SP `SHIPMENT_STATUS_LABEL_SP`, shs.LABEL_PR `SHIPMENT_STATUS_LABEL_PR`,
            sc.CURRENCY_ID `SHIPMENT_CURRENCY_ID`, sc.`CURRENCY_CODE` `SHIPMENT_CURRENCY_CODE`, s.CONVERSION_RATE_TO_USD `SHIPMENT_CONVERSION_RATE_TO_USD`,
            sc.LABEL_ID `SHIPMENT_CURRENCY_LABEL_ID`, sc.LABEL_EN `SHIPMENT_CURRENCY_LABEL_EN`, sc.LABEL_FR `SHIPMENT_CURRENCY_LABEL_FR`, sc.LABEL_SP `SHIPMENT_CURRENCY_LABEL_SP`, sc.LABEL_PR `SHIPMENT_CURRENCY_LABEL_PR`,
            st.ACTIVE, st.`ORDER_NO`, st.`PRIME_LINE_NO`,
            b.BUDGET_ID, b.BUDGET_CODE, b.LABEL_ID `BUDGET_LABEL_ID`, b.LABEL_EN `BUDGET_LABEL_EN`, b.LABEL_FR `BUDGET_LABEL_FR`, b.LABEL_SP `BUDGET_LABEL_SP`, b.LABEL_PR `BUDGET_LABEL_PR`,
            st.PLANNING_UNIT_ID, pu.LABEL_ID `PLANNING_UNIT_LABEL_ID`, pu.LABEL_EN `PLANNING_UNIT_LABEL_EN`, pu.LABEL_FR `PLANNING_UNIT_LABEL_FR`, pu.LABEL_SP `PLANNING_UNIT_LABEL_SP`, pu.LABEL_PR `PLANNING_UNIT_LABEL_PR`,st.`NOTES`
FROM (
    SELECT st.SHIPMENT_ID, MAX(st.VERSION_ID) MAX_VERSION_ID FROM rm_shipment s LEFT JOIN rm_shipment_trans st ON s.SHIPMENT_ID=st.SHIPMENT_ID WHERE (@versiONId=-1 OR st.VERSION_ID<=@versiONId) AND s.PROGRAM_ID=@programId GROUP BY st.SHIPMENT_ID
) ts
    LEFT JOIN rm_shipment s ON ts.SHIPMENT_ID=s.SHIPMENT_ID
    LEFT JOIN rm_shipment_trans st ON ts.SHIPMENT_ID=st.SHIPMENT_ID AND ts.MAX_VERSION_ID=st.VERSION_ID
    LEFT JOIN vw_planning_unit pu ON st.PLANNING_UNIT_ID=pu.PLANNING_UNIT_ID
    LEFT JOIN vw_procurement_agent pa ON st.PROCUREMENT_AGENT_ID=pa.PROCUREMENT_AGENT_ID
    LEFT JOIN vw_funding_source fs ON st.FUNDING_SOURCE_ID=fs.FUNDING_SOURCE_ID
    LEFT JOIN vw_shipment_status shs ON st.SHIPMENT_STATUS_ID=shs.SHIPMENT_STATUS_ID
    LEFT JOIN vw_currency sc ON s.CURRENCY_ID=sc.CURRENCY_ID
    LEFT JOIN vw_budget b ON st.BUDGET_ID=b.BUDGET_ID
    LEFT JOIN rm_manual_tagging mt ON mt.SHIPMENT_ID=ts.SHIPMENT_ID AND mt.ACTIVE
    LEFT JOIN rm_procurement_agent_planning_unit papu ON papu.PROCUREMENT_AGENT_ID=pa.PROCUREMENT_AGENT_ID AND papu.PLANNING_UNIT_ID=st.PLANNING_UNIT_ID
    WHERE st.ERP_FLAG=0 AND st.ACTIVE AND st.SHIPMENT_STATUS_ID IN (3,4,5,6,9) AND (LENGTH(@planningUnitIds)=0 OR FIND_IN_SET(st.PLANNING_UNIT_ID,@planningUnitIds))   AND (mt.SHIPMENT_ID IS NULL OR mt.ACTIVE=0) AND st.PROCUREMENT_AGENT_ID=@procurementAgentId
) st
ORDER BY COALESCE(st.RECEIVED_DATE, st.EXPECTED_DELIVERY_DATE) DESC;
END$$
DELIMITER ;

DELIMITER $$

USE `fasp`$$

DROP PROCEDURE IF EXISTS `getShipmentListForAlreadyLinkedShipments`$$

CREATE DEFINER=`faspUser`@`%` PROCEDURE `getShipmentListForAlreadyLinkedShipments`(PROGRAM_ID INT(10), PLANNING_UNIT_ID TEXT, VERSION_ID INT (10))
BEGIN
    SET @programId = PROGRAM_ID;
    SET @planningUnitIds = PLANNING_UNIT_ID;
    SET @procurementAgentId = 1;
    SET @versionId = VERSION_ID;
    IF @versionId = -1 THEN
        SELECT MAX(pv.VERSION_ID) INTO @versionId FROM rm_program_version pv WHERE pv.PROGRAM_ID=@programId;
    END IF;
   
SELECT
        st.SHIPMENT_ID, st.SHIPMENT_TRANS_ID, st.SHIPMENT_QTY, st.EXPECTED_DELIVERY_DATE, st.PRODUCT_COST, st.SKU_CODE,
        st.PROCUREMENT_AGENT_ID, st.PROCUREMENT_AGENT_CODE, st.`COLOR_HTML_CODE`, st.`PROCUREMENT_AGENT_LABEL_ID`, st.`PROCUREMENT_AGENT_LABEL_EN`, st.`PROCUREMENT_AGENT_LABEL_FR`, st.`PROCUREMENT_AGENT_LABEL_SP`, st.`PROCUREMENT_AGENT_LABEL_PR`,
        st.FUNDING_SOURCE_ID, st.FUNDING_SOURCE_CODE, st.`FUNDING_SOURCE_LABEL_ID`, st.`FUNDING_SOURCE_LABEL_EN`, st.`FUNDING_SOURCE_LABEL_FR`, st.`FUNDING_SOURCE_LABEL_SP`, st.`FUNDING_SOURCE_LABEL_PR`,
        st.BUDGET_ID, st.BUDGET_CODE, st.`BUDGET_LABEL_ID`, st.`BUDGET_LABEL_EN`, st.`BUDGET_LABEL_FR`, st.`BUDGET_LABEL_SP`, st.`BUDGET_LABEL_PR`,
        st.SHIPMENT_STATUS_ID, st.`SHIPMENT_STATUS_LABEL_ID`, st.`SHIPMENT_STATUS_LABEL_EN`, st.`SHIPMENT_STATUS_LABEL_FR`, st.`SHIPMENT_STATUS_LABEL_SP`, st.`SHIPMENT_STATUS_LABEL_PR`,
        st.PLANNING_UNIT_ID, st.`PLANNING_UNIT_LABEL_ID`, st.`PLANNING_UNIT_LABEL_EN`, st.`PLANNING_UNIT_LABEL_FR`, st.`PLANNING_UNIT_LABEL_SP`, st.`PLANNING_UNIT_LABEL_PR`,
        st.ORDER_NO, st.PRIME_LINE_NO,st.`NOTES`,st.CONVERSION_FACTOR,st.PARENT_SHIPMENT_ID,st.ERP_PRODUCT_LABEL_EN,st.ERP_PRODUCT_LABEL_FR,st.ERP_PRODUCT_LABEL_SP,st.ERP_PRODUCT_LABEL_PR,st.ERP_PRODUCT_ID,st.ERP_PRODUCT_LABEL_ID,st.RO_NO,st.RO_PRIME_LINE_NO
FROM (
        SELECT
            s.SHIPMENT_ID, st.RECEIVED_DATE, st.EXPECTED_DELIVERY_DATE,st.SHIPMENT_QTY, st.RATE, st.PRODUCT_COST, st.FREIGHT_COST, st.ACCOUNT_FLAG, st.SHIPMENT_TRANS_ID, papu.SKU_CODE,
            pa.`PROCUREMENT_AGENT_ID`, pa.`PROCUREMENT_AGENT_CODE`, pa.`COLOR_HTML_CODE`, pa.`LABEL_ID` `PROCUREMENT_AGENT_LABEL_ID`, pa.`LABEL_EN` `PROCUREMENT_AGENT_LABEL_EN`, pa.LABEL_FR `PROCUREMENT_AGENT_LABEL_FR`, pa.LABEL_SP `PROCUREMENT_AGENT_LABEL_SP`, pa.LABEL_PR `PROCUREMENT_AGENT_LABEL_PR`,
            fs.`FUNDING_SOURCE_ID`, fs.`FUNDING_SOURCE_CODE`, fs.LABEL_ID `FUNDING_SOURCE_LABEL_ID`, fs.LABEL_EN `FUNDING_SOURCE_LABEL_EN`, fs.LABEL_FR `FUNDING_SOURCE_LABEL_FR`, fs.LABEL_SP `FUNDING_SOURCE_LABEL_SP`, fs.LABEL_PR `FUNDING_SOURCE_LABEL_PR`,
            shs.SHIPMENT_STATUS_ID, shs.LABEL_ID `SHIPMENT_STATUS_LABEL_ID`, shs.LABEL_EN `SHIPMENT_STATUS_LABEL_EN`, shs.LABEL_FR `SHIPMENT_STATUS_LABEL_FR`, shs.LABEL_SP `SHIPMENT_STATUS_LABEL_SP`, shs.LABEL_PR `SHIPMENT_STATUS_LABEL_PR`,
            sc.CURRENCY_ID `SHIPMENT_CURRENCY_ID`, sc.`CURRENCY_CODE` `SHIPMENT_CURRENCY_CODE`, s.CONVERSION_RATE_TO_USD `SHIPMENT_CONVERSION_RATE_TO_USD`,
            sc.LABEL_ID `SHIPMENT_CURRENCY_LABEL_ID`, sc.LABEL_EN `SHIPMENT_CURRENCY_LABEL_EN`, sc.LABEL_FR `SHIPMENT_CURRENCY_LABEL_FR`, sc.LABEL_SP `SHIPMENT_CURRENCY_LABEL_SP`, sc.LABEL_PR `SHIPMENT_CURRENCY_LABEL_PR`,
            mt.ACTIVE, st.`ORDER_NO`, st.`PRIME_LINE_NO`,
            b.BUDGET_ID, b.BUDGET_CODE, b.LABEL_ID `BUDGET_LABEL_ID`, b.LABEL_EN `BUDGET_LABEL_EN`, b.LABEL_FR `BUDGET_LABEL_FR`, b.LABEL_SP `BUDGET_LABEL_SP`, b.LABEL_PR `BUDGET_LABEL_PR`,
            st.PLANNING_UNIT_ID, pu.LABEL_ID `PLANNING_UNIT_LABEL_ID`, pu.LABEL_EN `PLANNING_UNIT_LABEL_EN`, pu.LABEL_FR `PLANNING_UNIT_LABEL_FR`, pu.LABEL_SP `PLANNING_UNIT_LABEL_SP`, pu.LABEL_PR `PLANNING_UNIT_LABEL_PR`,mt.`NOTES`,mt.CONVERSION_FACTOR,s.PARENT_SHIPMENT_ID,pu1.LABEL_EN AS ERP_PRODUCT_LABEL_EN,pu1.LABEL_FR AS ERP_PRODUCT_LABEL_FR,pu1.LABEL_SP AS ERP_PRODUCT_LABEL_SP,pu1.LABEL_PR AS ERP_PRODUCT_LABEL_PR,pu1.PLANNING_UNIT_ID AS ERP_PRODUCT_ID,pu1.LABEL_ID AS ERP_PRODUCT_LABEL_ID,eo.RO_NO,eo.RO_PRIME_LINE_NO
FROM (
    SELECT st.SHIPMENT_ID, MAX(st.VERSION_ID) MAX_VERSION_ID FROM rm_shipment s LEFT JOIN rm_shipment_trans st ON s.SHIPMENT_ID=st.SHIPMENT_ID WHERE (@versiONId=-1 OR st.VERSION_ID<=@versiONId) AND s.PROGRAM_ID=@programId GROUP BY st.SHIPMENT_ID
) ts
    LEFT JOIN rm_shipment s ON ts.SHIPMENT_ID=s.SHIPMENT_ID
    LEFT JOIN rm_shipment_trans st ON ts.SHIPMENT_ID=st.SHIPMENT_ID AND ts.MAX_VERSION_ID=st.VERSION_ID
    LEFT JOIN vw_planning_unit pu ON st.PLANNING_UNIT_ID=pu.PLANNING_UNIT_ID
    LEFT JOIN vw_procurement_agent pa ON st.PROCUREMENT_AGENT_ID=pa.PROCUREMENT_AGENT_ID
    LEFT JOIN vw_funding_source fs ON st.FUNDING_SOURCE_ID=fs.FUNDING_SOURCE_ID
    LEFT JOIN vw_shipment_status shs ON st.SHIPMENT_STATUS_ID=shs.SHIPMENT_STATUS_ID
    LEFT JOIN vw_currency sc ON s.CURRENCY_ID=sc.CURRENCY_ID
    LEFT JOIN vw_budget b ON st.BUDGET_ID=b.BUDGET_ID
    LEFT JOIN rm_manual_tagging mt ON mt.ORDER_NO=st.ORDER_NO AND mt.PRIME_LINE_NO=st.PRIME_LINE_NO AND mt.ACTIVE
    LEFT JOIN rm_procurement_agent_planning_unit papu ON papu.PROCUREMENT_AGENT_ID=pa.PROCUREMENT_AGENT_ID AND papu.PLANNING_UNIT_ID=st.PLANNING_UNIT_ID
    LEFT JOIN (SELECT e.PLANNING_UNIT_SKU_CODE,e.RO_NO,e.RO_PRIME_LINE_NO,e.ORDER_NO,e.PRIME_LINE_NO FROM rm_erp_order e WHERE e.`ERP_ORDER_ID` IN (SELECT MAX(e.`ERP_ORDER_ID`)  AS ERP_ORDER_ID FROM rm_erp_order e
                 GROUP BY e.`RO_NO`,e.`RO_PRIME_LINE_NO`,e.`ORDER_NO`,e.`PRIME_LINE_NO`)) AS eo ON eo.ORDER_NO=st.ORDER_NO AND eo.PRIME_LINE_NO=st.PRIME_LINE_NO
    LEFT JOIN rm_procurement_agent_planning_unit papu1 ON papu1.PROCUREMENT_AGENT_ID=pa.PROCUREMENT_AGENT_ID AND LEFT(papu1.SKU_CODE,12)=eo.PLANNING_UNIT_SKU_CODE
    LEFT JOIN vw_planning_unit pu1 ON papu1.PLANNING_UNIT_ID=pu1.PLANNING_UNIT_ID
    WHERE st.ERP_FLAG=1 AND st.ACTIVE AND st.SHIPMENT_STATUS_ID IN (3,4,5,6,7,9) AND (LENGTH(@planningUnitIds)=0 OR FIND_IN_SET(st.PLANNING_UNIT_ID,@planningUnitIds))   
--    AND (mt.SHIPMENT_ID IS not NULL AND mt.ACTIVE=1) 
    AND st.PROCUREMENT_AGENT_ID=@procurementAgentId
) st
ORDER BY COALESCE(st.RECEIVED_DATE, st.EXPECTED_DELIVERY_DATE) DESC;
END$$

DELIMITER ;



DELIMITER $$

USE `fasp`$$

DROP PROCEDURE IF EXISTS `getErpShipmentForNotLinked`$$

CREATE DEFINER=`faspUser`@`%` PROCEDURE `getErpShipmentForNotLinked`(
    VAR_REALM_COUNTRY_ID INT(10), 
    VAR_PRODUCT_CATEGORY_IDS TEXT, 
    VAR_PLANNING_UNIT_IDS TEXT, 
    VAR_REALM_ID INT(10)
    )
BEGIN
    SET @productCategoryIds = VAR_PRODUCT_CATEGORY_IDS;
    SET @planningUnitIds = VAR_PLANNING_UNIT_IDS;
    SET @realmId = VAR_REALM_ID;
    SET @realmCountryId = VAR_REALM_COUNTRY_ID;
    
    SELECT GROUP_CONCAT(pc2.PRODUCT_CATEGORY_ID) INTO @finalProductCategoryIds FROM rm_product_category pc LEFT JOIN rm_product_category pc2 ON pc2.SORT_ORDER LIKE CONCAT(pc.SORT_ORDER,"%") WHERE FIND_IN_SET(pc.PRODUCT_CATEGORY_ID, @productCategoryIds);
    
    SELECT GROUP_CONCAT(COALESCE(ac.RECEPIENT_NAME, c.LABEL_EN)) INTO @recepientCountryList
    FROM rm_realm_country rc
    LEFT JOIN vw_country c ON rc.COUNTRY_ID=c.COUNTRY_ID
    LEFT JOIN tr_artmis_country ac ON rc.REALM_COUNTRY_ID=ac.REALM_COUNTRY_ID
    WHERE (rc.REALM_COUNTRY_ID=@realmCountryId OR @realmCountryId=-1) AND rc.REALM_ID=@realmId;
    
    SELECT 
        st.ORDER_NO, st.PRIME_LINE_NO, st.`RO_NO`,st.`RO_PRIME_LINE_NO`,st.ERP_ORDER_ID,
        st.PLANNING_UNIT_ID, st.`PLANNING_UNIT_LABEL_ID`, st.`PLANNING_UNIT_LABEL_EN`, st.`PLANNING_UNIT_LABEL_FR`, st.`PLANNING_UNIT_LABEL_SP`, st.`PLANNING_UNIT_LABEL_PR`,
        st.`EXPECTED_DELIVERY_DATE`, st.`STATUS`, st.QTY,st.SKU_CODE
        FROM (
    SELECT 
        o.ORDER_NO, o.PRIME_LINE_NO, o.`RO_NO`,o.`RO_PRIME_LINE_NO`,o.ERP_ORDER_ID,
        pu.PLANNING_UNIT_ID, pu.LABEL_ID `PLANNING_UNIT_LABEL_ID`, pu.LABEL_EN `PLANNING_UNIT_LABEL_EN`, pu.LABEL_FR `PLANNING_UNIT_LABEL_FR`, pu.LABEL_SP `PLANNING_UNIT_LABEL_SP`, pu.LABEL_PR `PLANNING_UNIT_LABEL_PR`,
        COALESCE(o.CURRENT_ESTIMATED_DELIVERY_DATE,o.AGREED_DELIVERY_DATE, o.REQ_DELIVERY_DATE) `EXPECTED_DELIVERY_DATE`, o.`STATUS`, o.QTY,papu.SKU_CODE
    FROM rm_erp_order o 
    LEFT JOIN (SELECT MAX(o.ERP_ORDER_ID) AS ERP_ORDER_ID FROM rm_erp_order o GROUP BY o.`RO_NO`,o.`RO_PRIME_LINE_NO`,o.ORDER_NO, o.PRIME_LINE_NO) o1 ON o.ERP_ORDER_ID=o1.ERP_ORDER_ID 
    LEFT JOIN rm_manual_tagging mt ON mt.ORDER_NO=o.ORDER_NO AND mt.PRIME_LINE_NO=o.PRIME_LINE_NO AND mt.ACTIVE 
    LEFT JOIN rm_procurement_agent_planning_unit papu ON o.PLANNING_UNIT_SKU_CODE=LEFT(papu.SKU_CODE,12) 
    LEFT JOIN vw_planning_unit pu ON papu.PLANNING_UNIT_ID=pu.PLANNING_UNIT_ID 
    LEFT JOIN rm_forecasting_unit fu ON pu.FORECASTING_UNIT_ID=fu.FORECASTING_UNIT_ID 
    LEFT JOIN rm_shipment_status_mapping sm ON sm.`EXTERNAL_STATUS_STAGE`=o.`STATUS`
    WHERE  
        o1.ERP_ORDER_ID IS NOT NULL  
        AND mt.SHIPMENT_ID IS NULL  
        AND o.RECPIENT_COUNTRY!=''  
        AND FIND_IN_SET(o.RECPIENT_COUNTRY,@recepientCountryList)
        AND sm.`SHIPMENT_STATUS_MAPPING_ID` NOT IN (1,3,5,7,9,10,13,15)
         AND (@finalProductCategoryIds IS NULL OR LENGTH(@finalProductCategoryIds)=0 OR FIND_IN_SET(fu.PRODUCT_CATEGORY_ID, @finalProductCategoryIds))
        AND (LENGTH(@planningUnitIds)=0 OR FIND_IN_SET(papu.PLANNING_UNIT_ID, @planningUnitIds))
        ) st
        ORDER BY st.EXPECTED_DELIVERY_DATE DESC;
END$$

DELIMITER ;

DROP TABLE IF EXISTS `fasp`.`rm_erp_notification`;
CREATE TABLE `fasp`.`rm_erp_notification`( `NOTIFICATION_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT , `ORDER_NO` VARCHAR(100) NOT NULL , `PRIME_LINE_NO` INT NOT NULL , `TYPE_ID` INT NOT NULL COMMENT '1-SKU CHANGE 2-CANCELLED', `SHIPMENT_ID` INT NOT NULL , `ADDRESSED` BOOLEAN NOT NULL DEFAULT '0' , `ACTIVE` BOOLEAN NOT NULL DEFAULT '0' , `CREATED_DATE` DATETIME NOT NULL , `CREATED_BY` INT NOT NULL , `LAST_MODIFIED_DATE` DATETIME NOT NULL , `LAST_MODIFIED_BY` INT NOT NULL , PRIMARY KEY (`NOTIFICATION_ID`) ); 

DELIMITER $$

USE `fasp`$$

DROP PROCEDURE IF EXISTS `getNotLinkedShipments`$$

CREATE DEFINER=`faspUser`@`%` PROCEDURE `getNotLinkedShipments`(PROGRAM_ID INT(10),  VERSION_ID INT (10))
BEGIN
    SET @programId = PROGRAM_ID;
    SET @procurementAgentId = 1;
    SET @versionId = VERSION_ID;
    IF @versionId = -1 THEN
        SELECT MAX(pv.VERSION_ID) INTO @versionId FROM rm_program_version pv WHERE pv.PROGRAM_ID=@programId;
    END IF;
   
SELECT
        st.SHIPMENT_ID, st.SHIPMENT_TRANS_ID, st.SHIPMENT_QTY, st.EXPECTED_DELIVERY_DATE, st.PRODUCT_COST, st.SKU_CODE,
        st.PROCUREMENT_AGENT_ID, st.PROCUREMENT_AGENT_CODE, st.`COLOR_HTML_CODE`, st.`PROCUREMENT_AGENT_LABEL_ID`, st.`PROCUREMENT_AGENT_LABEL_EN`, st.`PROCUREMENT_AGENT_LABEL_FR`, st.`PROCUREMENT_AGENT_LABEL_SP`, st.`PROCUREMENT_AGENT_LABEL_PR`,
        st.FUNDING_SOURCE_ID, st.FUNDING_SOURCE_CODE, st.`FUNDING_SOURCE_LABEL_ID`, st.`FUNDING_SOURCE_LABEL_EN`, st.`FUNDING_SOURCE_LABEL_FR`, st.`FUNDING_SOURCE_LABEL_SP`, st.`FUNDING_SOURCE_LABEL_PR`,
        st.BUDGET_ID, st.BUDGET_CODE, st.`BUDGET_LABEL_ID`, st.`BUDGET_LABEL_EN`, st.`BUDGET_LABEL_FR`, st.`BUDGET_LABEL_SP`, st.`BUDGET_LABEL_PR`,
        st.SHIPMENT_STATUS_ID, st.`SHIPMENT_STATUS_LABEL_ID`, st.`SHIPMENT_STATUS_LABEL_EN`, st.`SHIPMENT_STATUS_LABEL_FR`, st.`SHIPMENT_STATUS_LABEL_SP`, st.`SHIPMENT_STATUS_LABEL_PR`,
        st.PLANNING_UNIT_ID, st.`PLANNING_UNIT_LABEL_ID`, st.`PLANNING_UNIT_LABEL_EN`, st.`PLANNING_UNIT_LABEL_FR`, st.`PLANNING_UNIT_LABEL_SP`, st.`PLANNING_UNIT_LABEL_PR`,
        st.ORDER_NO, st.PRIME_LINE_NO,st.`NOTES`
FROM (
        SELECT
            s.SHIPMENT_ID, st.RECEIVED_DATE, st.EXPECTED_DELIVERY_DATE,st.SHIPMENT_QTY, st.RATE, st.PRODUCT_COST, st.FREIGHT_COST, st.ACCOUNT_FLAG, st.SHIPMENT_TRANS_ID, papu.SKU_CODE,
            pa.`PROCUREMENT_AGENT_ID`, pa.`PROCUREMENT_AGENT_CODE`, pa.`COLOR_HTML_CODE`, pa.`LABEL_ID` `PROCUREMENT_AGENT_LABEL_ID`, pa.`LABEL_EN` `PROCUREMENT_AGENT_LABEL_EN`, pa.LABEL_FR `PROCUREMENT_AGENT_LABEL_FR`, pa.LABEL_SP `PROCUREMENT_AGENT_LABEL_SP`, pa.LABEL_PR `PROCUREMENT_AGENT_LABEL_PR`,
            fs.`FUNDING_SOURCE_ID`, fs.`FUNDING_SOURCE_CODE`, fs.LABEL_ID `FUNDING_SOURCE_LABEL_ID`, fs.LABEL_EN `FUNDING_SOURCE_LABEL_EN`, fs.LABEL_FR `FUNDING_SOURCE_LABEL_FR`, fs.LABEL_SP `FUNDING_SOURCE_LABEL_SP`, fs.LABEL_PR `FUNDING_SOURCE_LABEL_PR`,
            shs.SHIPMENT_STATUS_ID, shs.LABEL_ID `SHIPMENT_STATUS_LABEL_ID`, shs.LABEL_EN `SHIPMENT_STATUS_LABEL_EN`, shs.LABEL_FR `SHIPMENT_STATUS_LABEL_FR`, shs.LABEL_SP `SHIPMENT_STATUS_LABEL_SP`, shs.LABEL_PR `SHIPMENT_STATUS_LABEL_PR`,
            sc.CURRENCY_ID `SHIPMENT_CURRENCY_ID`, sc.`CURRENCY_CODE` `SHIPMENT_CURRENCY_CODE`, s.CONVERSION_RATE_TO_USD `SHIPMENT_CONVERSION_RATE_TO_USD`,
            sc.LABEL_ID `SHIPMENT_CURRENCY_LABEL_ID`, sc.LABEL_EN `SHIPMENT_CURRENCY_LABEL_EN`, sc.LABEL_FR `SHIPMENT_CURRENCY_LABEL_FR`, sc.LABEL_SP `SHIPMENT_CURRENCY_LABEL_SP`, sc.LABEL_PR `SHIPMENT_CURRENCY_LABEL_PR`,
            st.ACTIVE, st.`ORDER_NO`, st.`PRIME_LINE_NO`,
            b.BUDGET_ID, b.BUDGET_CODE, b.LABEL_ID `BUDGET_LABEL_ID`, b.LABEL_EN `BUDGET_LABEL_EN`, b.LABEL_FR `BUDGET_LABEL_FR`, b.LABEL_SP `BUDGET_LABEL_SP`, b.LABEL_PR `BUDGET_LABEL_PR`,
            st.PLANNING_UNIT_ID, pu.LABEL_ID `PLANNING_UNIT_LABEL_ID`, pu.LABEL_EN `PLANNING_UNIT_LABEL_EN`, pu.LABEL_FR `PLANNING_UNIT_LABEL_FR`, pu.LABEL_SP `PLANNING_UNIT_LABEL_SP`, pu.LABEL_PR `PLANNING_UNIT_LABEL_PR`,st.`NOTES`
FROM (
    SELECT st.SHIPMENT_ID, MAX(st.VERSION_ID) MAX_VERSION_ID FROM rm_shipment s LEFT JOIN rm_shipment_trans st ON s.SHIPMENT_ID=st.SHIPMENT_ID WHERE (@versiONId=-1 OR st.VERSION_ID<=@versiONId) AND s.PROGRAM_ID=@programId GROUP BY st.SHIPMENT_ID
) ts
    LEFT JOIN rm_shipment s ON ts.SHIPMENT_ID=s.SHIPMENT_ID
    LEFT JOIN rm_shipment_trans st ON ts.SHIPMENT_ID=st.SHIPMENT_ID AND ts.MAX_VERSION_ID=st.VERSION_ID
    LEFT JOIN vw_planning_unit pu ON st.PLANNING_UNIT_ID=pu.PLANNING_UNIT_ID
    LEFT JOIN vw_procurement_agent pa ON st.PROCUREMENT_AGENT_ID=pa.PROCUREMENT_AGENT_ID
    LEFT JOIN vw_funding_source fs ON st.FUNDING_SOURCE_ID=fs.FUNDING_SOURCE_ID
    LEFT JOIN vw_shipment_status shs ON st.SHIPMENT_STATUS_ID=shs.SHIPMENT_STATUS_ID
    LEFT JOIN vw_currency sc ON s.CURRENCY_ID=sc.CURRENCY_ID
    LEFT JOIN vw_budget b ON st.BUDGET_ID=b.BUDGET_ID
    LEFT JOIN rm_manual_tagging mt ON mt.SHIPMENT_ID=ts.SHIPMENT_ID AND mt.ACTIVE
    LEFT JOIN rm_procurement_agent_planning_unit papu ON papu.PROCUREMENT_AGENT_ID=pa.PROCUREMENT_AGENT_ID AND papu.PLANNING_UNIT_ID=st.PLANNING_UNIT_ID
    WHERE st.ERP_FLAG=0 AND st.ACTIVE AND st.SHIPMENT_STATUS_ID IN (3,4,5,6,9)  AND (mt.SHIPMENT_ID IS NULL OR mt.ACTIVE=0) AND st.PROCUREMENT_AGENT_ID=@procurementAgentId
) st
ORDER BY COALESCE(st.RECEIVED_DATE, st.EXPECTED_DELIVERY_DATE);
END$$

DELIMITER ;

CREATE TABLE `fasp`.`ap_notification_type`( `NOTIFICATION_TYPE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT , `LABEL_ID` INT NOT NULL , `ACTIVE` TINYINT NOT NULL DEFAULT '1' , `CREATED_DATE` DATETIME NOT NULL , `CREATED_BY` INT NOT NULL , `LAST_MODIFIED_DATE` DATETIME NOT NULL , `LAST_MODIFIED_BY` INT NOT NULL , PRIMARY KEY (`NOTIFICATION_TYPE_ID`) ); 

ALTER TABLE `fasp`.`rm_erp_notification` CHANGE `TYPE_ID` `NOTIFICATION_TYPE_ID` INT(11) NOT NULL COMMENT '1-SKU CHANGE 2-CANCELLED'; 

DELIMITER $$

USE `fasp`$$

DROP PROCEDURE IF EXISTS `getShipmentLinkingNotifications`$$

CREATE DEFINER=`faspUser`@`%` PROCEDURE `getShipmentLinkingNotifications`(PROGRAM_ID INT(10), PLANNING_UNIT_ID TEXT, VERSION_ID INT (10))
BEGIN
    SET @programId = PROGRAM_ID;
    SET @planningUnitIds = PLANNING_UNIT_ID;
    SET @procurementAgentId = 1;
    SET @versionId = VERSION_ID;
    IF @versionId = -1 THEN
        SELECT MAX(pv.VERSION_ID) INTO @versionId FROM rm_program_version pv WHERE pv.PROGRAM_ID=@programId;
    END IF;
   
SELECT n.`NOTIFICATION_ID`,n.ADDRESSED,n.NOTIFICATION_TYPE_ID,lnt.*,st.`SHIPMENT_ID`,st.`ORDER_NO`,st.`PRIME_LINE_NO`,eo.RO_NO,eo.RO_PRIME_LINE_NO,
st.PLANNING_UNIT_ID, pu.LABEL_ID `PLANNING_UNIT_LABEL_ID`, pu.LABEL_EN `PLANNING_UNIT_LABEL_EN`, pu.LABEL_FR `PLANNING_UNIT_LABEL_FR`,
 pu.LABEL_SP `PLANNING_UNIT_LABEL_SP`, pu.LABEL_PR `PLANNING_UNIT_LABEL_PR`,
 papu1.PLANNING_UNIT_ID AS ERP_PLANNING_UNIT_ID, pu1.LABEL_ID `ERP_PLANNING_UNIT_LABEL_ID`, pu1.LABEL_EN `ERP_PLANNING_UNIT_LABEL_EN`, pu1.LABEL_FR `ERP_PLANNING_UNIT_LABEL_FR`,
 pu1.LABEL_SP `ERP_PLANNING_UNIT_LABEL_SP`, pu1.LABEL_PR `ERP_PLANNING_UNIT_LABEL_PR`,st.`EXPECTED_DELIVERY_DATE`,
 ss.`SHIPMENT_STATUS_ID`,ss.`LABEL_EN` AS SHIPMENT_STATUS_LABEL_EN,ss.`LABEL_FR` AS SHIPMENT_STATUS_LABEL_FR,ss.`LABEL_ID`  AS SHIPMENT_STATUS_LABEL_ID,ss.`LABEL_PR` AS SHIPMENT_STATUS_LABEL_PR,ss.`LABEL_SP` AS SHIPMENT_STATUS_LABEL_SP,
 pa.`PROCUREMENT_AGENT_ID`, pa.`PROCUREMENT_AGENT_CODE`, pa.`COLOR_HTML_CODE`, pa.`LABEL_ID` `PROCUREMENT_AGENT_LABEL_ID`, pa.`LABEL_EN` `PROCUREMENT_AGENT_LABEL_EN`, pa.LABEL_FR `PROCUREMENT_AGENT_LABEL_FR`, pa.LABEL_SP `PROCUREMENT_AGENT_LABEL_SP`, pa.LABEL_PR `PROCUREMENT_AGENT_LABEL_PR`,st.`SHIPMENT_QTY`,
 n.NOTES,m.CONVERSION_FACTOR,n.SHIPMENT_ID AS PARENT_SHIPMENT_ID,eo.STATUS
 FROM (
SELECT st.SHIPMENT_ID, MAX(st.VERSION_ID) MAX_VERSION_ID 
FROM rm_shipment s LEFT JOIN rm_shipment_trans st ON s.SHIPMENT_ID=st.SHIPMENT_ID 
WHERE (@versiONId=-1 OR st.VERSION_ID<=@versiONId) AND s.PROGRAM_ID=@programId GROUP BY st.SHIPMENT_ID
)  ts
LEFT JOIN rm_shipment s ON s.`SHIPMENT_ID`=ts.`SHIPMENT_ID`
LEFT JOIN rm_erp_notification n ON n.`SHIPMENT_ID`=s.`PARENT_SHIPMENT_ID`
LEFT JOIN ap_notification_type nt ON nt.`NOTIFICATION_TYPE_ID`=n.`NOTIFICATION_TYPE_ID`
LEFT JOIN ap_label lnt ON lnt.`LABEL_ID`=nt.`LABEL_ID`
LEFT JOIN rm_shipment_trans st ON ts.SHIPMENT_ID=st.SHIPMENT_ID AND ts.MAX_VERSION_ID=st.VERSION_ID
LEFT JOIN vw_planning_unit pu ON st.PLANNING_UNIT_ID=pu.PLANNING_UNIT_ID
LEFT JOIN rm_procurement_agent_planning_unit papu ON papu.PROCUREMENT_AGENT_ID=1 AND papu.PLANNING_UNIT_ID=st.PLANNING_UNIT_ID
LEFT JOIN (SELECT e.PLANNING_UNIT_SKU_CODE,e.RO_NO,e.RO_PRIME_LINE_NO,e.ORDER_NO,e.PRIME_LINE_NO ,e.`STATUS`
FROM rm_erp_order e WHERE e.`ERP_ORDER_ID` IN (SELECT MAX(e.`ERP_ORDER_ID`)  AS ERP_ORDER_ID 
FROM rm_erp_order e
GROUP BY e.`RO_NO`,e.`RO_PRIME_LINE_NO`,e.`ORDER_NO`,e.`PRIME_LINE_NO`)) AS eo 
ON eo.ORDER_NO=st.ORDER_NO AND eo.PRIME_LINE_NO=st.PRIME_LINE_NO 
LEFT JOIN rm_procurement_agent_planning_unit papu1 ON papu1.PROCUREMENT_AGENT_ID=1 AND LEFT(papu1.SKU_CODE,12)=eo.PLANNING_UNIT_SKU_CODE
LEFT JOIN vw_planning_unit pu1 ON papu1.PLANNING_UNIT_ID=pu1.PLANNING_UNIT_ID
LEFT JOIN rm_shipment_status_mapping ssm ON ssm.`EXTERNAL_STATUS_STAGE`=eo.STATUS
LEFT JOIN vw_shipment_status ss ON ss.`SHIPMENT_STATUS_ID`=ssm.`SHIPMENT_STATUS_ID`
LEFT JOIN vw_procurement_agent pa ON st.PROCUREMENT_AGENT_ID=pa.PROCUREMENT_AGENT_ID
LEFT JOIN rm_manual_tagging m ON m.ORDER_NO=n.ORDER_NO AND m.PRIME_LINE_NO=n.PRIME_LINE_NO AND m.SHIPMENT_ID=n.SHIPMENT_ID AND m.ACTIVE
WHERE n.`NOTIFICATION_ID` IS NOT NULL AND n.ACTIVE AND (LENGTH(@planningUnitIds)=0 OR FIND_IN_SET(st.PLANNING_UNIT_ID,@planningUnitIds))   
    AND st.PROCUREMENT_AGENT_ID=@procurementAgentId GROUP BY n.`NOTIFICATION_ID`;
END$$

DELIMITER ;

ALTER TABLE `fasp`.`rm_erp_notification` ADD COLUMN `NOTES` TEXT NULL AFTER `LAST_MODIFIED_BY`; 
ALTER TABLE `fasp`.`rm_erp_notification` ADD COLUMN `CONVERSION_FACTOR` DECIMAL(12,4) NULL AFTER `NOTES`; 

INSERT INTO `fasp`.`ap_label_source`(`SOURCE_ID`,`SOURCE_DESC`) VALUES ( NULL,'ap_notification_type'); 

INSERT INTO `fasp`.`ap_label`(`LABEL_ID`,`LABEL_EN`,`LABEL_FR`,`LABEL_SP`,`LABEL_PR`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`,`SOURCE_ID`) VALUES ( NULL,'Cancellation',NULL,NULL,NULL,'1',NOW(),'1',NOW(),'36'); 
INSERT INTO `fasp`.`ap_notification_type`(`NOTIFICATION_TYPE_ID`,`LABEL_ID`,`ACTIVE`,`CREATED_DATE`,`CREATED_BY`,`LAST_MODIFIED_DATE`,`LAST_MODIFIED_BY`) VALUES ( NULL,LAST_INSERT_ID(),'1',NOW(),'1',NOW(),'1'); 

INSERT INTO `fasp`.`ap_label`(`LABEL_ID`,`LABEL_EN`,`LABEL_FR`,`LABEL_SP`,`LABEL_PR`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`,`SOURCE_ID`) VALUES ( NULL,'ERP Current Product Change',NULL,NULL,NULL,'1',NOW(),'1',NOW(),'36'); 
INSERT INTO `fasp`.`ap_notification_type`(`NOTIFICATION_TYPE_ID`,`LABEL_ID`,`ACTIVE`,`CREATED_DATE`,`CREATED_BY`,`LAST_MODIFIED_DATE`,`LAST_MODIFIED_BY`) VALUES ( NULL,LAST_INSERT_ID(),'1',NOW(),'1',NOW(),'1'); 

INSERT INTO `fasp`.`ap_label`(`LABEL_ID`,`LABEL_EN`,`LABEL_FR`,`LABEL_SP`,`LABEL_PR`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`,`SOURCE_ID`) VALUES ( NULL,'ERP Previous Product Change',NULL,NULL,NULL,'1',NOW(),'1',NOW(),'36'); 
INSERT INTO `fasp`.`ap_notification_type`(`NOTIFICATION_TYPE_ID`,`LABEL_ID`,`ACTIVE`,`CREATED_DATE`,`CREATED_BY`,`LAST_MODIFIED_DATE`,`LAST_MODIFIED_BY`) VALUES ( NULL,LAST_INSERT_ID(),'1',NOW(),'1',NOW(),'1'); 

INSERT INTO `fasp`.`us_role_business_function`(`ROLE_BUSINESS_FUNCTION_ID`,`ROLE_ID`,`BUSINESS_FUNCTION_ID`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`) VALUES ( NULL,'ROLE_PROGRAM_ADMIN','ROLE_BF_MANUAL_TAGGING','1',NOW(),'1',NOW()); 

CREATE TABLE `fasp`.`rm_manual_tagging_trans` ( PRIMARY KEY(`MANUAL_TAGGING_ID`),KEY `fk_rm_manual_tagging_rm_shipment1_idx`( `SHIPMENT_ID` ), KEY `fk_rm_manual_tagging_us_user1_idx`( `CREATED_BY` ), KEY `fk_rm_manual_tagging_us_user2_idx`( `LAST_MODIFIED_BY` ), KEY `idx_rmManualTagging_orderNo`( `ORDER_NO` ), KEY `idx_rmManualTagging_primeLineNo`( `PRIME_LINE_NO` ))ENGINE=INNODB COLLATE = utf8_bin COMMENT = '' SELECT `MANUAL_TAGGING_ID`, `ORDER_NO`, `PRIME_LINE_NO`, `SHIPMENT_ID`, `CREATED_DATE`, `CREATED_BY`, `LAST_MODIFIED_DATE`, `LAST_MODIFIED_BY`, `ACTIVE`, `NOTES`, `CONVERSION_FACTOR` FROM `fasp`.`rm_manual_tagging`; 
ALTER TABLE `fasp`.`rm_manual_tagging_trans` DROP COLUMN `CREATED_DATE`, DROP COLUMN `CREATED_BY`, ADD COLUMN `MANUAL_TAGGING_TRANS_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT FIRST, CHANGE `MANUAL_TAGGING_ID` `MANUAL_TAGGING_ID` INT(10) UNSIGNED NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY(`MANUAL_TAGGING_TRANS_ID`); 

DELIMITER $$

USE `fasp`$$

DROP TRIGGER /*!50032 IF EXISTS */ `rm_manual_tagging_AFTER_INSERT`$$

CREATE
    /*!50017 DEFINER = 'faspUser'@'%' */
    TRIGGER `rm_manual_tagging_AFTER_INSERT` AFTER INSERT ON `rm_manual_tagging` 
    FOR EACH ROW BEGIN
	INSERT INTO rm_manual_tagging_trans (`MANUAL_TAGGING_TRANS_ID`,`MANUAL_TAGGING_ID`,`ORDER_NO`,`PRIME_LINE_NO`,`SHIPMENT_ID`,`LAST_MODIFIED_DATE`,`LAST_MODIFIED_BY`,`ACTIVE`,`NOTES`,`CONVERSION_FACTOR`) 
    VALUES(NULL,new.`MANUAL_TAGGING_ID`,new.ORDER_NO,new.PRIME_LINE_NO,new.SHIPMENT_ID,new.`LAST_MODIFIED_DATE`,new.LAST_MODIFIED_BY,new.ACTIVE,new.NOTES,new.CONVERSION_FACTOR);
END;
$$

DELIMITER ;

DELIMITER $$

USE `fasp`$$

DROP TRIGGER /*!50032 IF EXISTS */ `rm_manual_tagging_AFTER_UPDATE`$$

CREATE
    /*!50017 DEFINER = 'faspUser'@'%' */
    TRIGGER `rm_manual_tagging_AFTER_UPDATE` AFTER UPDATE ON `rm_manual_tagging` 
    FOR EACH ROW BEGIN
	INSERT INTO rm_manual_tagging_trans (`MANUAL_TAGGING_TRANS_ID`,`MANUAL_TAGGING_ID`,`ORDER_NO`,`PRIME_LINE_NO`,`SHIPMENT_ID`,`LAST_MODIFIED_DATE`,`LAST_MODIFIED_BY`,`ACTIVE`,`NOTES`,`CONVERSION_FACTOR`) 
    VALUES(NULL,new.`MANUAL_TAGGING_ID`,new.ORDER_NO,new.PRIME_LINE_NO,new.SHIPMENT_ID,new.`LAST_MODIFIED_DATE`,new.LAST_MODIFIED_BY,new.ACTIVE,new.NOTES,new.CONVERSION_FACTOR);
END;
$$

DELIMITER ;



INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES (NULL,'static.mt.notLinkedQAT','1');  

SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ; 

 

INSERT INTO `fasp`.`ap_static_label_languages`(`STATIC_LABEL_LANGUAGE_ID`,`STATIC_LABEL_ID`,`LANGUAGE_ID`,`LABEL_TEXT`) VALUES ( NULL,@MAX,'1','Not Linked (QAT)');  

INSERT INTO `fasp`.`ap_static_label_languages`(`STATIC_LABEL_LANGUAGE_ID`,`STATIC_LABEL_ID`,`LANGUAGE_ID`,`LABEL_TEXT`) VALUES ( NULL,@MAX,'2','Non lié (QAT)');  

INSERT INTO `fasp`.`ap_static_label_languages`(`STATIC_LABEL_LANGUAGE_ID`,`STATIC_LABEL_ID`,`LANGUAGE_ID`,`LABEL_TEXT`) VALUES ( NULL,@MAX,'3','No vinculado (QAT)');  

INSERT INTO `fasp`.`ap_static_label_languages`(`STATIC_LABEL_LANGUAGE_ID`,`STATIC_LABEL_ID`,`LANGUAGE_ID`,`LABEL_TEXT`) VALUES ( NULL,@MAX,'4','Não vinculado (QAT)');  

 

 

 

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.notLinkedERP','1');  

SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ; 

 

INSERT INTO `fasp`.`ap_static_label_languages`(`STATIC_LABEL_LANGUAGE_ID`,`STATIC_LABEL_ID`,`LANGUAGE_ID`,`LABEL_TEXT`) VALUES ( NULL,@MAX,'1','Not Linked (ERP)');  

INSERT INTO `fasp`.`ap_static_label_languages`(`STATIC_LABEL_LANGUAGE_ID`,`STATIC_LABEL_ID`,`LANGUAGE_ID`,`LABEL_TEXT`) VALUES ( NULL,@MAX,'2','Non lié (ERP)');  

INSERT INTO `fasp`.`ap_static_label_languages`(`STATIC_LABEL_LANGUAGE_ID`,`STATIC_LABEL_ID`,`LANGUAGE_ID`,`LABEL_TEXT`) VALUES ( NULL,@MAX,'3','No vinculado (ERP)');  

INSERT INTO `fasp`.`ap_static_label_languages`(`STATIC_LABEL_LANGUAGE_ID`,`STATIC_LABEL_ID`,`LANGUAGE_ID`,`LABEL_TEXT`) VALUES ( NULL,@MAX,'4','Não vinculado (ERP)');  

 

 

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.linked','1');  

SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ; 

INSERT INTO `fasp`.`ap_static_label_languages`(`STATIC_LABEL_LANGUAGE_ID`,`STATIC_LABEL_ID`,`LANGUAGE_ID`,`LABEL_TEXT`) VALUES ( NULL,@MAX,'1','Linked');  

INSERT INTO `fasp`.`ap_static_label_languages`(`STATIC_LABEL_LANGUAGE_ID`,`STATIC_LABEL_ID`,`LANGUAGE_ID`,`LABEL_TEXT`) VALUES ( NULL,@MAX,'2','Lié');  

INSERT INTO `fasp`.`ap_static_label_languages`(`STATIC_LABEL_LANGUAGE_ID`,`STATIC_LABEL_ID`,`LANGUAGE_ID`,`LABEL_TEXT`) VALUES ( NULL,@MAX,'3','Vinculado');  

INSERT INTO `fasp`.`ap_static_label_languages`(`STATIC_LABEL_LANGUAGE_ID`,`STATIC_LABEL_ID`,`LANGUAGE_ID`,`LABEL_TEXT`) VALUES ( NULL,@MAX,'4','Vinculado');  




INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.selectShipmentId','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Please select shipment id');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Veuillez sélectionner lidentifiant de lenvoi');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Seleccione la identificación de envío');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Selecione a identificação da remessa');

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.selectProgram','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Please select program');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Veuillez sélectionner un programme');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Por favor seleccione programa');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Selecione o programa');

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.selectFundingSource','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Please select funding source');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Veuillez sélectionner la source de financement');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Seleccione la fuente de financiación');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Selecione a fonte de financiamento');

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.selectBudget','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Please select budget');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Veuillez sélectionner le budget');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Por favor seleccione presupuesto');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Selecione o orçamento');

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.confirmNewShipmentCreation','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'You are about to create a new shipment. Are you sure you want to continue?');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Vous êtes sur le point de créer un nouvel envoi. Es-tu sur de vouloir continuer?');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Está a punto de crear un nuevo envío. Estás seguro de que quieres continuar?');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Você está prestes a criar uma nova remessa. Você tem certeza que quer continuar?');


INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.oneOrderAtATime','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Please select only 1 order at a time.');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Veuillez ne sélectionner quune seule commande à la fois.');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Seleccione solo 1 pedido a la vez.');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Selecione apenas 1 pedido de cada vez.');

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.linkingUpdateSuccess','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Shipment linking updated successfully');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'La liaison de lenvoi a bien été mise à jour');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Enlace de envío actualizado correctamente');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Vinculação de remessa atualizada com sucesso');

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.linkColumn','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Link?');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Relier?');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'¿Enlace?');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Link?');

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.parentShipmentId','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Parent Shipment Id');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'ID de lenvoi parent');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'ID de envío principal');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Id de remessa pai');

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.selectShipment','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Select shipment id');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Sélectionnez lidentifiant de lenvoi');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Seleccionar id de envío');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Selecione a identificação da remessa');


INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.createNewShipment','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Create New Shipment');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Créer un nouvel envoi');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Crear nuevo envío');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Criar Nova Remessa');

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.selectExistingShipment','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Select Existing Shipment');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Sélectionnez un envoi existant');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Seleccionar envío existente');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Selecione Remessa Existente');




INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.dataUpdateSuccess','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Data updated successfully.');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Les données ont été mises à jour avec succès.');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Datos actualizados con éxito.');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Dados atualizados com sucesso.');


INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.isAddressed','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Addressed?');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Adressé?');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'¿Dirigida?');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Endereçada?');

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.notificationType','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Notification Type');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Type de notification');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Tipo de notificación');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Tipo de notificação');

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.viewArtmisHistory','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'View ARTMIS History');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Afficher lhistorique dARTMIS');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Ver historial de ARTMIS');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Ver o histórico do ARTMIS');

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.dataReceivedOn','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Data Received On');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Données reçues le');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Datos recibidos el');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Dados recebidos em');

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.addressed','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Addressed');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Adressé');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Dirigida');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Endereçada');

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.notAddressed','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Not Addressed');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Pas adressé');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'No dirigida');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Não endereçado');



INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.selectPlanninfUnit','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Please select planning unit');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Veuillez sélectionner lunité de planification');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Seleccione la unidad de planificación');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Selecione a unidade de planejamento');



INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.filterByShipmentId','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Filter by QAT shipment id?');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Filtrer par identifiant dexpédition QAT?');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'¿Filtrar por ID de envío QAT?');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Filtrar por ID de remessa QAT?');




UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT`='Search By RO/Order No.' WHERE `STATIC_LABEL_LANGUAGE_ID`='6005'; 
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT`='Pesquisa por RO / Nº do pedido' WHERE `STATIC_LABEL_LANGUAGE_ID`='6008'; 
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT`='Buscar por RO / Núm. De pedido' WHERE `STATIC_LABEL_LANGUAGE_ID`='6006'; 
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT`='Recherche par RO / N ° de commande' WHERE `STATIC_LABEL_LANGUAGE_ID`='6007'; 


INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.delinkAllShipments','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'You have delinked all the shipments.Your data will be reverted to the original QAT shipment.Are you sure you want to continue?');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Vous avez dissocié tous les envois. Vos données seront rétablies sur lenvoi QAT dorigine. Voulez-vous vraiment continuer?');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Ha desvinculado todos los envíos. Sus datos se revertirán al envío QAT original. ¿Está seguro de que desea continuar?');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Você desvinculou todas as remessas. Seus dados serão revertidos para a remessa QAT original. Tem certeza de que deseja continuar?');



INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.totalQty','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'/ ERP Quantity');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'/ Quantité ERP');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'/ Cantidad de ERP');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'/ Quantidade ERP');



INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.masterDataSyncNote','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Reminder: If you make any changes in this screen, you will need to click “master data sync” for those changes to be seen throughout the tool.');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Rappel: si vous apportez des modifications dans cet écran, vous devrez cliquer sur «synchronisation des données de base» pour que ces modifications soient visibles dans tout loutil.');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Recordatorio: si realiza algún cambio en esta pantalla, deberá hacer clic en “sincronización de datos maestros” para que esos cambios se vean en toda la herramienta.');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Lembrete: se você fizer alguma alteração nesta tela, precisará clicar em “sincronização de dados mestre” para que essas alterações sejam vistas em toda a ferramenta.');



INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.tab1Purpose','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Use this screen to link QAT shipments with ERP orders for the first time');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Utilisez cet écran pour lier les envois QAT aux commandes ERP pour la première fois');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Utilice esta pantalla para vincular los envíos QAT con los pedidos de ERP por primera vez');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Use esta tela para vincular remessas QAT com pedidos ERP pela primeira vez');


INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.tab2Purpose','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Use this screen to update or de-link existing QAT-ERP linkages.');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Utilisez cet écran pour mettre à jour ou dissocier les liaisons QAT-ERP existantes.');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Utilice esta pantalla para actualizar o desvincular los enlaces QAT-ERP existentes.');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Use esta tela para atualizar ou desvincular links QAT-ERP existentes.');


INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.tab3Purpose','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Use this screen to link ERP orders to QAT for the first time');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Utilisez cet écran pour lier les commandes ERP à QAT pour la première fois');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Utilice esta pantalla para vincular los pedidos de ERP a QAT por primera vez');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Use esta tela para vincular pedidos de ERP ao QAT pela primeira vez');


INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.shipmentLinkingNotification','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'ERP Shipment Notifications');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Notifications dexpédition ERP');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Notificaciones de envío de ERP');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Notificações de remessa de ERP');


INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.originalQty','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Original Quantity');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Quantité dorigine');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Cantidad original');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Quantidade Original');

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.mt.childShipmentId','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Child Shipment Id');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'ID de lenvoi enfant');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'ID de envío secundario');
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Id de Remessa Infantil');


DELIMITER $$

USE `fasp`$$

DROP PROCEDURE IF EXISTS `getShipmentLinkingNotifications`$$

CREATE DEFINER=`faspUser`@`%` PROCEDURE `getShipmentLinkingNotifications`(PROGRAM_ID INT(10), PLANNING_UNIT_ID TEXT, VERSION_ID INT (10))
BEGIN
    SET @programId = PROGRAM_ID;
    SET @planningUnitIds = PLANNING_UNIT_ID;
    SET @procurementAgentId = 1;
    SET @versionId = VERSION_ID;
    IF @versionId = -1 THEN
        SELECT MAX(pv.VERSION_ID) INTO @versionId FROM rm_program_version pv WHERE pv.PROGRAM_ID=@programId;
    END IF;
   
-- SELECT n.`NOTIFICATION_ID`,n.ADDRESSED,n.NOTIFICATION_TYPE_ID,lnt.*,st.`SHIPMENT_ID`,st.`ORDER_NO`,m.`PRIME_LINE_NO`,eo.RO_NO,eo.RO_PRIME_LINE_NO,
-- st.PLANNING_UNIT_ID, pu.LABEL_ID `PLANNING_UNIT_LABEL_ID`, pu.LABEL_EN `PLANNING_UNIT_LABEL_EN`, pu.LABEL_FR `PLANNING_UNIT_LABEL_FR`,
--  pu.LABEL_SP `PLANNING_UNIT_LABEL_SP`, pu.LABEL_PR `PLANNING_UNIT_LABEL_PR`,
--  papu1.PLANNING_UNIT_ID AS ERP_PLANNING_UNIT_ID, pu1.LABEL_ID `ERP_PLANNING_UNIT_LABEL_ID`, pu1.LABEL_EN `ERP_PLANNING_UNIT_LABEL_EN`, pu1.LABEL_FR `ERP_PLANNING_UNIT_LABEL_FR`,
--  pu1.LABEL_SP `ERP_PLANNING_UNIT_LABEL_SP`, pu1.LABEL_PR `ERP_PLANNING_UNIT_LABEL_PR`,st.`EXPECTED_DELIVERY_DATE`,
--  ss.`SHIPMENT_STATUS_ID`,ss.`LABEL_EN` AS SHIPMENT_STATUS_LABEL_EN,ss.`LABEL_FR` AS SHIPMENT_STATUS_LABEL_FR,ss.`LABEL_ID`  AS SHIPMENT_STATUS_LABEL_ID,ss.`LABEL_PR` AS SHIPMENT_STATUS_LABEL_PR,ss.`LABEL_SP` AS SHIPMENT_STATUS_LABEL_SP,
--  pa.`PROCUREMENT_AGENT_ID`, pa.`PROCUREMENT_AGENT_CODE`, pa.`COLOR_HTML_CODE`, pa.`LABEL_ID` `PROCUREMENT_AGENT_LABEL_ID`, pa.`LABEL_EN` `PROCUREMENT_AGENT_LABEL_EN`, pa.LABEL_FR `PROCUREMENT_AGENT_LABEL_FR`, pa.LABEL_SP `PROCUREMENT_AGENT_LABEL_SP`, pa.LABEL_PR `PROCUREMENT_AGENT_LABEL_PR`,st.`SHIPMENT_QTY`,
--  n.NOTES,m.CONVERSION_FACTOR,n.SHIPMENT_ID AS PARENT_SHIPMENT_ID,eo.STATUS
--  FROM (
-- SELECT st.SHIPMENT_ID, MAX(st.VERSION_ID) MAX_VERSION_ID 
-- FROM rm_shipment s LEFT JOIN rm_shipment_trans st ON s.SHIPMENT_ID=st.SHIPMENT_ID 
-- WHERE (@versiONId=-1 OR st.VERSION_ID<=@versiONId) AND s.PROGRAM_ID=@programId GROUP BY st.SHIPMENT_ID
-- )  ts
-- LEFT JOIN rm_shipment s ON s.`SHIPMENT_ID`=ts.`SHIPMENT_ID`
-- LEFT JOIN rm_erp_notification n ON n.`SHIPMENT_ID`=s.`PARENT_SHIPMENT_ID`
-- LEFT JOIN ap_notification_type nt ON nt.`NOTIFICATION_TYPE_ID`=n.`NOTIFICATION_TYPE_ID`
-- LEFT JOIN ap_label lnt ON lnt.`LABEL_ID`=nt.`LABEL_ID`
-- LEFT JOIN rm_shipment_trans st ON ts.SHIPMENT_ID=st.SHIPMENT_ID AND ts.MAX_VERSION_ID=st.VERSION_ID
-- LEFT JOIN vw_planning_unit pu ON st.PLANNING_UNIT_ID=pu.PLANNING_UNIT_ID
-- LEFT JOIN rm_procurement_agent_planning_unit papu ON papu.PROCUREMENT_AGENT_ID=1 AND papu.PLANNING_UNIT_ID=st.PLANNING_UNIT_ID
-- 
-- LEFT JOIN rm_manual_tagging m ON m.ORDER_NO=n.ORDER_NO AND m.PRIME_LINE_NO=n.PRIME_LINE_NO AND m.SHIPMENT_ID=n.SHIPMENT_ID
-- LEFT JOIN (SELECT e.PLANNING_UNIT_SKU_CODE,e.RO_NO,e.RO_PRIME_LINE_NO,e.ORDER_NO,e.PRIME_LINE_NO ,e.`STATUS`
-- FROM rm_erp_order e WHERE e.`ERP_ORDER_ID` IN (SELECT MAX(e.`ERP_ORDER_ID`)  AS ERP_ORDER_ID 
-- FROM rm_erp_order e
-- GROUP BY e.`RO_NO`,e.`RO_PRIME_LINE_NO`,e.`ORDER_NO`,e.`PRIME_LINE_NO`)) AS eo 
-- ON eo.ORDER_NO=m.ORDER_NO AND eo.PRIME_LINE_NO=m.PRIME_LINE_NO 
-- 
-- LEFT JOIN rm_procurement_agent_planning_unit papu1 ON papu1.PROCUREMENT_AGENT_ID=1 AND LEFT(papu1.SKU_CODE,12)=eo.PLANNING_UNIT_SKU_CODE
-- LEFT JOIN vw_planning_unit pu1 ON papu1.PLANNING_UNIT_ID=pu1.PLANNING_UNIT_ID
-- LEFT JOIN rm_shipment_status_mapping ssm ON ssm.`EXTERNAL_STATUS_STAGE`=eo.STATUS
-- LEFT JOIN vw_shipment_status ss ON ss.`SHIPMENT_STATUS_ID`=ssm.`SHIPMENT_STATUS_ID`
-- LEFT JOIN vw_procurement_agent pa ON st.PROCUREMENT_AGENT_ID=pa.PROCUREMENT_AGENT_ID
-- WHERE n.`NOTIFICATION_ID` IS NOT NULL AND n.ACTIVE AND (LENGTH(@planningUnitIds)=0 OR FIND_IN_SET(st.PLANNING_UNIT_ID,@planningUnitIds))   
--     AND st.PROCUREMENT_AGENT_ID=@procurementAgentId GROUP BY n.`NOTIFICATION_ID`;

SELECT n.`NOTIFICATION_ID`,n.`ADDRESSED`,n.NOTIFICATION_TYPE_ID,l.*,n.`CHILD_SHIPMENT_ID` AS SHIPMENT_ID,e.`RO_NO`,e.`RO_PRIME_LINE_NO`,e.`ORDER_NO`,e.`PRIME_LINE_NO`,
st.`EXPECTED_DELIVERY_DATE`,e.`STATUS`,st.`SHIPMENT_QTY`,COALESCE(n.`CONVERSION_FACTOR`,m.CONVERSION_FACTOR) AS CONVERSION_FACTOR,n.`NOTES`,s.`PARENT_SHIPMENT_ID`,
st.PLANNING_UNIT_ID, pu.LABEL_ID `PLANNING_UNIT_LABEL_ID`, pu.LABEL_EN `PLANNING_UNIT_LABEL_EN`, pu.LABEL_FR `PLANNING_UNIT_LABEL_FR`,
 pu.LABEL_SP `PLANNING_UNIT_LABEL_SP`, pu.LABEL_PR `PLANNING_UNIT_LABEL_PR`,
 papu1.PLANNING_UNIT_ID AS ERP_PLANNING_UNIT_ID, pu1.LABEL_ID `ERP_PLANNING_UNIT_LABEL_ID`, pu1.LABEL_EN `ERP_PLANNING_UNIT_LABEL_EN`, pu1.LABEL_FR `ERP_PLANNING_UNIT_LABEL_FR`,
 pu1.LABEL_SP `ERP_PLANNING_UNIT_LABEL_SP`, pu1.LABEL_PR `ERP_PLANNING_UNIT_LABEL_PR`
 FROM 
(SELECT st.SHIPMENT_ID, MAX(st.VERSION_ID) MAX_VERSION_ID 
FROM rm_shipment s LEFT JOIN rm_shipment_trans st ON s.SHIPMENT_ID=st.SHIPMENT_ID 
WHERE (@versiONId=-1 OR st.VERSION_ID<=@versiONId) AND s.PROGRAM_ID=@programId GROUP BY st.SHIPMENT_ID
) ts
LEFT JOIN rm_shipment s ON s.`SHIPMENT_ID`=ts.`SHIPMENT_ID`
LEFT JOIN rm_erp_notification n ON n.`CHILD_SHIPMENT_ID`=s.`SHIPMENT_ID`
LEFT JOIN ap_notification_type nt ON nt.`NOTIFICATION_TYPE_ID`=n.`NOTIFICATION_TYPE_ID`
LEFT JOIN ap_label l ON l.`LABEL_ID`=nt.`LABEL_ID`
LEFT JOIN rm_erp_order e ON e.`ERP_ORDER_ID`=n.`ERP_ORDER_ID`
LEFT JOIN rm_procurement_agent_planning_unit papu1 ON LEFT(papu1.`SKU_CODE`,12)=e.`PLANNING_UNIT_SKU_CODE`
LEFT JOIN vw_planning_unit pu1 ON pu1.`PLANNING_UNIT_ID`=papu1.`PLANNING_UNIT_ID`
LEFT JOIN rm_shipment_trans st ON ts.SHIPMENT_ID=st.SHIPMENT_ID AND ts.MAX_VERSION_ID=st.VERSION_ID
LEFT JOIN rm_procurement_agent_planning_unit papu2 ON papu2.`PLANNING_UNIT_ID`=st.`PLANNING_UNIT_ID`
LEFT JOIN vw_planning_unit pu ON pu.`PLANNING_UNIT_ID`=papu2.`PLANNING_UNIT_ID`
LEFT JOIN rm_manual_tagging m ON m.ORDER_NO=e.ORDER_NO AND m.PRIME_LINE_NO=e.PRIME_LINE_NO AND m.SHIPMENT_ID=s.`PARENT_SHIPMENT_ID`
WHERE n.`NOTIFICATION_ID` IS NOT NULL AND n.ACTIVE AND (LENGTH(@planningUnitIds)=0 OR FIND_IN_SET(st.PLANNING_UNIT_ID,@planningUnitIds)) 
ORDER BY n.ADDRESSED DESC;
END$$

DELIMITER ;

ALTER TABLE `fasp`.`rm_erp_notification` ADD COLUMN `ERP_ORDER_ID` INT NOT NULL AFTER `CONVERSION_FACTOR`, ADD COLUMN `CHILD_SHIPMENT_ID` INT NOT NULL AFTER `ERP_ORDER_ID`; 

ALTER TABLE `fasp`.`rm_erp_notification` DROP COLUMN `ORDER_NO`, DROP COLUMN `PRIME_LINE_NO`, DROP COLUMN `SHIPMENT_ID`; 

UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT`='Estimated Receive Date' WHERE `STATIC_LABEL_LANGUAGE_ID`='4841'; 
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT`='Date de réception estimée' WHERE `STATIC_LABEL_LANGUAGE_ID`='4842'; 
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT`='Fecha estimada de recepción' WHERE `STATIC_LABEL_LANGUAGE_ID`='4843'; 
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT`='Data Estimada de Recebimento' WHERE `STATIC_LABEL_LANGUAGE_ID`='4844'; 
