INSERT INTO `fasp`.`us_can_create_role`(`ROLE_ID`,`CAN_CREATE_ROLE`) VALUES ( 'ROLE_APPLICATION_ADMIN','ROLE_REPORT_USER');
INSERT INTO `fasp`.`us_can_create_role`(`ROLE_ID`,`CAN_CREATE_ROLE`) VALUES ( 'ROLE_REALM_ADMIN','ROLE_REPORT_USER'); 
DELETE FROM `fasp`.`us_role_business_function` WHERE `ROLE_BUSINESS_FUNCTION_ID`='290'; 