CREATE TABLE IF NOT EXISTS `rm_procurement_agent_planning_unit_program` (
  `PROCUREMENT_AGENT_PLANNING_UNIT_PROGRAM_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `PROCUREMENT_AGENT_PLANNING_UNIT_ID` INT(10) UNSIGNED NOT NULL,
  `PROGRAM_ID` INT(10) UNSIGNED NOT NULL,
  `PRICE` DECIMAL(14,4) NOT NULL,
  `ACTIVE` TINYINT(1) UNSIGNED NOT NULL,
  `CREATED_BY` INT(10) UNSIGNED NOT NULL,
  `CREATED_DATE` DATETIME NOT NULL,
  `LAST_MODIFIED_BY` INT(10) UNSIGNED NOT NULL,
  `LAST_MODIFIED_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`PROCUREMENT_AGENT_PLANNING_UNIT_PROGRAM_ID`),
  INDEX `fk_rm_papup_idx_PROCUREMENT_AGENT_PLANNING_UNIT_ID` (`PROCUREMENT_AGENT_PLANNING_UNIT_ID` ASC),
  INDEX `fk_rm_papup_idx_PROGRAM_ID` (`PROGRAM_ID` ASC),
  INDEX `fk_rm_papup_idx_CREATED_BY` (`CREATED_BY` ASC),
  INDEX `fk_rm_papup_idx_LAST_MODIFIED_BY` (`LAST_MODIFIED_BY` ASC),
  UNIQUE INDEX `unq_rm_papu_PROCUREMENT_AGENT_PLANNING_UNIT_ID_PROGRAM_ID` (`PROCUREMENT_AGENT_PLANNING_UNIT_ID` ASC, `PROGRAM_ID` ASC),
  CONSTRAINT `fk_rm_papup_rm_procurement_PROCUREMENT_AGENT_PLANNING_UNIT_ID`
    FOREIGN KEY (`PROCUREMENT_AGENT_PLANNING_UNIT_ID`)
    REFERENCES `fasp`.`rm_procurement_agent_planning_unit` (`PROCUREMENT_AGENT_PLANNING_UNIT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rm_papup_rm_program_PROGRAM_ID`
    FOREIGN KEY (`PROGRAM_ID`)
    REFERENCES `fasp`.`rm_program` (`PROGRAM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rm_papup_us_user_CREATED_BY`
    FOREIGN KEY (`CREATED_BY`)
    REFERENCES `fasp`.`us_user` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rm_papup_us_user_LAST_MODIFIED_BY`
    FOREIGN KEY (`LAST_MODIFIED_BY`)
    REFERENCES `fasp`.`us_user` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;