/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  altius
 * Created: 20-Aug-2021
 */

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE `fasp`.`rm_organisation_type`;
SET FOREIGN_KEY_CHECKS = 1;


INSERT INTO `fasp`.`ap_label`(`LABEL_ID`,`LABEL_EN`,`LABEL_FR`,`LABEL_SP`,`LABEL_PR`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`,`SOURCE_ID`) VALUES ( NULL,'Govt',NULL,NULL,NULL,'1',NOW(),'1',NOW(),'1'); 
SELECT MAX(l.LABEL_ID) INTO @MAX FROM ap_label l ;
INSERT INTO `fasp`.`rm_organisation_type`(`ORGANISATION_TYPE_ID`,`REALM_ID`,`LABEL_ID`,`ACTIVE`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`) VALUES ( NULL,'1',@MAX,'1','1',NOW(),'1',NOW()); 

INSERT INTO `fasp`.`ap_label`(`LABEL_ID`,`LABEL_EN`,`LABEL_FR`,`LABEL_SP`,`LABEL_PR`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`,`SOURCE_ID`) VALUES ( NULL,'Intl. donor',NULL,NULL,NULL,'1',NOW(),'1',NOW(),'1'); 
SELECT MAX(l.LABEL_ID) INTO @MAX FROM ap_label l ;
INSERT INTO `fasp`.`rm_organisation_type`(`ORGANISATION_TYPE_ID`,`REALM_ID`,`LABEL_ID`,`ACTIVE`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`) VALUES ( NULL,'1',@MAX,'1','1',NOW(),'1',NOW()); 

INSERT INTO `fasp`.`ap_label`(`LABEL_ID`,`LABEL_EN`,`LABEL_FR`,`LABEL_SP`,`LABEL_PR`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`,`SOURCE_ID`) VALUES ( NULL,'CMS',NULL,NULL,NULL,'1',NOW(),'1',NOW(),'1'); 
SELECT MAX(l.LABEL_ID) INTO @MAX FROM ap_label l ;
INSERT INTO `fasp`.`rm_organisation_type`(`ORGANISATION_TYPE_ID`,`REALM_ID`,`LABEL_ID`,`ACTIVE`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`) VALUES ( NULL,'1',@MAX,'1','1',NOW(),'1',NOW()); 

INSERT INTO `fasp`.`ap_label`(`LABEL_ID`,`LABEL_EN`,`LABEL_FR`,`LABEL_SP`,`LABEL_PR`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`,`SOURCE_ID`) VALUES ( NULL,'TBD',NULL,NULL,NULL,'1',NOW(),'1',NOW(),'1'); 
SELECT MAX(l.LABEL_ID) INTO @MAX FROM ap_label l ;
INSERT INTO `fasp`.`rm_organisation_type`(`ORGANISATION_TYPE_ID`,`REALM_ID`,`LABEL_ID`,`ACTIVE`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`) VALUES ( NULL,'1',@MAX,'1','1',NOW(),'1',NOW()); 

INSERT INTO `fasp`.`ap_label`(`LABEL_ID`,`LABEL_EN`,`LABEL_FR`,`LABEL_SP`,`LABEL_PR`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`,`SOURCE_ID`) VALUES ( NULL,'SMO',NULL,NULL,NULL,'1',NOW(),'1',NOW(),'1'); 
SELECT MAX(l.LABEL_ID) INTO @MAX FROM ap_label l ;
INSERT INTO `fasp`.`rm_organisation_type`(`ORGANISATION_TYPE_ID`,`REALM_ID`,`LABEL_ID`,`ACTIVE`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`) VALUES ( NULL,'1',@MAX,'1','1',NOW(),'1',NOW()); 












/*[9:04:17 PM][ 7 ms]*/ UPDATE `fasp`.`rm_organisation` SET `ORGANISATION_TYPE_ID`='1' WHERE `ORGANISATION_ID`='1'; 
/*[9:04:20 PM][ 7 ms]*/ UPDATE `fasp`.`rm_organisation` SET `ORGANISATION_TYPE_ID`='1' WHERE `ORGANISATION_ID`='2'; 
/*[9:04:26 PM][ 6 ms]*/ UPDATE `fasp`.`rm_organisation` SET `ORGANISATION_TYPE_ID`='2' WHERE `ORGANISATION_ID`='3'; 
/*[9:04:37 PM][ 7 ms]*/ UPDATE `fasp`.`rm_organisation` SET `ORGANISATION_TYPE_ID`='2' WHERE `ORGANISATION_ID`='4'; 
/*[9:04:45 PM][ 7 ms]*/ UPDATE `fasp`.`rm_organisation` SET `ORGANISATION_TYPE_ID`='3' WHERE `ORGANISATION_ID`='5'; 
/*[9:04:52 PM][ 7 ms]*/ UPDATE `fasp`.`rm_organisation` SET `ORGANISATION_TYPE_ID`='3' WHERE `ORGANISATION_ID`='6'; 
/*[9:05:02 PM][ 7 ms]*/ UPDATE `fasp`.`rm_organisation` SET `ORGANISATION_TYPE_ID`='1' WHERE `ORGANISATION_ID`='7'; 
/*[9:05:14 PM][ 7 ms]*/ UPDATE `fasp`.`rm_organisation` SET `ORGANISATION_TYPE_ID`='1' WHERE `ORGANISATION_ID`='8'; 
/*[9:05:20 PM][ 6 ms]*/ UPDATE `fasp`.`rm_organisation` SET `ORGANISATION_TYPE_ID`='1' WHERE `ORGANISATION_ID`='9'; 
/*[9:05:27 PM][ 7 ms]*/ UPDATE `fasp`.`rm_organisation` SET `ORGANISATION_TYPE_ID`='4' WHERE `ORGANISATION_ID`='10'; 
/*[9:05:39 PM][ 7 ms]*/ UPDATE `fasp`.`rm_organisation` SET `ORGANISATION_TYPE_ID`='2' WHERE `ORGANISATION_ID`='11'; 
/*[9:05:46 PM][ 8 ms]*/ UPDATE `fasp`.`rm_organisation` SET `ORGANISATION_TYPE_ID`='5' WHERE `ORGANISATION_ID`='12'; 
/*[9:05:51 PM][ 6 ms]*/ UPDATE `fasp`.`rm_organisation` SET `ORGANISATION_TYPE_ID`='2' WHERE `ORGANISATION_ID`='13'; 

