ALTER TABLE `ap_problem` 
    ADD COLUMN `ACTUAL_CONSUMPTION_TRIGGER` TINYINT(1) NOT NULL DEFAULT 0 AFTER ACTION_LABEL_ID, 
    ADD COLUMN `FORECASTED_CONSUMPTION_TRIGGER` TINYINT(1) NOT NULL DEFAULT 0 AFTER ACTUAL_CONSUMPTION_TRIGGER,
    ADD COLUMN `INVENTORY_TRIGGER` TINYINT(1) NOT NULL DEFAULT 0 AFTER FORECASTED_CONSUMPTION_TRIGGER,
    ADD COLUMN `ADJUSTMENT_TRIGGER` TINYINT(1) NOT NULL DEFAULT 0 AFTER INVENTORY_TRIGGER,
    ADD COLUMN `SHIPMENT_TRIGGER` TINYINT(1) NOT NULL DEFAULT 0 AFTER ADJUSTMENT_TRIGGER;
    
UPDATE `ap_problem` SET ACTUAL_CONSUMPTION_TRIGGER=1, FORECASTED_CONSUMPTION_TRIGGER=0, INVENTORY_TRIGGER=0, ADJUSTMENT_TRIGGER=0, SHIPMENT_TRIGGER=0 WHERE PROBLEM_ID=1;
UPDATE `ap_problem` SET ACTUAL_CONSUMPTION_TRIGGER=0, FORECASTED_CONSUMPTION_TRIGGER=0, INVENTORY_TRIGGER=1, ADJUSTMENT_TRIGGER=0, SHIPMENT_TRIGGER=0 WHERE PROBLEM_ID=2;
UPDATE `ap_problem` SET ACTUAL_CONSUMPTION_TRIGGER=0, FORECASTED_CONSUMPTION_TRIGGER=0, INVENTORY_TRIGGER=0, ADJUSTMENT_TRIGGER=0, SHIPMENT_TRIGGER=1 WHERE PROBLEM_ID=3;
UPDATE `ap_problem` SET ACTUAL_CONSUMPTION_TRIGGER=0, FORECASTED_CONSUMPTION_TRIGGER=0, INVENTORY_TRIGGER=0, ADJUSTMENT_TRIGGER=0, SHIPMENT_TRIGGER=1 WHERE PROBLEM_ID=4;
UPDATE `ap_problem` SET ACTUAL_CONSUMPTION_TRIGGER=0, FORECASTED_CONSUMPTION_TRIGGER=1, INVENTORY_TRIGGER=0, ADJUSTMENT_TRIGGER=0, SHIPMENT_TRIGGER=0 WHERE PROBLEM_ID=8;
UPDATE `ap_problem` SET ACTUAL_CONSUMPTION_TRIGGER=0, FORECASTED_CONSUMPTION_TRIGGER=1, INVENTORY_TRIGGER=0, ADJUSTMENT_TRIGGER=0, SHIPMENT_TRIGGER=0 WHERE PROBLEM_ID=10;
UPDATE `ap_problem` SET ACTUAL_CONSUMPTION_TRIGGER=0, FORECASTED_CONSUMPTION_TRIGGER=1, INVENTORY_TRIGGER=0, ADJUSTMENT_TRIGGER=0, SHIPMENT_TRIGGER=0 WHERE PROBLEM_ID=14;
UPDATE `ap_problem` SET ACTUAL_CONSUMPTION_TRIGGER=0, FORECASTED_CONSUMPTION_TRIGGER=1, INVENTORY_TRIGGER=0, ADJUSTMENT_TRIGGER=0, SHIPMENT_TRIGGER=0 WHERE PROBLEM_ID=15;
UPDATE `ap_problem` SET ACTUAL_CONSUMPTION_TRIGGER=0, FORECASTED_CONSUMPTION_TRIGGER=1, INVENTORY_TRIGGER=0, ADJUSTMENT_TRIGGER=0, SHIPMENT_TRIGGER=0 WHERE PROBLEM_ID=16;
UPDATE `ap_problem` SET ACTUAL_CONSUMPTION_TRIGGER=1, FORECASTED_CONSUMPTION_TRIGGER=1, INVENTORY_TRIGGER=1, ADJUSTMENT_TRIGGER=1, SHIPMENT_TRIGGER=1 WHERE PROBLEM_ID=17;
UPDATE `ap_problem` SET ACTUAL_CONSUMPTION_TRIGGER=1, FORECASTED_CONSUMPTION_TRIGGER=1, INVENTORY_TRIGGER=1, ADJUSTMENT_TRIGGER=1, SHIPMENT_TRIGGER=1 WHERE PROBLEM_ID=18;
UPDATE `ap_problem` SET ACTUAL_CONSUMPTION_TRIGGER=1, FORECASTED_CONSUMPTION_TRIGGER=1, INVENTORY_TRIGGER=1, ADJUSTMENT_TRIGGER=1, SHIPMENT_TRIGGER=1 WHERE PROBLEM_ID=19;
UPDATE `ap_problem` SET ACTUAL_CONSUMPTION_TRIGGER=1, FORECASTED_CONSUMPTION_TRIGGER=1, INVENTORY_TRIGGER=1, ADJUSTMENT_TRIGGER=1, SHIPMENT_TRIGGER=1 WHERE PROBLEM_ID=20;
UPDATE `ap_problem` SET ACTUAL_CONSUMPTION_TRIGGER=1, FORECASTED_CONSUMPTION_TRIGGER=1, INVENTORY_TRIGGER=1, ADJUSTMENT_TRIGGER=1, SHIPMENT_TRIGGER=1 WHERE PROBLEM_ID=21;
UPDATE `ap_problem` SET ACTUAL_CONSUMPTION_TRIGGER=1, FORECASTED_CONSUMPTION_TRIGGER=1, INVENTORY_TRIGGER=1, ADJUSTMENT_TRIGGER=1, SHIPMENT_TRIGGER=1 WHERE PROBLEM_ID=23;
UPDATE `ap_problem` SET ACTUAL_CONSUMPTION_TRIGGER=1, FORECASTED_CONSUMPTION_TRIGGER=1, INVENTORY_TRIGGER=1, ADJUSTMENT_TRIGGER=1, SHIPMENT_TRIGGER=1 WHERE PROBLEM_ID=24;



USE `fasp`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `faspUser`@`%` 
    SQL SECURITY DEFINER
VIEW `vw_problem` AS
    SELECT 
        `pr`.`PROBLEM_ID` AS `PROBLEM_ID`,
        `pr`.`PROBLEM_CATEGORY_ID` AS `PROBLEM_CATEGORY_ID`,
        `pr`.`LABEL_ID` AS `LABEL_ID`,
        `pr`.`ACTION_URL` AS `ACTION_URL`,
        `pr`.`ACTION_LABEL_ID` AS `ACTION_LABEL_ID`,
        `pr`.`ACTUAL_CONSUMPTION_TRIGGER` AS `ACTUAL_CONSUMPTION_TRIGGER`,
        `pr`.`FORECASTED_CONSUMPTION_TRIGGER` AS `FORECASTED_CONSUMPTION_TRIGGER`,
        `pr`.`INVENTORY_TRIGGER` AS `INVENTORY_TRIGGER`,
        `pr`.`ADJUSTMENT_TRIGGER` AS `ADJUSTMENT_TRIGGER`,
        `pr`.`SHIPMENT_TRIGGER` AS `SHIPMENT_TRIGGER`,
        `pr`.`ACTIVE` AS `ACTIVE`,
        `pr`.`CREATED_BY` AS `CREATED_BY`,
        `pr`.`CREATED_DATE` AS `CREATED_DATE`,
        `pr`.`LAST_MODIFIED_BY` AS `LAST_MODIFIED_BY`,
        `pr`.`LAST_MODIFIED_DATE` AS `LAST_MODIFIED_DATE`,
        `prl`.`LABEL_EN` AS `LABEL_EN`,
        `prl`.`LABEL_FR` AS `LABEL_FR`,
        `prl`.`LABEL_SP` AS `LABEL_SP`,
        `prl`.`LABEL_PR` AS `LABEL_PR`,
        `pral`.`LABEL_EN` AS `ACTION_LABEL_EN`,
        `pral`.`LABEL_FR` AS `ACTION_LABEL_FR`,
        `pral`.`LABEL_SP` AS `ACTION_LABEL_SP`,
        `pral`.`LABEL_PR` AS `ACTION_LABEL_PR`
    FROM
        ((`ap_problem` `pr`
        LEFT JOIN `ap_label` `prl` ON ((`pr`.`LABEL_ID` = `prl`.`LABEL_ID`)))
        LEFT JOIN `ap_label` `pral` ON ((`pr`.`ACTION_LABEL_ID` = `pral`.`LABEL_ID`)));

update rm_realm_problem rrp set rrp.LAST_MODIFIED_DATE=now();


INSERT INTO `ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.qpl.calculate','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Calculate');-- en
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Calculer');-- fr
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Calcular');-- sp
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Calcular');-- pr


INSERT INTO `ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.qpl.recalculate','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Recalculate');-- en
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Recalcular');-- fr
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Recalcular');-- sp
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Recalcular');-- pr