DROP TABLE IF EXISTS rm_procurement_agent_planning_unit_program;
CREATE TABLE IF NOT EXISTS `rm_program_planning_unit_procurement_agent` (
  `PROGRAM_PLANNING_UNIT_PROCUREMENT_AGENT_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `PROGRAM_PLANNING_UNIT_ID` INT(10) UNSIGNED NOT NULL,
  `PROCUREMENT_AGENT_ID` INT(10) UNSIGNED NOT NULL,
  `PRICE` DECIMAL(14,4) NOT NULL,
  `ACTIVE` TINYINT(1) UNSIGNED NOT NULL,
  `CREATED_BY` INT(10) UNSIGNED NOT NULL,
  `CREATED_DATE` DATETIME NOT NULL,
  `LAST_MODIFIED_BY` INT(10) UNSIGNED NOT NULL,
  `LAST_MODIFIED_DATE` DATETIME NOT NULL,
  PRIMARY KEY (`PROGRAM_PLANNING_UNIT_PROCUREMENT_AGENT_ID`),
  INDEX `fk_rm_papup_idx_PROGRAM_PLANNING_UNIT_ID` (`PROGRAM_PLANNING_UNIT_ID` ASC),
  INDEX `fk_rm_papup_idx_PROCUREMENT_AGENT_ID` (`PROCUREMENT_AGENT_ID` ASC),
  INDEX `fk_rm_papup_idx_CREATED_BY` (`CREATED_BY` ASC),
  INDEX `fk_rm_papup_idx_LAST_MODIFIED_BY` (`LAST_MODIFIED_BY` ASC),
  UNIQUE INDEX `unq_rm_papu_PROGRAM_PLANNING_UNIT_ID_PROCUREMENT_AGENT_ID` (`PROGRAM_PLANNING_UNIT_ID` ASC, `PROCUREMENT_AGENT_ID` ASC),
  CONSTRAINT `fk_rm_papup_PROGRAM_PLANNING_UNIT_ID`
    FOREIGN KEY (`PROGRAM_PLANNING_UNIT_ID`)
    REFERENCES `fasp`.`rm_program_planning_unit` (`PROGRAM_PLANNING_UNIT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rm_papup_PROCUREMENT_AGENT_ID`
    FOREIGN KEY (`PROCUREMENT_AGENT_ID`)
    REFERENCES `fasp`.`rm_procurement_agent` (`PROCUREMENT_AGENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rm_papup_us_user_CREATED_BY`
    FOREIGN KEY (`CREATED_BY`)
    REFERENCES `fasp`.`us_user` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rm_papup_us_user_LAST_MODIFIED_BY`
    FOREIGN KEY (`LAST_MODIFIED_BY`)
    REFERENCES `fasp`.`us_user` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;        