ALTER TABLE `fasp`.`rm_program_planning_unit` 
DROP COLUMN `LAST_MODIFIED_DATE`,
ADD COLUMN `PLAN_BASED_ON` INT UNSIGNED NOT NULL COMMENT '1- MoS , 2- Qty' AFTER `MONTHS_IN_PAST_FOR_AMC`,
ADD COLUMN `MIN_QTY` INT UNSIGNED NOT NULL AFTER `PLAN_BASED_ON`,
ADD COLUMN `DISTRIBUTION_LEAD_TIME` DOUBLE(6,2) UNSIGNED NOT NULL AFTER `MIN_QTY`;


