INSERT INTO us_can_create_role values ('ROLE_INTERNAL_USER', 'ROLE_REALM_ADMIN'), ('ROLE_INTERNAL_USER', 'ROLE_INTERNAL_USER');
INSERT INTO us_can_create_role values ('ROLE_DATASET_ADMIN', 'ROLE_DATASET_USER');
INSERT INTO us_can_create_role values ('ROLE_REALM_ADMIN', 'ROLE_DATASET_ADMIN'), ('ROLE_REALM_ADMIN', 'ROLE_DATASET_USER'), ('ROLE_REALM_ADMIN', 'ROLE_FORECAST_VIEWER');
