ALTER TABLE `fasp`.`rm_program_planning_unit` 
ADD COLUMN `PLAN_BASED_ON` INT UNSIGNED NOT NULL COMMENT '1- MoS , 2- Qty' AFTER `MONTHS_IN_PAST_FOR_AMC`,
ADD COLUMN `MIN_QTY` INT UNSIGNED NULL AFTER `PLAN_BASED_ON`,
ADD COLUMN `DISTRIBUTION_LEAD_TIME` DOUBLE(6,2) UNSIGNED NULL AFTER `MIN_QTY`,
CHANGE COLUMN `MIN_MONTHS_OF_STOCK` `MIN_MONTHS_OF_STOCK` INT UNSIGNED NULL ;


