INSERT INTO fasp.ap_label (LABEL_ID, LABEL_EN, LABEL_FR, LABEL_SP, LABEL_PR, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, SOURCE_ID) VALUES (null, 'Other', 'Autre', 'Otra', 'Outra', 1, now(), 1, now(), 34);
SELECT MAX(l.LABEL_ID) INTO @MAX FROM ap_label l ;
INSERT INTO fasp.ap_problem_category(PROBLEM_CATEGORY_ID,LABEL_ID)VALUES (4, @MAX);

INSERT INTO fasp.ap_label (LABEL_ID, LABEL_EN, LABEL_FR, LABEL_SP, LABEL_PR, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, SOURCE_ID) VALUES (null, 'Manual problem', null, null, null, 1, now(), 1, now(), 22);
SELECT LAST_INSERT_ID() INTO @MAX;
INSERT INTO fasp.ap_label (LABEL_ID, LABEL_EN, LABEL_FR, LABEL_SP, LABEL_PR, CREATED_BY, CREATED_DATE, LAST_MODIFIED_BY, LAST_MODIFIED_DATE, SOURCE_ID) VALUES (null, 'Manual problem', null, null, null, 1, now(), 1, now(), 23);
SELECT LAST_INSERT_ID() INTO @MAX2;
INSERT INTO `fasp`.`ap_problem` (
    `PROBLEM_ID`,`LABEL_ID`, `PROBLEM_CATEGORY_ID`, `ACTION_URL`, `ACTION_LABEL_ID`, `ACTUAL_CONSUMPTION_TRIGGER`,
    `FORECASTED_CONSUMPTION_TRIGGER`, `INVENTORY_TRIGGER`, `ADJUSTMENT_TRIGGER`, `SHIPMENT_TRIGGER`, `ACTIVE`,
    `CREATED_BY`, `CREATED_DATE`, `LAST_MODIFIED_BY`, `LAST_MODIFIED_DATE`)
VALUES (
    26,@MAX, 4, '',@MAX2, 0,
    0, 0, 0, 0, 1,
    1, now(), 1, now());


INSERT INTO `fasp`.`rm_realm_problem` (`REALM_PROBLEM_ID`,`REALM_ID`, `PROBLEM_ID`, `PROBLEM_TYPE_ID`, `CRITICALITY_ID`, `ACTIVE`, `CREATED_BY`, `CREATED_DATE`, `LAST_MODIFIED_BY`, `LAST_MODIFIED_DATE`) VALUES ('25', '1', '26', '2', '1', '3', '1', now(), '1', now());
