ALTER TABLE `fasp`.`rm_realm` 
ADD COLUMN `MIN_COUNT_FOR_MODE` INT UNSIGNED NULL AFTER `INVENTORY_MONTHS_IN_PAST`,
ADD COLUMN `MIN_PERC_FOR_MODE` DECIMAL(10,2) UNSIGNED NULL AFTER `MIN_COUNT_FOR_MODE`;
