ALTER TABLE `fasp`.`rm_forecast_tree_node` ADD COLUMN `COLLAPSED` TINYINT NOT NULL DEFAULT 0 AFTER `LABEL_ID`;
ALTER TABLE `fasp`.`rm_tree_template_node` ADD COLUMN `COLLAPSED` TINYINT NOT NULL DEFAULT 0 AFTER `LABEL_ID`;

