ALTER TABLE `fasp`.`rm_supply_plan_amc` 
CHANGE COLUMN `AMC` `AMC` DECIMAL(24,8) NULL DEFAULT NULL ,
CHANGE COLUMN `MOS` `MOS` DECIMAL(24,8) NULL DEFAULT NULL ,
CHANGE COLUMN `MOS_WPS` `MOS_WPS` DECIMAL(24,8) NULL DEFAULT NULL ,
CHANGE COLUMN `MIN_STOCK_QTY` `MIN_STOCK_QTY` DECIMAL(24,8) NULL DEFAULT NULL ,
CHANGE COLUMN `MIN_STOCK_MOS` `MIN_STOCK_MOS` DECIMAL(24,8) NULL DEFAULT NULL ,
CHANGE COLUMN `MAX_STOCK_QTY` `MAX_STOCK_QTY` DECIMAL(24,8) NULL DEFAULT NULL ,
CHANGE COLUMN `MAX_STOCK_MOS` `MAX_STOCK_MOS` DECIMAL(24,8) NULL DEFAULT NULL ;


