ALTER TABLE `fasp`.`rm_program_planning_unit_procurement_agent` 
ADD COLUMN `SEA_FREIGHT_PERC` DECIMAL(5,2) NULL AFTER `PRICE`,
ADD COLUMN `AIR_FREIGHT_PERC` DECIMAL(5,2) NULL AFTER `SEA_FREIGHT_PERC`,
ADD COLUMN `ROAD_FREIGHT_PERC` DECIMAL(5,2) NULL AFTER `AIR_FREIGHT_PERC`,
ADD COLUMN `LOCAL_PROCUREMENT_LEAD_TIME` DECIMAL(4,2) NULL AFTER `ROAD_FREIGHT_PERC`;


ALTER TABLE `fasp`.`rm_program_planning_unit_procurement_agent` 
ADD COLUMN `PLANNED_TO_SUBMITTED_LEAD_TIME` DECIMAL(4,2) DEFAULT NULL AFTER `ROAD_FREIGHT_PERC`,
ADD COLUMN `SUBMITTED_TO_APPROVED_LEAD_TIME` decimal(4,2) DEFAULT NULL AFTER `PLANNED_TO_SUBMITTED_LEAD_TIME`,
ADD COLUMN `APPROVED_TO_SHIPPED_LEAD_TIME` decimal(4,2) DEFAULT NULL AFTER `SUBMITTED_TO_APPROVED_LEAD_TIME`,
ADD COLUMN `SHIPPED_TO_ARRIVED_BY_AIR_LEAD_TIME` decimal(4,2) DEFAULT NULL AFTER `APPROVED_TO_SHIPPED_LEAD_TIME`,
ADD COLUMN `SHIPPED_TO_ARRIVED_BY_SEA_LEAD_TIME` decimal(4,2) DEFAULT NULL AFTER `SHIPPED_TO_ARRIVED_BY_AIR_LEAD_TIME`,
ADD COLUMN `SHIPPED_TO_ARRIVED_BY_ROAD_LEAD_TIME` decimal(4,2) DEFAULT NULL AFTER `SHIPPED_TO_ARRIVED_BY_SEA_LEAD_TIME`,
ADD COLUMN `ARRIVED_TO_DELIVERED_LEAD_TIME` decimal(4,2) DEFAULT NULL AFTER `SHIPPED_TO_ARRIVED_BY_ROAD_LEAD_TIME`;