ALTER TABLE `fasp`.`rm_program_planning_unit_procurement_agent` 
ADD COLUMN `SEA_FREIGHT_PERC` DECIMAL(5,2) NULL AFTER `PRICE`,
ADD COLUMN `AIR_FREIGHT_PERC` DECIMAL(5,2) NULL AFTER `SEA_FREIGHT_PERC`,
ADD COLUMN `ROAD_FREIGHT_PERC` DECIMAL(5,2) NULL AFTER `AIR_FREIGHT_PERC`,
ADD COLUMN `LOCAL_PROCUREMENT_LEAD_TIME` DECIMAL(4,2) NULL AFTER `ROAD_FREIGHT_PERC`;
