ALTER TABLE `fasp`.`rm_program_planning_unit` 
ADD COLUMN `FORECAST_ERROR_THRESHOLD` DECIMAL(10,4) NULL AFTER `DISTRIBUTION_LEAD_TIME`,
ADD COLUMN `NOTES` TEXT NULL AFTER `FORECAST_ERROR_THRESHOLD`;

UPDATE `rm_program_planning_unit` ppu SET ppu.FORECAST_ERROR_THRESHOLD = 0.50;

