CREATE TABLE IF NOT EXISTS `rm_procurement_agent_forecasting_unit` ( 
  `FORECASTING_UNIT_PROCUREMENT_AGENT_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT, 
  `FORECASTING_UNIT_ID` INT(10) UNSIGNED NOT NULL, 
  `PROCUREMENT_AGENT_ID` INT(10) UNSIGNED NOT NULL, 
  `SKU_CODE` VARCHAR(9) NOT NULL, 
  PRIMARY KEY (`FORECASTING_UNIT_PROCUREMENT_AGENT_ID`), 
  KEY `FK_rm_procurement_agent_forecasting_unit_fu` (`FORECASTING_UNIT_ID`), 
  KEY `FK_rm_procurement_agent_forecasting_unit_pa` (`PROCUREMENT_AGENT_ID`), 
  CONSTRAINT `FK_rm_procurement_agent_forecasting_unit_fu` FOREIGN KEY (`FORECASTING_UNIT_ID`) REFERENCES `rm_forecasting_unit` (`FORECASTING_UNIT_ID`), 
  CONSTRAINT `FK_rm_procurement_agent_forecasting_unit_pa` FOREIGN KEY (`PROCUREMENT_AGENT_ID`) REFERENCES `rm_procurement_agent` (`PROCUREMENT_AGENT_ID`) 
) ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE `fasp`.`rm_procurement_agent_forecasting_unit` 
CHANGE COLUMN `FORECASTING_UNIT_PROCUREMENT_AGENT_ID` `PROCUREMENT_AGENT_FORECASTING_UNIT_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT ;

ALTER TABLE `fasp`.`rm_procurement_agent_forecasting_unit` 
ADD COLUMN `ACTIVE` TINYINT(1) UNSIGNED NOT NULL AFTER `SKU_CODE`,
ADD COLUMN `CREATED_BY` INT UNSIGNED NOT NULL AFTER `ACTIVE`,
ADD COLUMN `CREATED_DATE` DATETIME NOT NULL AFTER `CREATED_BY`,
ADD COLUMN `LAST_MODIFIED_BY` INT UNSIGNED NOT NULL AFTER `CREATED_DATE`,
ADD COLUMN `LAST_MODIFIED_DATE` DATETIME NOT NULL AFTER `LAST_MODIFIED_BY`,
ADD INDEX `fk_rm_procurement_agent_forecasting_unit_cb_idx` (`CREATED_BY` ASC) VISIBLE,
ADD INDEX `fk_rm_procurement_agent_forecasting_unit_lmb_idx` (`LAST_MODIFIED_BY` ASC) VISIBLE;
;
ALTER TABLE `fasp`.`rm_procurement_agent_forecasting_unit` 
ADD CONSTRAINT `fk_rm_procurement_agent_forecasting_unit_cb`
  FOREIGN KEY (`CREATED_BY`)
  REFERENCES `fasp`.`us_user` (`USER_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `fk_rm_procurement_agent_forecasting_unit_lmb`
  FOREIGN KEY (`LAST_MODIFIED_BY`)
  REFERENCES `fasp`.`us_user` (`USER_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
