INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.supplyPlan.recommendToChangeFreightCost','1'); 
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Recommended to change the freight cost');-- en
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Il est recommandé de modifier le coût du fret');-- fr
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Se recomienda cambiar el costo del flete');-- sp
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Recomendado para alterar o custo do frete');-- pr
INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.dataentry.autogeneratedFreight','1'); 
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Autogenerated freight cost');-- en
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Coût du fret généré automatiquement');-- fr
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Costo de flete generado automáticamente');-- sp
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Custo do frete gerado automaticamente');-- pr