ALTER TABLE `fasp`.`rm_forecast_tree_node_data_fu` ADD COLUMN `ONE_TIME_DISPENSING` TINYINT(3) UNSIGNED DEFAULT '1' NOT NULL AFTER `ONE_TIME_USAGE`; 

ALTER TABLE `fasp`.`rm_tree_template_node_data_fu` ADD COLUMN `ONE_TIME_DISPENSING` TINYINT(3) UNSIGNED DEFAULT '1' NOT NULL AFTER `ONE_TIME_USAGE`; 