INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.tooltip.procurementAgentAcl','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'This shows the procurement agent(s) the user is associated with and this field is linked to the Procurement Agent selection in the top half of this screen. You can limit/grant access to a particular Procurement Agent from accessing your program by removing/adding them from the Procurement Agent selection at the top of this screen. Note that the Procurement Agent selection also dictates which dropdowns will appear in your shipment data entry screens.'); -- en
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Ce champ indique le ou les agents d\'approvisionnement auxquels l\'utilisateur est associé. Il est lié à la sélection d\'agents d\'approvisionnement dans la moitié supérieure de l\'écran. Vous pouvez limiter ou autoriser l\'accès à votre programme à un agent d\'approvisionnement spécifique en le supprimant ou en l\'ajoutant de la sélection d\'agents d\'approvisionnement en haut de l\'écran. Notez que la sélection d\'agents d\'approvisionnement détermine également les menus déroulants qui apparaîtront dans vos écrans de saisie des données d\'expédition.'); -- fr
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Este campo muestra el/los agente(s) de compras con los que está asociado el usuario y está vinculado a la selección de Agente de Compras en la parte superior de esta pantalla. Puede restringir o conceder acceso a un Agente de Compras específico a su programa eliminándolo o agregándolo en la selección de Agente de Compras en la parte superior de esta pantalla. Tenga en cuenta que la selección de Agente de Compras también determina los menús desplegables que aparecerán en las pantallas de entrada de datos de envío.'); -- sp 
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Isso mostra o(s) agente(s) de compras ao(s) qual(is) o usuário está associado(s). Este campo está vinculado à seleção do Agente de Compras na metade superior desta tela. Você pode restringir/conceder acesso a um Agente de Compras específico para acessar seu programa, removendo-o/adicionando-o da seleção do Agente de Compras na parte superior desta tela. Observe que a seleção do Agente de Compras também determina quais menus suspensos serão exibidos nas telas de entrada de dados de remessa.'); -- pr

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.tooltip.fundingSourceAcl','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;

INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'This shows the funding source(s) the user is associated with and this field is linked to the Funding Source selection in the top half of this screen. You can limit/grant access to a particular Funding Source from accessing your program by removing/adding them from the Funding Source selection at the top of this screen. Note that the Funding Source selection also dictates which dropdowns will appear in your shipment data entry screens.'); -- en
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Ce champ affiche la ou les sources de financement auxquelles l\'utilisateur est associé. Il est lié à la sélection « Source de financement » dans la partie supérieure de l\'écran. Vous pouvez limiter ou autoriser l\'accès à votre programme à une source de financement spécifique en la supprimant ou en l\'ajoutant de la sélection « Source de financement » en haut de l\'écran. Notez que la sélection de la source de financement détermine également les menus déroulants qui apparaîtront dans vos écrans de saisie des données d\'expédition.'); -- fr
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Este campo muestra la(s) fuente(s) de financiamiento a las que está asociado el usuario y está vinculado a la selección de Fuente de Financiamiento en la parte superior de esta pantalla. Puede restringir o permitir el acceso a una fuente de financiamiento específica a su programa eliminándola o agregándola en la selección de Fuente de Financiamiento en la parte superior de esta pantalla. Tenga en cuenta que la selección de Fuente de Financiamiento también determina los menús desplegables que aparecerán en las pantallas de entrada de datos de envío.'); -- sp 
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Isso mostra a(s) fonte(s) de financiamento às quais o usuário está associado e este campo está vinculado à seleção de Fonte de Financiamento na metade superior desta tela. Você pode limitar/conceder acesso a uma Fonte de Financiamento específica para acessar seu programa, removendo-a/adicionando-a da seleção de Fonte de Financiamento na parte superior desta tela. Observe que a seleção de Fonte de Financiamento também determina quais menus suspensos aparecerão nas telas de entrada de dados de remessa.'); -- pr