INSERT INTO `ap_label`(`LABEL_EN`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`,`SOURCE_ID`) VALUES ( 'Planning Unit Draft',9,now(),9,now(),24);
INSERT INTO `us_business_function` (`BUSINESS_FUNCTION_ID`, `LABEL_ID`, `CREATED_BY`, `CREATED_DATE`, `LAST_MODIFIED_BY`, `LAST_MODIFIED_DATE`) VALUES ('ROLE_BF_PLANNING_UNIT_DRAFT', LAST_INSERT_ID(), 9, now(), 9, now());
INSERT INTO `us_role_business_function` (`ROLE_ID`, `BUSINESS_FUNCTION_ID`, `CREATED_BY`, `CREATED_DATE`, `LAST_MODIFIED_BY`, `LAST_MODIFIED_DATE`) VALUES ('ROLE_REALM_ADMIN', 'ROLE_BF_PLANNING_UNIT_DRAFT', 9, now(), 9, now());
INSERT INTO `us_role_business_function` (`ROLE_ID`, `BUSINESS_FUNCTION_ID`, `CREATED_BY`, `CREATED_DATE`, `LAST_MODIFIED_BY`, `LAST_MODIFIED_DATE`) VALUES ('ROLE_INTERNAL_USER', 'ROLE_BF_PLANNING_UNIT_DRAFT', 9, now(), 9, now());

INSERT INTO ap_security (METHOD, URL, BF) VALUES (1, '/api/planningUnit/draft', 'ROLE_BF_PLANNING_UNIT_DRAFT');

INSERT INTO `fasp`.`ap_static_label`(`STATIC_LABEL_ID`,`LABEL_CODE`,`ACTIVE`) VALUES ( NULL,'static.dashboard.planningUnitDraft','1');
SELECT MAX(l.STATIC_LABEL_ID) INTO @MAX FROM ap_static_label l ;
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,1,'Draft Planning Unit');-- en
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,2,'Unité de planification provisoire');-- fr
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,3,'Unidad de planificación preliminar');-- sp
INSERT INTO ap_static_label_languages VALUES(NULL,@MAX,4,'Unidade de planejamento provisória');-- pr

CREATE TABLE `rm_planning_unit_draft` (
  `PLANNING_UNIT_DRAFT_ID` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Id for each Planning unit draft',
  `PLANNING_UNIT_ID` int unsigned DEFAULT NULL COMMENT 'Reference to the published Planning unit',
  `ACTION` int unsigned DEFAULT NULL COMMENT 'Action to be performed on the Planning unit, 1-Ignore, 2-Merge, 3-Create',
  `TaskOrder` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `CommodityCouncil` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Subcategory` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `TracerCategory` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `ProductActive` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `ProductIDNoPack` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `ProductNameNoPack` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `ProductID` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `ProductName` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `OrderUOM` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `PackSize` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `NoofBaseUnits` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `BaseUnit` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `L5DataTrusteeCode` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `UNSPSC` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `INN` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Controlled` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Route` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Form` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `QACategory` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `QACriteria` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug1Name` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug1Abbr` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug1Qty` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug1Meas` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug1Unit` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug2Name` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug2Abbr` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug2Qty` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug2Meas` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug2Unit` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug3Name` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug3Abbr` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug3Qty` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug3Meas` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug3Unit` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug4Name` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug4Abbr` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug4Qty` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug4Meas` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Drug4Unit` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `USAIDARVTier` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `PlanningUnitMOQ` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `PlanningUnitsperPallet` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `PlanningUnitsperContainer` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `PlanningUnitVolumem3` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `PlanningUnitWeightkg` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `ItemID` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `ItemName` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Supplier` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `WeightUOM` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Weight` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `HeightUOM` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Height` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Length` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Width` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `GTIN` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Labeling` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `ItemAvailable` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `UnitsperCase` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `UnitsperPallet` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `UnitsperContainer` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `EstPrice` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Euro1` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `Euro2` varchar(250) COLLATE utf8_bin DEFAULT NULL,
  `ACTIVE` tinyint unsigned NOT NULL DEFAULT '1' COMMENT 'If True indicates this record is Active',
  `CREATED_BY` int unsigned NOT NULL COMMENT 'Created by',
  `CREATED_DATE` datetime NOT NULL COMMENT 'Created date',
  `LAST_MODIFIED_BY` int unsigned NOT NULL COMMENT 'Last Modified by',
  `LAST_MODIFIED_DATE` datetime NOT NULL COMMENT 'Last Modified date',
  PRIMARY KEY (`PLANNING_UNIT_DRAFT_ID`),
  KEY `fk_planning_unit_draft_planningUnit_idx` (`PLANNING_UNIT_ID`),
  KEY `fk_planning_unit_draft_createdBy_idx` (`CREATED_BY`),
  KEY `fk_planning_unit_draft_lastModifiedBy_idx` (`LAST_MODIFIED_BY`),
  KEY `idx_planningUnit_draft_lastModifiedDt` (`LAST_MODIFIED_DATE`),
  KEY `idxProductNameNoPack` (`ProductNameNoPack`),
  KEY `idxProductName` (`ProductName`),
  KEY `idxItemName` (`ItemName`),
  CONSTRAINT `fk_planning_unit_draft_planningUnit` FOREIGN KEY (`PLANNING_UNIT_ID`) REFERENCES `rm_planning_unit` (`PLANNING_UNIT_ID`),
  CONSTRAINT `fk_planning_unit_draft_createdBy` FOREIGN KEY (`CREATED_BY`) REFERENCES `us_user` (`USER_ID`),
  CONSTRAINT `fk_planning_unit_draft_lastModifiedBy` FOREIGN KEY (`LAST_MODIFIED_BY`) REFERENCES `us_user` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Draft table for Planning units that will be used to map a Product to a Program';