INSERT INTO `fasp`.`ap_label`(`LABEL_ID`,`LABEL_EN`,`LABEL_FR`,`LABEL_SP`,`LABEL_PR`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`,`SOURCE_ID`) VALUES ( NULL,'SP - View Program Specific Prices',NULL,NULL,NULL,'1',NOW(),'1',NOW(),'1');
SELECT MAX(l.LABEL_ID) INTO @MAX FROM ap_label l ;
INSERT INTO `fasp`.`us_business_function`(`BUSINESS_FUNCTION_ID`,`LABEL_ID`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`) VALUES ( 'ROLE_BF_VIEW_COUNTRY_SPECIFIC_PRICES',@MAX,'1',NOW(),'1',NOW());


INSERT INTO `fasp`.`us_role_business_function`(`ROLE_BUSINESS_FUNCTION_ID`,`ROLE_ID`,`BUSINESS_FUNCTION_ID`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`) VALUES ( NULL,'ROLE_PROGRAM_USER','ROLE_BF_VIEW_COUNTRY_SPECIFIC_PRICES','1',NOW(),'1',NOW());
INSERT INTO `fasp`.`us_role_business_function`(`ROLE_BUSINESS_FUNCTION_ID`,`ROLE_ID`,`BUSINESS_FUNCTION_ID`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`) VALUES ( NULL,'ROLE_REPORT_USER','ROLE_BF_VIEW_COUNTRY_SPECIFIC_PRICES','1',NOW(),'1',NOW());

insert into ap_security values (null,2,'/api/programAndPlanningUnit/programs','ROLE_BF_VIEW_COUNTRY_SPECIFIC_PRICES');
insert into ap_security values (null,2,'/api/program/planningUnit/procurementAgent','ROLE_BF_VIEW_COUNTRY_SPECIFIC_PRICES');
insert into ap_security values (null,2,'/api/program/**','ROLE_BF_VIEW_COUNTRY_SPECIFIC_PRICES');