delete u.* from us_role_business_function u where u.BUSINESS_FUNCTION_ID='ROLE_BF_LIST_PROGRAM_PRODUCT';
INSERT INTO `fasp`.`us_role_business_function`(`ROLE_BUSINESS_FUNCTION_ID`,`ROLE_ID`,`BUSINESS_FUNCTION_ID`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`) VALUES ( NULL,'ROLE_PROGRAM_USER','ROLE_BF_LIST_PROGRAM_PRODUCT','1',NOW(),'1',NOW());
INSERT INTO `fasp`.`us_role_business_function`(`ROLE_BUSINESS_FUNCTION_ID`,`ROLE_ID`,`BUSINESS_FUNCTION_ID`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`) VALUES ( NULL,'ROLE_REPORT_USER','ROLE_BF_LIST_PROGRAM_PRODUCT','1',NOW(),'1',NOW());

INSERT INTO `fasp`.`ap_label`(`LABEL_ID`,`LABEL_EN`,`LABEL_FR`,`LABEL_SP`,`LABEL_PR`,`CREATED_BY`,`CREATED_DATE`,`LAST_MODIFIED_BY`,`LAST_MODIFIED_DATE`,`SOURCE_ID`) VALUES ( NULL,'SP - View Update Planning Units',NULL,NULL,NULL,'1',NOW(),'1',NOW(),'1');
SELECT MAX(l.LABEL_ID) INTO @MAX FROM ap_label l ;

desc us_business_function;
update us_business_function b set b.LABEL_ID=@MAX where b.BUSINESS_FUNCTION_ID='ROLE_BF_LIST_PROGRAM_PRODUCT';