DROP TRIGGER IF EXISTS `fasp`.`rm_erp_order_consolidated_AFTER_UPDATE`;

DELIMITER $$
USE `fasp`$$
CREATE DEFINER=`faspUser`@`%` TRIGGER `rm_erp_order_consolidated_AFTER_UPDATE` AFTER UPDATE ON `rm_erp_order_consolidated` FOR EACH ROW BEGIN
	SET @SHIPMENT_LINKING_ID = NULL;
	IF NEW.PLANNING_UNIT_SKU_CODE IS NOT NULL AND OLD.PLANNING_UNIT_SKU_CODE IS NOT NULL AND NEW.PLANNING_UNIT_SKU_CODE!=OLD.PLANNING_UNIT_SKU_CODE THEN
		SELECT sl.SHIPMENT_LINKING_ID INTO @SHIPMENT_LINKING_ID FROM rm_shipment_linking sl WHERE sl.RO_NO=NEW.RO_NO AND sl.RO_PRIME_LINE_NO=NEW.RO_PRIME_LINE_NO AND sl.ORDER_NO=NEW.ORDER_NO AND sl.PRIME_LINE_NO=NEW.PRIME_LINE_NO AND sl.ACTIVE ORDER BY sl.SHIPMENT_LINKING_ID DESC LIMIT 1;
        IF @SHIPMENT_LINKING_ID IS NOT NULL THEN
			INSERT IGNORE INTO rm_erp_notification (NOTIFICATION_TYPE_ID, ADDRESSED, ACTIVE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, SHIPMENT_LINKING_ID)             VALUES (2, 0, 1, now(), 1, now(), 1, @SHIPMENT_LINKING_ID);
        END IF;
    END IF;
    
    SET @SHIPMENT_LINKING_ID = NULL;
    IF NEW.STATUS='Cancelled' OR NEW.STATUS='CANCELLED' THEN
		SELECT sl.SHIPMENT_LINKING_ID INTO @SHIPMENT_LINKING_ID FROM rm_shipment_linking sl WHERE sl.RO_NO=NEW.RO_NO AND sl.RO_PRIME_LINE_NO=NEW.RO_PRIME_LINE_NO AND sl.ORDER_NO=NEW.ORDER_NO AND sl.PRIME_LINE_NO=NEW.PRIME_LINE_NO AND sl.ACTIVE ORDER BY sl.SHIPMENT_LINKING_ID DESC LIMIT 1;
        IF @SHIPMENT_LINKING_ID IS NOT NULL THEN
			INSERT IGNORE INTO rm_erp_notification (NOTIFICATION_TYPE_ID, ADDRESSED, ACTIVE, CREATED_DATE, CREATED_BY, LAST_MODIFIED_DATE, LAST_MODIFIED_BY, SHIPMENT_LINKING_ID)             VALUES (1, 0, 1, now(), 1, now(), 1, @SHIPMENT_LINKING_ID);
        END IF;
	END IF;
END$$
DELIMITER ;