ALTER TABLE `fasp`.`rm_forecast_tree_node_data_pu` 
CHANGE COLUMN `REFILL_MONTHS` `REFILL_MONTHS` DECIMAL(16,4) UNSIGNED NULL DEFAULT NULL COMMENT '# of moths over which refulls are taken' ,
CHANGE COLUMN `PU_PER_VISIT` `PU_PER_VISIT` DECIMAL(16,4) UNSIGNED NOT NULL ;

