UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT` = 'Use the graph below the Detailed Data table to view the adjusted data (note: graph will only update after clicking “submit”)' WHERE (`STATIC_LABEL_LANGUAGE_ID` = '266211');
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT` = 'Utiliser le graphique sous le tableau des données détaillées pour afficher les données ajustées (Remarque : le graphique ne sera mis à jour qu\'après avoir cliqué sur \"Soumettre\")' WHERE (`STATIC_LABEL_LANGUAGE_ID` = '266212');
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT` = 'Use el gráfico debajo de la tabla de datos detallados para ver los datos ajustados (nota: el gráfico solo se actualizará después de hacer clic en \"enviar\")' WHERE (`STATIC_LABEL_LANGUAGE_ID` = '266213');
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT` = 'Use o gráfico abaixo da tabela Dados Detalhados para visualizar os dados ajustados (nota: o gráfico só será atualizado após clicar em “enviar”)' WHERE (`STATIC_LABEL_LANGUAGE_ID` = '266214');


UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT` = 'For imported data, the number of stock out days is pulled in from the QAT supply plan program, if data is collected. The default value for stock out days is zero days (product assumed always in stock). The user can change this to the correct value. The calculation assumes that the days the product was stocked out would have had the same consumption rate as the rest of the time the product was in stock. The default value for number of days in a month are based on the calendar days, but users can adjust the number of days used for the stock out calculation in' WHERE (`STATIC_LABEL_LANGUAGE_ID` = '266143');
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT` = 'Pour les données importées, le nombre de jours de rupture de stock est extrait du programme de plan d\'approvisionnement QAT, si les données sont collectées. La valeur par défaut pour les jours de rupture de stock est de zéro jour (produit supposé toujours en stock). L\'utilisateur peut le remplacer par la valeur correcte. Le calcul suppose que les jours où le produit était en rupture de stock auraient eu le même taux de consommation que le reste du temps où le produit était en stock. La valeur par défaut du nombre de jours dans un mois est basée sur les jours calendaires, mais les utilisateurs peuvent ajuster le nombre de jours utilisés pour le calcul de la rupture de stock dans' WHERE (`STATIC_LABEL_LANGUAGE_ID` = '266144');
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT` = 'Para los datos importados, la cantidad de días sin existencias se extrae del programa del plan de suministro de QAT, si se recopilan datos. El valor predeterminado para los días de desabastecimiento es cero días (se supone que el producto siempre está en stock). El usuario puede cambiar esto al valor correcto. El cálculo asume que los días que el producto estuvo sin stock habría tenido el mismo índice de consumo que el resto del tiempo que el producto estuvo en stock. El valor predeterminado para la cantidad de días en un mes se basa en los días calendario, pero los usuarios pueden ajustar la cantidad de días utilizados para el cálculo de agotamiento de existencias en' WHERE (`STATIC_LABEL_LANGUAGE_ID` = '266145');
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT` = 'Para dados importados, o número de dias de falta de estoque é obtido do programa de plano de fornecimento QAT, se os dados forem coletados. O valor padrão para dias de falta de estoque é zero dias (produto assumido sempre em estoque). O usuário pode alterar isso para o valor correto. O cálculo pressupõe que os dias em que o produto ficou sem estoque teriam a mesma taxa de consumo que o restante do tempo em que o produto ficou em estoque. O valor padrão para o número de dias em um mês é baseado nos dias do calendário, mas os usuários podem ajustar o número de dias usados para o cálculo de falta de estoque em' WHERE (`STATIC_LABEL_LANGUAGE_ID` = '266146');


UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT` = 'Adjusting for missing values' WHERE (`STATIC_LABEL_LANGUAGE_ID` = '266179');
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT` = 'Ajustement des valeurs manquantes' WHERE (`STATIC_LABEL_LANGUAGE_ID` = '266180');
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT` = 'Ajuste por valores perdidos' WHERE (`STATIC_LABEL_LANGUAGE_ID` = '266181');
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT` = 'Ajustando para valores ausentes' WHERE (`STATIC_LABEL_LANGUAGE_ID` = '266182');



UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT` = 'The default value is 100% reporting every month. The user can change this to the correct value. QAT will calculate the adjusted consumption due to underreporting. The calculation assumes that facilities that did not report any consumption had the same consumption rate as the ones that did.' WHERE (`STATIC_LABEL_LANGUAGE_ID` = '266135');
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT` = 'La valeur par défaut est 100 % de rapportage chaque mois. L\'utilisateur peut le remplacer par la valeur correcte. QAT calculera la consommation ajustée en raison du sous-rapportage. Le calcul suppose que les installations qui n\'ont déclaré aucune consommation avaient le même taux de consommation que celles qui l\'ont fait.' WHERE (`STATIC_LABEL_LANGUAGE_ID` = '266136');
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT` = 'El valor predeterminado es 100% de informes cada mes. El usuario puede cambiar esto al valor correcto. QAT calculará el consumo ajustado por subregistro. El cálculo asume que las instalaciones que no reportaron ningún consumo tuvieron la misma tasa de consumo que las que lo hicieron.' WHERE (`STATIC_LABEL_LANGUAGE_ID` = '266137');
UPDATE `fasp`.`ap_static_label_languages` SET `LABEL_TEXT` = 'O valor padrão é 100% de relatórios todos os meses. O usuário pode alterar isso para o valor correto. A QAT calculará o consumo ajustado devido à subnotificação. O cálculo assume que as instalações que não relataram nenhum consumo tiveram a mesma taxa de consumo das que o fizeram.' WHERE (`STATIC_LABEL_LANGUAGE_ID` = '266138');

