/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cc.altius.FASP.test;

import cc.altius.FASP.model.DatasetPlanningUnit;
import cc.altius.FASP.model.EmptyDoubleTypeAdapter;
import cc.altius.FASP.model.EmptyIntegerTypeAdapter;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;
import java.util.List;

/**
 *
 * @author akil
 */
public class GsonTest {

    public static void main(String[] args) {
        String json = "[\n"
                + "        {\n"
                + "            \"programPlanningUnitId\": 48,\n"
                + "            \"planningUnit\": {\n"
                + "                \"id\": 2882,\n"
                + "                \"label\": {\n"
                + "                    \"createdBy\": null,\n"
                + "                    \"createdDate\": null,\n"
                + "                    \"lastModifiedBy\": null,\n"
                + "                    \"lastModifiedDate\": null,\n"
                + "                    \"active\": true,\n"
                + "                    \"labelId\": 9813,\n"
                + "                    \"label_en\": \"Emtricitabine/Tenofovir DF 200/300 mg Tablet, 30 Tablets\",\n"
                + "                    \"label_sp\": null,\n"
                + "                    \"label_fr\": null,\n"
                + "                    \"label_pr\": null\n"
                + "                },\n"
                + "                \"unit\": {\n"
                + "                    \"id\": 7,\n"
                + "                    \"label\": {\n"
                + "                        \"createdBy\": null,\n"
                + "                        \"createdDate\": null,\n"
                + "                        \"lastModifiedBy\": null,\n"
                + "                        \"lastModifiedDate\": null,\n"
                + "                        \"active\": true,\n"
                + "                        \"labelId\": 149,\n"
                + "                        \"label_en\": \"Bottle\",\n"
                + "                        \"label_sp\": null,\n"
                + "                        \"label_fr\": null,\n"
                + "                        \"label_pr\": null\n"
                + "                    },\n"
                + "                    \"code\": \"BOT\",\n"
                + "                    \"idString\": \"7\"\n"
                + "                },\n"
                + "                \"multiplier\": 30,\n"
                + "                \"forecastingUnit\": {\n"
                + "                    \"id\": 205,\n"
                + "                    \"label\": {\n"
                + "                        \"createdBy\": null,\n"
                + "                        \"createdDate\": null,\n"
                + "                        \"lastModifiedBy\": null,\n"
                + "                        \"lastModifiedDate\": null,\n"
                + "                        \"active\": true,\n"
                + "                        \"labelId\": 1498,\n"
                + "                        \"label_en\": \"Emtricitabine/Tenofovir DF 200/300 mg Tablet\",\n"
                + "                        \"label_sp\": null,\n"
                + "                        \"label_fr\": null,\n"
                + "                        \"label_pr\": null\n"
                + "                    },\n"
                + "                    \"unit\": {\n"
                + "                        \"id\": 65,\n"
                + "                        \"label\": {\n"
                + "                            \"createdBy\": null,\n"
                + "                            \"createdDate\": null,\n"
                + "                            \"lastModifiedBy\": null,\n"
                + "                            \"lastModifiedDate\": null,\n"
                + "                            \"active\": true,\n"
                + "                            \"labelId\": 1066,\n"
                + "                            \"label_en\": \"Tablet\",\n"
                + "                            \"label_sp\": null,\n"
                + "                            \"label_fr\": null,\n"
                + "                            \"label_pr\": null\n"
                + "                        },\n"
                + "                        \"code\": \"Tablet\",\n"
                + "                        \"idString\": \"65\"\n"
                + "                    },\n"
                + "                    \"tracerCategory\": {\n"
                + "                        \"id\": 3,\n"
                + "                        \"label\": {\n"
                + "                            \"createdBy\": null,\n"
                + "                            \"createdDate\": null,\n"
                + "                            \"lastModifiedBy\": null,\n"
                + "                            \"lastModifiedDate\": null,\n"
                + "                            \"active\": true,\n"
                + "                            \"labelId\": 1170,\n"
                + "                            \"label_en\": \"Adult ARV\",\n"
                + "                            \"label_sp\": null,\n"
                + "                            \"label_fr\": null,\n"
                + "                            \"label_pr\": null\n"
                + "                        },\n"
                + "                        \"idString\": \"3\"\n"
                + "                    },\n"
                + "                    \"idString\": \"205\"\n"
                + "                },\n"
                + "                \"idString\": \"2882\"\n"
                + "            },\n"
                + "            \"consuptionForecast\": true,\n"
                + "            \"treeForecast\": true,\n"
                + "            \"stock\": 0,\n"
                + "            \"existingShipments\": 0,\n"
                + "            \"monthsOfStock\": 3,\n"
                + "            \"procurementAgent\": null,\n"
                + "            \"price\": 3.95,\n"
                + "            \"higherThenConsumptionThreshold\": null,\n"
                + "            \"lowerThenConsumptionThreshold\": null,\n"
                + "            \"consumptionNotes\": null,\n"
                + "            \"consumptionDataType\": 2,\n"
                + "            \"otherUnit\": null,\n"
                + "            \"selectedForecastMap\": {\n"
                + "                \"54\": {\n"
                + "                    \"scenarioId\": \"25\",\n"
                + "                    \"consumptionExtrapolationId\": \"\",\n"
                + "                    \"totalForecast\": 4133.05,\n"
                + "                    \"notes\": \"\"\n"
                + "                }\n"
                + "            },\n"
                + "            \"createdBy\": null,\n"
                + "            \"createdDate\": null\n"
                + "        },\n"
                + "        {\n"
                + "            \"programPlanningUnitId\": 49,\n"
                + "            \"planningUnit\": {\n"
                + "                \"id\": 4039,\n"
                + "                \"label\": {\n"
                + "                    \"createdBy\": null,\n"
                + "                    \"createdDate\": null,\n"
                + "                    \"lastModifiedBy\": null,\n"
                + "                    \"lastModifiedDate\": null,\n"
                + "                    \"active\": true,\n"
                + "                    \"labelId\": 10970,\n"
                + "                    \"label_en\": \"Lopinavir/Ritonavir 200/50 mg Tablet, 120 Tablets\",\n"
                + "                    \"label_sp\": null,\n"
                + "                    \"label_fr\": null,\n"
                + "                    \"label_pr\": null\n"
                + "                },\n"
                + "                \"unit\": {\n"
                + "                    \"id\": 7,\n"
                + "                    \"label\": {\n"
                + "                        \"createdBy\": null,\n"
                + "                        \"createdDate\": null,\n"
                + "                        \"lastModifiedBy\": null,\n"
                + "                        \"lastModifiedDate\": null,\n"
                + "                        \"active\": true,\n"
                + "                        \"labelId\": 149,\n"
                + "                        \"label_en\": \"Bottle\",\n"
                + "                        \"label_sp\": null,\n"
                + "                        \"label_fr\": null,\n"
                + "                        \"label_pr\": null\n"
                + "                    },\n"
                + "                    \"code\": \"BOT\",\n"
                + "                    \"idString\": \"7\"\n"
                + "                },\n"
                + "                \"multiplier\": 120,\n"
                + "                \"forecastingUnit\": {\n"
                + "                    \"id\": 38,\n"
                + "                    \"label\": {\n"
                + "                        \"createdBy\": null,\n"
                + "                        \"createdDate\": null,\n"
                + "                        \"lastModifiedBy\": null,\n"
                + "                        \"lastModifiedDate\": null,\n"
                + "                        \"active\": true,\n"
                + "                        \"labelId\": 1274,\n"
                + "                        \"label_en\": \"Lopinavir/Ritonavir 200/50 mg Tablet\",\n"
                + "                        \"label_sp\": null,\n"
                + "                        \"label_fr\": null,\n"
                + "                        \"label_pr\": null\n"
                + "                    },\n"
                + "                    \"unit\": {\n"
                + "                        \"id\": 65,\n"
                + "                        \"label\": {\n"
                + "                            \"createdBy\": null,\n"
                + "                            \"createdDate\": null,\n"
                + "                            \"lastModifiedBy\": null,\n"
                + "                            \"lastModifiedDate\": null,\n"
                + "                            \"active\": true,\n"
                + "                            \"labelId\": 1066,\n"
                + "                            \"label_en\": \"Tablet\",\n"
                + "                            \"label_sp\": null,\n"
                + "                            \"label_fr\": null,\n"
                + "                            \"label_pr\": null\n"
                + "                        },\n"
                + "                        \"code\": \"Tablet\",\n"
                + "                        \"idString\": \"65\"\n"
                + "                    },\n"
                + "                    \"tracerCategory\": {\n"
                + "                        \"id\": 3,\n"
                + "                        \"label\": {\n"
                + "                            \"createdBy\": null,\n"
                + "                            \"createdDate\": null,\n"
                + "                            \"lastModifiedBy\": null,\n"
                + "                            \"lastModifiedDate\": null,\n"
                + "                            \"active\": true,\n"
                + "                            \"labelId\": 1170,\n"
                + "                            \"label_en\": \"Adult ARV\",\n"
                + "                            \"label_sp\": null,\n"
                + "                            \"label_fr\": null,\n"
                + "                            \"label_pr\": null\n"
                + "                        },\n"
                + "                        \"idString\": \"3\"\n"
                + "                    },\n"
                + "                    \"idString\": \"38\"\n"
                + "                },\n"
                + "                \"idString\": \"4039\"\n"
                + "            },\n"
                + "            \"consuptionForecast\": true,\n"
                + "            \"treeForecast\": true,\n"
                + "            \"stock\": 0,\n"
                + "            \"existingShipments\": 0,\n"
                + "            \"monthsOfStock\": 3,\n"
                + "            \"procurementAgent\": null,\n"
                + "            \"price\": 16.9,\n"
                + "            \"higherThenConsumptionThreshold\": null,\n"
                + "            \"lowerThenConsumptionThreshold\": null,\n"
                + "            \"consumptionNotes\": null,\n"
                + "            \"consumptionDataType\": 2,\n"
                + "            \"otherUnit\": null,\n"
                + "            \"selectedForecastMap\": {\n"
                + "                \"54\": {\n"
                + "                    \"scenarioId\": \"25\",\n"
                + "                    \"consumptionExtrapolationId\": \"\",\n"
                + "                    \"totalForecast\": 5707.52,\n"
                + "                    \"notes\": \"\"\n"
                + "                }\n"
                + "            },\n"
                + "            \"createdBy\": null,\n"
                + "            \"createdDate\": null\n"
                + "        },\n"
                + "        {\n"
                + "            \"programPlanningUnitId\": 50,\n"
                + "            \"planningUnit\": {\n"
                + "                \"id\": 3827,\n"
                + "                \"label\": {\n"
                + "                    \"createdBy\": null,\n"
                + "                    \"createdDate\": null,\n"
                + "                    \"lastModifiedBy\": null,\n"
                + "                    \"lastModifiedDate\": null,\n"
                + "                    \"active\": true,\n"
                + "                    \"labelId\": 10758,\n"
                + "                    \"label_en\": \"Lamivudine/Zidovudine 150/300 mg Tablet, 60 Tablets\",\n"
                + "                    \"label_sp\": null,\n"
                + "                    \"label_fr\": null,\n"
                + "                    \"label_pr\": null\n"
                + "                },\n"
                + "                \"unit\": {\n"
                + "                    \"id\": 7,\n"
                + "                    \"label\": {\n"
                + "                        \"createdBy\": null,\n"
                + "                        \"createdDate\": null,\n"
                + "                        \"lastModifiedBy\": null,\n"
                + "                        \"lastModifiedDate\": null,\n"
                + "                        \"active\": true,\n"
                + "                        \"labelId\": 149,\n"
                + "                        \"label_en\": \"Bottle\",\n"
                + "                        \"label_sp\": null,\n"
                + "                        \"label_fr\": null,\n"
                + "                        \"label_pr\": null\n"
                + "                    },\n"
                + "                    \"code\": \"BOT\",\n"
                + "                    \"idString\": \"7\"\n"
                + "                },\n"
                + "                \"multiplier\": 60,\n"
                + "                \"forecastingUnit\": {\n"
                + "                    \"id\": 214,\n"
                + "                    \"label\": {\n"
                + "                        \"createdBy\": null,\n"
                + "                        \"createdDate\": null,\n"
                + "                        \"lastModifiedBy\": null,\n"
                + "                        \"lastModifiedDate\": null,\n"
                + "                        \"active\": true,\n"
                + "                        \"labelId\": 1516,\n"
                + "                        \"label_en\": \"Lamivudine/Zidovudine 150/300 mg Tablet\",\n"
                + "                        \"label_sp\": null,\n"
                + "                        \"label_fr\": null,\n"
                + "                        \"label_pr\": null\n"
                + "                    },\n"
                + "                    \"unit\": {\n"
                + "                        \"id\": 65,\n"
                + "                        \"label\": {\n"
                + "                            \"createdBy\": null,\n"
                + "                            \"createdDate\": null,\n"
                + "                            \"lastModifiedBy\": null,\n"
                + "                            \"lastModifiedDate\": null,\n"
                + "                            \"active\": true,\n"
                + "                            \"labelId\": 1066,\n"
                + "                            \"label_en\": \"Tablet\",\n"
                + "                            \"label_sp\": null,\n"
                + "                            \"label_fr\": null,\n"
                + "                            \"label_pr\": null\n"
                + "                        },\n"
                + "                        \"code\": \"Tablet\",\n"
                + "                        \"idString\": \"65\"\n"
                + "                    },\n"
                + "                    \"tracerCategory\": {\n"
                + "                        \"id\": 3,\n"
                + "                        \"label\": {\n"
                + "                            \"createdBy\": null,\n"
                + "                            \"createdDate\": null,\n"
                + "                            \"lastModifiedBy\": null,\n"
                + "                            \"lastModifiedDate\": null,\n"
                + "                            \"active\": true,\n"
                + "                            \"labelId\": 1170,\n"
                + "                            \"label_en\": \"Adult ARV\",\n"
                + "                            \"label_sp\": null,\n"
                + "                            \"label_fr\": null,\n"
                + "                            \"label_pr\": null\n"
                + "                        },\n"
                + "                        \"idString\": \"3\"\n"
                + "                    },\n"
                + "                    \"idString\": \"214\"\n"
                + "                },\n"
                + "                \"idString\": \"3827\"\n"
                + "            },\n"
                + "            \"consuptionForecast\": true,\n"
                + "            \"treeForecast\": true,\n"
                + "            \"stock\": 0,\n"
                + "            \"existingShipments\": 0,\n"
                + "            \"monthsOfStock\": 3,\n"
                + "            \"procurementAgent\": null,\n"
                + "            \"price\": 6.75,\n"
                + "            \"higherThenConsumptionThreshold\": null,\n"
                + "            \"lowerThenConsumptionThreshold\": null,\n"
                + "            \"consumptionNotes\": null,\n"
                + "            \"consumptionDataType\": 2,\n"
                + "            \"otherUnit\": null,\n"
                + "            \"selectedForecastMap\": {\n"
                + "                \"54\": {\n"
                + "                    \"scenarioId\": \"25\",\n"
                + "                    \"consumptionExtrapolationId\": \"\",\n"
                + "                    \"totalForecast\": 5707.52,\n"
                + "                    \"notes\": \"\"\n"
                + "                }\n"
                + "            },\n"
                + "            \"createdBy\": null,\n"
                + "            \"createdDate\": null\n"
                + "        },\n"
                + "        {\n"
                + "            \"programPlanningUnitId\": 51,\n"
                + "            \"planningUnit\": {\n"
                + "                \"id\": 2733,\n"
                + "                \"label\": {\n"
                + "                    \"createdBy\": null,\n"
                + "                    \"createdDate\": null,\n"
                + "                    \"lastModifiedBy\": null,\n"
                + "                    \"lastModifiedDate\": null,\n"
                + "                    \"active\": true,\n"
                + "                    \"labelId\": 9664,\n"
                + "                    \"label_en\": \"Dolutegravir/Lamivudine/Tenofovir DF 50/300/300 mg Tablet, 30 Tablets\",\n"
                + "                    \"label_sp\": null,\n"
                + "                    \"label_fr\": null,\n"
                + "                    \"label_pr\": null\n"
                + "                },\n"
                + "                \"unit\": {\n"
                + "                    \"id\": 7,\n"
                + "                    \"label\": {\n"
                + "                        \"createdBy\": null,\n"
                + "                        \"createdDate\": null,\n"
                + "                        \"lastModifiedBy\": null,\n"
                + "                        \"lastModifiedDate\": null,\n"
                + "                        \"active\": true,\n"
                + "                        \"labelId\": 149,\n"
                + "                        \"label_en\": \"Bottle\",\n"
                + "                        \"label_sp\": null,\n"
                + "                        \"label_fr\": null,\n"
                + "                        \"label_pr\": null\n"
                + "                    },\n"
                + "                    \"code\": \"BOT\",\n"
                + "                    \"idString\": \"7\"\n"
                + "                },\n"
                + "                \"multiplier\": 30,\n"
                + "                \"forecastingUnit\": {\n"
                + "                    \"id\": 2665,\n"
                + "                    \"label\": {\n"
                + "                        \"createdBy\": null,\n"
                + "                        \"createdDate\": null,\n"
                + "                        \"lastModifiedBy\": null,\n"
                + "                        \"lastModifiedDate\": null,\n"
                + "                        \"active\": true,\n"
                + "                        \"labelId\": 4340,\n"
                + "                        \"label_en\": \"Dolutegravir/Lamivudine/Tenofovir DF 50/300/300 mg Tablet\",\n"
                + "                        \"label_sp\": null,\n"
                + "                        \"label_fr\": null,\n"
                + "                        \"label_pr\": null\n"
                + "                    },\n"
                + "                    \"unit\": {\n"
                + "                        \"id\": 65,\n"
                + "                        \"label\": {\n"
                + "                            \"createdBy\": null,\n"
                + "                            \"createdDate\": null,\n"
                + "                            \"lastModifiedBy\": null,\n"
                + "                            \"lastModifiedDate\": null,\n"
                + "                            \"active\": true,\n"
                + "                            \"labelId\": 1066,\n"
                + "                            \"label_en\": \"Tablet\",\n"
                + "                            \"label_sp\": null,\n"
                + "                            \"label_fr\": null,\n"
                + "                            \"label_pr\": null\n"
                + "                        },\n"
                + "                        \"code\": \"Tablet\",\n"
                + "                        \"idString\": \"65\"\n"
                + "                    },\n"
                + "                    \"tracerCategory\": {\n"
                + "                        \"id\": 3,\n"
                + "                        \"label\": {\n"
                + "                            \"createdBy\": null,\n"
                + "                            \"createdDate\": null,\n"
                + "                            \"lastModifiedBy\": null,\n"
                + "                            \"lastModifiedDate\": null,\n"
                + "                            \"active\": true,\n"
                + "                            \"labelId\": 1170,\n"
                + "                            \"label_en\": \"Adult ARV\",\n"
                + "                            \"label_sp\": null,\n"
                + "                            \"label_fr\": null,\n"
                + "                            \"label_pr\": null\n"
                + "                        },\n"
                + "                        \"idString\": \"3\"\n"
                + "                    },\n"
                + "                    \"idString\": \"2665\"\n"
                + "                },\n"
                + "                \"idString\": \"2733\"\n"
                + "            },\n"
                + "            \"consuptionForecast\": true,\n"
                + "            \"treeForecast\": true,\n"
                + "            \"stock\": 0,\n"
                + "            \"existingShipments\": 0,\n"
                + "            \"monthsOfStock\": 3,\n"
                + "            \"procurementAgent\": null,\n"
                + "            \"price\": 6.45,\n"
                + "            \"higherThenConsumptionThreshold\": null,\n"
                + "            \"lowerThenConsumptionThreshold\": null,\n"
                + "            \"consumptionNotes\": null,\n"
                + "            \"consumptionDataType\": 2,\n"
                + "            \"otherUnit\": null,\n"
                + "            \"selectedForecastMap\": {\n"
                + "                \"54\": {\n"
                + "                    \"scenarioId\": \"25\",\n"
                + "                    \"consumptionExtrapolationId\": \"\",\n"
                + "                    \"totalForecast\": 38154.03,\n"
                + "                    \"notes\": \"\"\n"
                + "                }\n"
                + "            },\n"
                + "            \"createdBy\": null,\n"
                + "            \"createdDate\": null\n"
                + "        },\n"
                + "        {\n"
                + "            \"programPlanningUnitId\": 52,\n"
                + "            \"planningUnit\": {\n"
                + "                \"id\": 4605,\n"
                + "                \"label\": {\n"
                + "                    \"createdBy\": null,\n"
                + "                    \"createdDate\": null,\n"
                + "                    \"lastModifiedBy\": null,\n"
                + "                    \"lastModifiedDate\": null,\n"
                + "                    \"active\": true,\n"
                + "                    \"labelId\": 11536,\n"
                + "                    \"label_en\": \"Nevirapine/Lamivudine/Zidovudine 200/150/300 mg Tablet, 60 Tablets\",\n"
                + "                    \"label_sp\": null,\n"
                + "                    \"label_fr\": null,\n"
                + "                    \"label_pr\": null\n"
                + "                },\n"
                + "                \"unit\": {\n"
                + "                    \"id\": 7,\n"
                + "                    \"label\": {\n"
                + "                        \"createdBy\": null,\n"
                + "                        \"createdDate\": null,\n"
                + "                        \"lastModifiedBy\": null,\n"
                + "                        \"lastModifiedDate\": null,\n"
                + "                        \"active\": true,\n"
                + "                        \"labelId\": 149,\n"
                + "                        \"label_en\": \"Bottle\",\n"
                + "                        \"label_sp\": null,\n"
                + "                        \"label_fr\": null,\n"
                + "                        \"label_pr\": null\n"
                + "                    },\n"
                + "                    \"code\": \"BOT\",\n"
                + "                    \"idString\": \"7\"\n"
                + "                },\n"
                + "                \"multiplier\": 60,\n"
                + "                \"forecastingUnit\": {\n"
                + "                    \"id\": 209,\n"
                + "                    \"label\": {\n"
                + "                        \"createdBy\": null,\n"
                + "                        \"createdDate\": null,\n"
                + "                        \"lastModifiedBy\": null,\n"
                + "                        \"lastModifiedDate\": null,\n"
                + "                        \"active\": true,\n"
                + "                        \"labelId\": 1506,\n"
                + "                        \"label_en\": \"Nevirapine/Lamivudine/Zidovudine 200/150/300 mg Tablet\",\n"
                + "                        \"label_sp\": null,\n"
                + "                        \"label_fr\": null,\n"
                + "                        \"label_pr\": null\n"
                + "                    },\n"
                + "                    \"unit\": {\n"
                + "                        \"id\": 65,\n"
                + "                        \"label\": {\n"
                + "                            \"createdBy\": null,\n"
                + "                            \"createdDate\": null,\n"
                + "                            \"lastModifiedBy\": null,\n"
                + "                            \"lastModifiedDate\": null,\n"
                + "                            \"active\": true,\n"
                + "                            \"labelId\": 1066,\n"
                + "                            \"label_en\": \"Tablet\",\n"
                + "                            \"label_sp\": null,\n"
                + "                            \"label_fr\": null,\n"
                + "                            \"label_pr\": null\n"
                + "                        },\n"
                + "                        \"code\": \"Tablet\",\n"
                + "                        \"idString\": \"65\"\n"
                + "                    },\n"
                + "                    \"tracerCategory\": {\n"
                + "                        \"id\": 3,\n"
                + "                        \"label\": {\n"
                + "                            \"createdBy\": null,\n"
                + "                            \"createdDate\": null,\n"
                + "                            \"lastModifiedBy\": null,\n"
                + "                            \"lastModifiedDate\": null,\n"
                + "                            \"active\": true,\n"
                + "                            \"labelId\": 1170,\n"
                + "                            \"label_en\": \"Adult ARV\",\n"
                + "                            \"label_sp\": null,\n"
                + "                            \"label_fr\": null,\n"
                + "                            \"label_pr\": null\n"
                + "                        },\n"
                + "                        \"idString\": \"3\"\n"
                + "                    },\n"
                + "                    \"idString\": \"209\"\n"
                + "                },\n"
                + "                \"idString\": \"4605\"\n"
                + "            },\n"
                + "            \"consuptionForecast\": true,\n"
                + "            \"treeForecast\": true,\n"
                + "            \"stock\": 0,\n"
                + "            \"existingShipments\": 0,\n"
                + "            \"monthsOfStock\": 3,\n"
                + "            \"procurementAgent\": null,\n"
                + "            \"price\": 7.4,\n"
                + "            \"higherThenConsumptionThreshold\": null,\n"
                + "            \"lowerThenConsumptionThreshold\": null,\n"
                + "            \"consumptionNotes\": null,\n"
                + "            \"consumptionDataType\": 2,\n"
                + "            \"otherUnit\": null,\n"
                + "            \"selectedForecastMap\": {\n"
                + "                \"54\": {\n"
                + "                    \"scenarioId\": \"25\",\n"
                + "                    \"consumptionExtrapolationId\": \"\",\n"
                + "                    \"totalForecast\": 63801.99,\n"
                + "                    \"notes\": \"\"\n"
                + "                }\n"
                + "            },\n"
                + "            \"createdBy\": null,\n"
                + "            \"createdDate\": null\n"
                + "        },\n"
                + "        {\n"
                + "            \"programPlanningUnitId\": 53,\n"
                + "            \"planningUnit\": {\n"
                + "                \"id\": 2795,\n"
                + "                \"label\": {\n"
                + "                    \"createdBy\": null,\n"
                + "                    \"createdDate\": null,\n"
                + "                    \"lastModifiedBy\": null,\n"
                + "                    \"lastModifiedDate\": null,\n"
                + "                    \"active\": true,\n"
                + "                    \"labelId\": 9726,\n"
                + "                    \"label_en\": \"Efavirenz 600 mg Tablet, 30 Tablets\",\n"
                + "                    \"label_sp\": null,\n"
                + "                    \"label_fr\": null,\n"
                + "                    \"label_pr\": null\n"
                + "                },\n"
                + "                \"unit\": {\n"
                + "                    \"id\": 7,\n"
                + "                    \"label\": {\n"
                + "                        \"createdBy\": null,\n"
                + "                        \"createdDate\": null,\n"
                + "                        \"lastModifiedBy\": null,\n"
                + "                        \"lastModifiedDate\": null,\n"
                + "                        \"active\": true,\n"
                + "                        \"labelId\": 149,\n"
                + "                        \"label_en\": \"Bottle\",\n"
                + "                        \"label_sp\": null,\n"
                + "                        \"label_fr\": null,\n"
                + "                        \"label_pr\": null\n"
                + "                    },\n"
                + "                    \"code\": \"BOT\",\n"
                + "                    \"idString\": \"7\"\n"
                + "                },\n"
                + "                \"multiplier\": 30,\n"
                + "                \"forecastingUnit\": {\n"
                + "                    \"id\": 323,\n"
                + "                    \"label\": {\n"
                + "                        \"createdBy\": null,\n"
                + "                        \"createdDate\": null,\n"
                + "                        \"lastModifiedBy\": null,\n"
                + "                        \"lastModifiedDate\": null,\n"
                + "                        \"active\": true,\n"
                + "                        \"labelId\": 1682,\n"
                + "                        \"label_en\": \"Efavirenz 600 mg Tablet\",\n"
                + "                        \"label_sp\": null,\n"
                + "                        \"label_fr\": null,\n"
                + "                        \"label_pr\": null\n"
                + "                    },\n"
                + "                    \"unit\": {\n"
                + "                        \"id\": 65,\n"
                + "                        \"label\": {\n"
                + "                            \"createdBy\": null,\n"
                + "                            \"createdDate\": null,\n"
                + "                            \"lastModifiedBy\": null,\n"
                + "                            \"lastModifiedDate\": null,\n"
                + "                            \"active\": true,\n"
                + "                            \"labelId\": 1066,\n"
                + "                            \"label_en\": \"Tablet\",\n"
                + "                            \"label_sp\": null,\n"
                + "                            \"label_fr\": null,\n"
                + "                            \"label_pr\": null\n"
                + "                        },\n"
                + "                        \"code\": \"Tablet\",\n"
                + "                        \"idString\": \"65\"\n"
                + "                    },\n"
                + "                    \"tracerCategory\": {\n"
                + "                        \"id\": 3,\n"
                + "                        \"label\": {\n"
                + "                            \"createdBy\": null,\n"
                + "                            \"createdDate\": null,\n"
                + "                            \"lastModifiedBy\": null,\n"
                + "                            \"lastModifiedDate\": null,\n"
                + "                            \"active\": true,\n"
                + "                            \"labelId\": 1170,\n"
                + "                            \"label_en\": \"Adult ARV\",\n"
                + "                            \"label_sp\": null,\n"
                + "                            \"label_fr\": null,\n"
                + "                            \"label_pr\": null\n"
                + "                        },\n"
                + "                        \"idString\": \"3\"\n"
                + "                    },\n"
                + "                    \"idString\": \"323\"\n"
                + "                },\n"
                + "                \"idString\": \"2795\"\n"
                + "            },\n"
                + "            \"consuptionForecast\": true,\n"
                + "            \"treeForecast\": true,\n"
                + "            \"stock\": 0,\n"
                + "            \"existingShipments\": 0,\n"
                + "            \"monthsOfStock\": 3,\n"
                + "            \"procurementAgent\": null,\n"
                + "            \"price\": 2.95,\n"
                + "            \"higherThenConsumptionThreshold\": null,\n"
                + "            \"lowerThenConsumptionThreshold\": null,\n"
                + "            \"consumptionNotes\": null,\n"
                + "            \"consumptionDataType\": 2,\n"
                + "            \"otherUnit\": null,\n"
                + "            \"selectedForecastMap\": {\n"
                + "                \"54\": {\n"
                + "                    \"scenarioId\": \"23\",\n"
                + "                    \"consumptionExtrapolationId\": \"\",\n"
                + "                    \"totalForecast\": 211966.9,\n"
                + "                    \"notes\": \"\"\n"
                + "                }\n"
                + "            },\n"
                + "            \"createdBy\": null,\n"
                + "            \"createdDate\": null\n"
                + "        },\n"
                + "        {\n"
                + "            \"programPlanningUnitId\": 54,\n"
                + "            \"planningUnit\": {\n"
                + "                \"id\": 1082,\n"
                + "                \"label\": {\n"
                + "                    \"createdBy\": null,\n"
                + "                    \"createdDate\": null,\n"
                + "                    \"lastModifiedBy\": null,\n"
                + "                    \"lastModifiedDate\": null,\n"
                + "                    \"active\": true,\n"
                + "                    \"labelId\": 8013,\n"
                + "                    \"label_en\": \"Abacavir/Lamivudine 600/300 mg Tablet, 30 Tablets\",\n"
                + "                    \"label_sp\": null,\n"
                + "                    \"label_fr\": null,\n"
                + "                    \"label_pr\": null\n"
                + "                },\n"
                + "                \"unit\": {\n"
                + "                    \"id\": 7,\n"
                + "                    \"label\": {\n"
                + "                        \"createdBy\": null,\n"
                + "                        \"createdDate\": null,\n"
                + "                        \"lastModifiedBy\": null,\n"
                + "                        \"lastModifiedDate\": null,\n"
                + "                        \"active\": true,\n"
                + "                        \"labelId\": 149,\n"
                + "                        \"label_en\": \"Bottle\",\n"
                + "                        \"label_sp\": null,\n"
                + "                        \"label_fr\": null,\n"
                + "                        \"label_pr\": null\n"
                + "                    },\n"
                + "                    \"code\": \"BOT\",\n"
                + "                    \"idString\": \"7\"\n"
                + "                },\n"
                + "                \"multiplier\": 30,\n"
                + "                \"forecastingUnit\": {\n"
                + "                    \"id\": 195,\n"
                + "                    \"label\": {\n"
                + "                        \"createdBy\": null,\n"
                + "                        \"createdDate\": null,\n"
                + "                        \"lastModifiedBy\": null,\n"
                + "                        \"lastModifiedDate\": null,\n"
                + "                        \"active\": true,\n"
                + "                        \"labelId\": 1482,\n"
                + "                        \"label_en\": \"Abacavir/Lamivudine 600/300 mg Tablet\",\n"
                + "                        \"label_sp\": null,\n"
                + "                        \"label_fr\": null,\n"
                + "                        \"label_pr\": null\n"
                + "                    },\n"
                + "                    \"unit\": {\n"
                + "                        \"id\": 65,\n"
                + "                        \"label\": {\n"
                + "                            \"createdBy\": null,\n"
                + "                            \"createdDate\": null,\n"
                + "                            \"lastModifiedBy\": null,\n"
                + "                            \"lastModifiedDate\": null,\n"
                + "                            \"active\": true,\n"
                + "                            \"labelId\": 1066,\n"
                + "                            \"label_en\": \"Tablet\",\n"
                + "                            \"label_sp\": null,\n"
                + "                            \"label_fr\": null,\n"
                + "                            \"label_pr\": null\n"
                + "                        },\n"
                + "                        \"code\": \"Tablet\",\n"
                + "                        \"idString\": \"65\"\n"
                + "                    },\n"
                + "                    \"tracerCategory\": {\n"
                + "                        \"id\": 3,\n"
                + "                        \"label\": {\n"
                + "                            \"createdBy\": null,\n"
                + "                            \"createdDate\": null,\n"
                + "                            \"lastModifiedBy\": null,\n"
                + "                            \"lastModifiedDate\": null,\n"
                + "                            \"active\": true,\n"
                + "                            \"labelId\": 1170,\n"
                + "                            \"label_en\": \"Adult ARV\",\n"
                + "                            \"label_sp\": null,\n"
                + "                            \"label_fr\": null,\n"
                + "                            \"label_pr\": null\n"
                + "                        },\n"
                + "                        \"idString\": \"3\"\n"
                + "                    },\n"
                + "                    \"idString\": \"195\"\n"
                + "                },\n"
                + "                \"idString\": \"1082\"\n"
                + "            },\n"
                + "            \"consuptionForecast\": true,\n"
                + "            \"treeForecast\": true,\n"
                + "            \"stock\": 0,\n"
                + "            \"existingShipments\": 0,\n"
                + "            \"monthsOfStock\": 3,\n"
                + "            \"procurementAgent\": null,\n"
                + "            \"price\": 10.23,\n"
                + "            \"higherThenConsumptionThreshold\": null,\n"
                + "            \"lowerThenConsumptionThreshold\": null,\n"
                + "            \"consumptionNotes\": null,\n"
                + "            \"consumptionDataType\": 2,\n"
                + "            \"otherUnit\": null,\n"
                + "            \"selectedForecastMap\": {\n"
                + "                \"54\": {\n"
                + "                    \"scenarioId\": \"23\",\n"
                + "                    \"consumptionExtrapolationId\": \"\",\n"
                + "                    \"totalForecast\": 211966.9,\n"
                + "                    \"notes\": \"\"\n"
                + "                }\n"
                + "            },\n"
                + "            \"createdBy\": null,\n"
                + "            \"createdDate\": null\n"
                + "        }\n"
                + "    ]";
        System.out.println(json);
        System.out.println("json length original=" + json.length());
//        String emptyFuNodeString1 = "\"fuNode\":{\"noOfForecastingUnitsPerPerson\":\"\",\"usageFrequency\":\"\",\"forecastingUnit\":{\"label\":{\"label_en\":\"\"},\"tracerCategory\":{},\"unit\":{\"id\":\"\"}},\"usageType\":{\"id\":\"\"},\"usagePeriod\":{\"usagePeriodId\":\"\"},\"repeatUsagePeriod\":{},\"noOfPersons\":\"\"}";
//        json = json.replace(emptyFuNodeString1, "\"fuNode\": null");
//        json = json.replace(",,", ",");
//        System.out.println("json length after replace fuNode1 =" + json.length());
//        String emptyPuNodeString1 = "\"puNode\":{\"planningUnit\":{\"unit\":{}},\"refillMonths\":\"\"}";
//        json = json.replace(emptyPuNodeString1, "\"puNode\": null");
//        json = json.replace(",,", ",");
//        System.out.println("json length after replacing puNode1 =" + json.length());
//        System.out.println(json);
        GsonBuilder gsonBuilder = new GsonBuilder()
                .registerTypeAdapter(Double.class, new EmptyDoubleTypeAdapter())
                .registerTypeAdapter(Integer.class, new EmptyIntegerTypeAdapter())
                .setLenient()
                .setDateFormat("yyyy-MM-dd HH:mm:ss");
        List<DatasetPlanningUnit> puList = gsonBuilder.create().fromJson(json, new TypeToken<List<DatasetPlanningUnit>>() {
        }.getType());
//        System.out.println(puList.get(0).getSelectedForecastMap().get(54).getTotalForecast());
    }

}
